### ISSUE TITLE
adding reactions | Error: No model reactions found

### ISSUE THREAD

**Issue by danfrks** [jotech/gapseq#101]
Hi,

I am trying to add reactions to a model. Would you please advise about the below error?

```
~$ ./gapseq/gapseq adapt -m "maxbin.001.xml" -a "NAPHTHALENE-12-DIOXYGENASE-RXN"

Loading required package: glpkAPI
using GLPK version 5.0
Warning message:
glpkAPI is used but cplexAPI is recommended because it is much faster 
Loading model files /home/danielfarkas/Desktop/shelf/maxbin.001.xml 
reading SBML file ... OK
getting the model ... OK
creating S and parsing constraints ... OK
GPR mapping ... OK
cleaning up ... OK
validating object ... OK
                               id     id.type                         db.rxn
1: NAPHTHALENE-12-DIOXYGENASE-RXN metacyc rxn NAPHTHALENE-12-DIOXYGENASE-RXN
   seed
1:     
Error: No model reactions found
Execution halted

```

**Comment by danfrks** [comment]
I just realised that it works with the RDS file. - Closed

**Comment by jotech** [comment]
hi @danfrks 
this means that there is no reaction available in the gapseq database that matches the one from metacyc. I will have a look if we can link it!

**Comment by Waschina** [comment]
Hi,

instead of `-m "maxbin.001.xml"` please provide the model's RDS file: `-m "maxbin.001.RDS"`

**Comment by danfrks** [comment]
Thanks for your promt replies.

In the meantime, I realised the RDS file works better (though for some reactions the XML file works too). In addition, I managed to include most of the reactions by adding them by E.C. number (though not all).

**Comment by jotech** [comment]
Hi @danfrks 
sorry for the delay, I just come back to it. The good news is there was indeed an error how we matched the EC metacyc numbers here. I fixed it and it should now also work with the metacyc reaction ids directly in all cases:
```
./gapseq adapt -m toy/myb71.RDS -a "NAPHTHALENE-12-DIOXYGENASE-RXN"
Loading model files toy/myb71.RDS 
                               id     id.type                         db.rxn
1: NAPHTHALENE-12-DIOXYGENASE-RXN metacyc rxn NAPHTHALENE-12-DIOXYGENASE-RXN
                                                                                                                                                                         seed
1: rxn02124 rxn02125 rxn03722 rxn03723 rxn03724 rxn03725 rxn03726 rxn03727 rxn04718 rxn04739 rxn04746 rxn06913 rxn06914 rxn07518 rxn11654 rxn11655 rxn11656 rxn11657 rxn16021
```
please reopen if there is still something wrong :)
