### ISSUE TITLE
Installation instruction (potentially) missing step

### ISSUE THREAD

**Issue by bramvandijk88** [jotech/gapseq#102]
Since R > 4.1 I have noticed there is 1 more step in the installation of gapseq. 

> sudo apt install libcurl4-openssl-dev

If this is not done first, Rcurl installation will fail.

**Comment by jotech** [comment]
hi @bramvandijk88 
thanks for reporting!
I think it is not related to new R version, but you are right there maybe systems without native dev libraries for curl already installed! I will add it to the install readme
