### ISSUE TITLE
[Error] Data connection reset by peer

### ISSUE THREAD

**Issue by camilogarciabotero** [jotech/gapseq#103]
Hi all,

Thanks for working on gapseq. I was playing around with it to predict the metabolic pathways from a bacterial isolate I'm currently working on. So, I went to the docs and installed it via conda, and later installed the needed R libraries. I did that in a HPC with the following characteristics:
```

       #######          --------------------------- 
       ##O#O##          OS: Rocky Linux 8.5 (Green Obsidian) x86_64 
       #######          Host: PowerEdge R730 
     ###########        Kernel: 4.18.0-348.12.2.el8_5.x86_64 
    #############       Uptime: 19 days, 22 hours, 7 mins 
   ###############      Packages: 1107 (rpm) 
   ################     Shell: bash 4.4.20 
  #################     Resolution: 1024x768 
#####################   Terminal: /dev/pts/7 
#####################   CPU: Intel Xeon E5-2683 v4 (64) @ 3.000GHz 
  #################     GPU: 0a:00.0 Matrox Electronics Systems Ltd. G200eR2 
                        Memory: 2340MiB / 31854MiB 
```
Installation of gapseq was apparently succesful as the resulted output of `gapseq test` showed it passes the 3 tests, yet some perl warnings started to pop up (several times):

```

gapseq version: 1.1 fbb651e
linux-gnu
#1 SMP Wed Jan 19 17:53:40 UTC 2022 


#######################
#Checking dependencies#
#######################
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.4
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.12.0+
exonerate from exonerate version 2.4.0
bedtools v2.30.0
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
R scripting front-end version 4.1.2 (2021-11-01)
git version 2.35.0
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
GNU parallel 20211222

Missing dependencies: 0


#####################
#Checking R packages#
#####################
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
data.table 1.14.2 
stringr 1.4.0 
sybil 2.2.0 
getopt 1.20.3 
doParallel 1.0.17 
foreach 1.5.2 
R.utils 2.11.0 
stringi 1.7.6 
glpkAPI 1.3.3 
BiocManager 1.30.16 
Biostrings 2.62.0 
jsonlite 1.7.3 
CHNOSZ 1.4.2 

Missing R packages:  0 


##############################
#Checking basic functionality#
##############################
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
Optimization test: OK 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
Building full model: OK 
Blast test: OK

Passed tests: 3/3

```
Then I made some first runs and then the perl warning poped up again and the process of updating sequences databases appeared aborted:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
index file Btequilensis_EA-CB0015.fna.tmp.fai not found, generating...
2022-02-13 14:26:28 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [193] -> ".listing" [1]
2022-02-13 14:26:29 (0.00 B/s) - Data connection: Connection reset by peer; Data transfer aborted.
...
2022-02-13 14:29:09 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [194] -> ".listing" [1]
2022-02-13 14:26:29 (0.00 B/s) - Data connection: Connection reset by peer; Data transfer aborted.
...
2022-02-13 14:31:51 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz [193] -> ".listing" [1]
2022-02-13 14:26:29 (0.00 B/s) - Data connection: Connection reset by peer; Data transfer aborted.
...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Any thoughts to solve this issue would be very helpful, 
Thanks in advance!

**Comment by Waschina** [comment]
Hi,
I'm not sure about the perl warning, but a quick web search suggests that this is related to the system setup. You may find a solution for example here: https://stackoverflow.com/questions/2499794/how-to-fix-a-locale-setting-warning-from-perl

For the download part: Could you try to run `src/./update_sequences.sh` in your gapseq directory?

**Comment by camilogarciabotero** [comment]
Hi @Waschina 

Yep, the system setup issue was solved with the suggested exports:

```
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

On the other hand, I tried locally the `bash src/./update_sequences.sh` and got the same error as the previous comment. Could that be a matter of permissions on the server? I will ask if that might be an issue and keep this issue updated.

Thanks for your help.

**Comment by Waschina** [comment]
The permissions on the FTP-Server are correctly set. The data connection error could also be caused by any machine along the transfer route. My guess is that one of the servers along the route does not allow bulk downloads via curl or wget. 

Could you try the following?
```
status_rev=$(curl -s --head -w %{http_code} ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz -o /dev/null)
echo $status_rev
```
That should ideally return `350` .

If that worked, could you try this:
```
wget -nv -N ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz
```

If that does not work, maybe the HPC system does not allow you to download files via wget. Maybe you could contact someone from the HPC admins and ask why this `wget` command above returns this error and if they have a suggestion?

**Comment by Waschina** [comment]
Okay, at least we found the command that causes the issue. I'm curious what your HPC admins think. In case the wget option cannot be enabled, please let me know and we can find a workaround. 

Best wishes

**Comment by jotech** [comment]
hm from the error log, it sound like a firewall issue to me!
looking forward to hear what the sys admin is saying :)

**Comment by camilogarciabotero** [comment]
Hi @Waschina and @jotech 

I just received an answer from the server administrators confirming this was an issue with the firewall of the server. So, I will download the files on my laptop and then upload them to my server account. Do I need to download something else than:

```
wget -nv -N ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz
```

Thanks again for your support.

**Comment by jotech** [comment]
hi @camilogarciabotero 
wow this is super strange! They are not willingly to change anything? Downloading from another university server shouldn't be such a security risk ..
Anyway, you need these files:

- `ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz`
- `ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz`
- `ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz`

The files must be put into the folders:
- `gapseq/dat/seq/Bacteria/rev/`
- `gapseq/dat/seq/Bacteria/unrev/`
- `gapseq/dat/seq/Bacteria/rxn/`

But if you have it already working on your laptop maybe the easiest way is to copy the complete gapseq folder?

**Comment by camilogarciabotero** [comment]
Hi @jotech 

Yeah, I reported the case. The server OS was just updated and I guess they will review this issue further, since `wget` is anywhere they surely don't want to see this problem popping up.

I will then set up those folders and hope to run the program soon.
Thanks again for all your support!

**Comment by camilogarciabotero** [comment]
Ok,

So I moved all the `sequences.tar.gz` to the corresponding folders. Now it turns out that when running the command:

```
gapseq doall genome.fna.gz -o out-folder
```
 The `sequences.tar.gz` files are replaced by the image of the updating attempt... So they end up being empty. Is there a way to disable the update step? Or any other way to sort that out?

**Comment by dutchscientist** [comment]
I can't even run the update from the ubuntu Linux terminal computers I use for testing and training. It is a firewall issue, even though they say they have fully opened the firewall, gapseq and a recent version of AMRfinder Plus from NCBI can't update via FTP. Unfortunately the gapseq command starts with looking for updates, meaning I can't run it on there.

I am going to try on a "proper" Linux computer, but it is a pity FTP causes difficulties.

**Comment by jotech** [comment]
Hi @dutchscientist 
I added a parameter to disable the check for updates (`gapseq find -O`). Could you give it a try? 
Please be aware that sequences must be present so you will have to copy it manually as mentioned above

**Comment by dutchscientist** [comment]
Yes, the -O works 👍 

It all worked fine on my dedicated Linux station which runs from my home network, so it is clearly a firewall issue at our work internet side. IT is scared of FTP sites....

**Comment by dutchscientist** [comment]
Our IT has looked into it and reported

"I believe the application was connecting using “active” FTP- this picks a random high TCP port number for communication, not the usual port 21 that FTP uses, so normal “passive” FTP was open and communicating, but the other random ports were being blocked at the firewall."

Is switching to passive FTP an option?

**Comment by jotech** [comment]
hi @dutchscientist 
sorry I just come back to the issue!

As far as I know, passive ftp, which opens a high port from the client side, is the default way how wget is downloading via ftp!

But we can take it the other way around and try whether active ftp works:
```
wget --no-passive-ftp ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz
```
Could you give it a try?

**Comment by jotech** [comment]
please reopen if still an issue
