### ISSUE TITLE
Typo in "-m" option for ./gapseq find leads to limited pathways search

### ISSUE THREAD

**Issue by BizzoTL** [jotech/gapseq#104]
Hello,
I'm writing to report a possible bug.
When I was using the find function with the parameter -m I accidentally typed "archea" instead of "archaea". This led to a limited search in the pathways available with only 10 reactions against the 360+ if I used the correct name. This also happens for every word that is not "auto", "bacteria" or "archaea". I would suggest raising a warning if the taxonomic range that the user inputs is different from the keywords used during the taxonomic assignation.

The command I used:
`./gapseq find -p all -b 200 -m archea mygenome.fna`
My gapseq version:
`1.1 2ec4c84`

Thank you

**Comment by jotech** [comment]
good point and thank you for reporting! I will have a look
