### ISSUE TITLE
Do the gapseq DBs include mucin pathways?

### ISSUE THREAD

**Issue by cdiener** [jotech/gapseq#105]
Hi I wanted to port some gut media compositions that we had to gapseq but could not find any mucin-related compounds in the `nutrients.csv` files. Are mucin breakdown pathways included in the gapseq DBs? And if yes, is there a list of the mucin core molecules?

Thanks!

**Comment by jotech** [comment]
hi @cdiener 
yes there is mucin support in gapseq, it was added some time ago: d3bba87128fe06caa928e2fe10a45b26f32f0b51
In more detail, I usually use the following components when mucus is supposed to be accessible for the bacteria:
```
cpd00122,acgam
cpd00232,acnam
cpd00751,fucose
cpd00108,galactose
cpd00832,acgal
cpd11842,mucuscore
cpd02992,mucuscore
```
What do you think of it?

**Comment by Waschina** [comment]
Just a small addition: In relation to https://doi.org/10.1074/jbc.R112.418558, `cpd11842` is core 3 and `cpd02992` is core 4.

**Comment by cdiener** [comment]
Perfect that is exactly what I was looking for. Thanks!
