### ISSUE TITLE
`gapseq doall` silently replaces medium if file can't be read

### ISSUE THREAD

**Issue by cdiener** [jotech/gapseq#107]
`gapseq doall` will ignore the medium argument and always use the `${id}-medium.csv` for me even if called with another medium. 

The call command was:

```
gapseq -n doall DSM.fasta /opt/gapseq/data/media/gut.csv > DSM.log
```

Which produces the attached log.

[DSM.log](https://github.com/jotech/gapseq/files/8093011/DSM.log)

Relevant line:

```
using media file DSM-medium.csv
```

which ignores the set medium.

**Comment by cdiener** [comment]
Oh I see this is supposed to be a boolean flag. My bad.

**Comment by cdiener** [comment]
This does not seems to have anything to do with the position of the `-n` parameter either, the same occurs with

```bash
gapseq doall DSM.fasta /opt/gapseq/data/media/gut.csv > DSM.log
```

**Comment by cdiener** [comment]
My bad, this was due to the docker container not having access to the file. Though I would have expected `gapseq` to raise an error if the medium can't be read ot the file does not exist. I think silently substituting the medium could lead to problems when analyzing the model later on.

**Comment by jotech** [comment]
Hi @cdiener you are right, we didn't checked for read access of the input files! I added some permission check and an error should be raised from now on! Thank you for reporting
