### ISSUE TITLE
How to get more carbon sources or fermentation products in fill step?

### ISSUE THREAD

**Issue by Erique29** [jotech/gapseq#108]
Hi again,
I tried the new function of prediction of carbon sources and fermentation products, and it is useful for me. I can get two lists of the same kind of 186 carbon sources or fermentation products. Can I add more carbon sources or fermentation products in this step? I don't know which is the key file. Thanks!
Best,
Erique

**Comment by Waschina** [comment]
Hi Erique,

could you provide some more detail on what you would like to achieve? Are you referring to the `gapseq medium` module to predict a gap-fill medium? At what stage of the gapseq workflow do you want to add additional carbon sources?

**Comment by jotech** [comment]
just to add to add shortly: candidate carbon sources and fermentation products are listed in: https://github.com/jotech/gapseq/blob/master/dat/subex.tbl

**Comment by Erique29** [comment]
Hi @Waschina,
In the last step (gapseq fill), I use the new function (-w) to get the information of carbon sources and fermentation products. But many carbon sources that I want to explore are not on the list. So, I want to add more targets to the results. I will add some carbon sources in dat/subex.tbl as @jotech suggested. Thanks a lot.
Best,
Erique

**Comment by Erique29** [comment]
Hi @jotech,
I will try it, Thanks!
Best,
Erique

**Comment by jotech** [comment]
Hi @Erique29 
do you mind to share which carbon sources are missing? Maybe we can add them so that they could be found by default

**Comment by Erique29** [comment]
Hi @jotech ,
Sure, I check subex.tbl, some carbon sources from BIOLOG test were not included. Like,

- β-Methyl-D-Glucoside	EX_cpd11603_e0
- N-Acetyl-β-D-Mannosamine	EX_cpd27563_e0
- D-Fucose	EX_cpd00750_e0
- D-Fructose-6-PO4	EX_cpd00072_e0
- Gelatin	EX_cpd11879_e0
- D-Malic Acid	EX_cpd00386_e0
- D-Aspartic Acid	EX_cpd00320_e0
- Glycyl-L-Proline	EX_cpd22832_e0
- Acetoacetic Acid	EX_cpd00142_e2
- Methyl Pyruvate	EX_cpd24420_e2
- D-Lactic Acid Methyl Ester	EX_cpd24428_e2
- 3-Methyl Glucose	EX_cpd26351_e2
- L-Galactonic Acid Lactone	EX_cpd00820_e3
- p-Hydroxy-Phenylacetic Acid	EX_cpd00489_e3
- Bromo-Succinic Acid	EX_cpd23859_e4
- γ-Amino-Butryric Acid	EX_cpd00281_e5
- β-Hydroxy-D,L Butyric Acid	EX_cpd02042_e6

Can I ask another question? There are 369 candidate carbon sources and fermentation products in the list. But there was only part of them shown in the cs.tbl and ferm.tbl.  How can I get the full list? Thank!

[cs.xls](https://github.com/jotech/gapseq/files/8287164/cs.xls)

Best

**Comment by jchmiel4** [comment]
@jotech Apologies for hijacking this closed comment, but it might be useful for other bacteria. Would it be possible to add the following compound to the list?

Oxalic Acid;oxalate   EX_oxa(e)   EX_cpd00180_e0   Carboxylic acids

**Comment by jotech** [comment]
Many thanks for reviving this thread! Yes, adding oxalate makes sense, and I just committed it!

The problem with the compounds @Erique29 provided some time ago was that many of them are, as far as I see, not well connected with downstream reactions and would potentially lead to artifacts slowing down the gap-filling.

But maybe it makes sense to rethink some of them. Anyway sorry for the late reply @Erique29!
