### ISSUE TITLE
Exchange Reaction of Manganese

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#11]
Dear All,

I would like to ask you concerning the exchange reaction of manganese in TSB medium. Why did you choose the identifier `cpd00030` instead of `cpd20864` or `cpd20863`?

Kind Regards,
Georgios

P.S.: This type of question may be valid for other compounds also.

**Comment by jotech** [comment]
the identifier with lower numbers are more trustworthy. If you have a look at reactions, which are using the compounds, you can see that these compounds are the ones that are widely used in metabolism. From my opinion the higher number metabolites are duplicates and come maybe from database merging.

**Comment by maringos** [comment]
Interesting! Thanks for the answer!
