### ISSUE TITLE
Gap-filling for AGORA models

### ISSUE THREAD

**Issue by shraddhakhirwadkar** [jotech/gapseq#111]
Hi,
I wanted to use GapSeq to gap-fill AGORA models. I was following the tutorial: https://gapseq.readthedocs.io/en/latest/tutorials/crossfeeding.html and I was wondering what I could use as rxnWeights.RDS and rxnXgenes.RDS if I am just interested in gap-filling an already existing metabolic model. Any help is appreciated!
Thank you,
Shraddha Khirwadkar

**Comment by Waschina** [comment]
Hi Shraddha,
the gapfilling algorithm of gapseq does only work with gapseq reconstruction, because it relies on outputs from the upstream gapseq command `gapseq draft`.
Best,
Silvio
