### ISSUE TITLE
Some reactions which were annotated as 'no_blast' or 'no seq data' in draft model

### ISSUE THREAD

**Issue by Zhelunnn** [jotech/gapseq#116]
> for bug reports and errors please report the output of: ./gapseq test
Hi Silvio

Recently, I found some reactions which were annotated as 'no_blast' or 'no seq data' in my draft model. The os.origin of them are '0'. I think these reactions should be added during the gapfill stage. This also seriously confused me. Could you have some comments on this?

**Comment by Waschina** [comment]
Hi @Zhelunnn 

which reactions IDs are these? And o you perhaps have a test case where you could share the `-draft.RDS` and `all-Reactions.tsv` ?

**Comment by Waschina** [comment]
The results in `1_reactions.tbl` and the reactions in `draft.RDS` do indeed not fit together. There are reactions ans genes in the draft network that do not occur in the `1_reactions.tbl` table.

Which exact gapseq commands did you use?

**Comment by Zhelunnn** [comment]
This is only small part of all the reactions (around 10 percent of the 'all-Reactions.tsv'). The complete file is more than 200 MB, which exceeds the limited file size of github. So I am not able to upload it completely. If you need all of it, can I send it to you via email?

**Comment by Waschina** [comment]
I understand. Could you provide the exact gapseq commands that you used? `gapseq find ...`, `gapseq find-transport ...`, and `gapseq draft ...`? Without the commands I cannot make a good guess on the underlying issue.

A side note: The network and the reaction table is huge (given that it's only 10%). Is it possible that you used gapseq with a whole metagenome assembly and not individual Bins/MAGs? Gapseq is designed for microbial genomes, not unbinned metagenome assemblies.

**Comment by Zhelunnn** [comment]
Thank you for this.  The exact commands I used are below.
  gapseq find -p all -b 100 -c 70 -l all -y model.fna
  gapseq find-transport -c 70 model.fna
  gapseq draft -r all-Reactions.tbl -u 100 -l 50 -t Transporter.tbl -p all-Pathways.tbl -c model.fna

I indeed used an individual MAGs to run gapseq. The mag had more than 90 % completeness and around 1 % contamination based on checkM result. I also found that most of my models have around 210 no_blast-reactions. Hope this could help your check-out.

**Comment by Waschina** [comment]
Hi,

I think it could be due to the parameter `-l all` in gapseq find. This option is helpful for pathway analysis that includes also other pathway databases such as KEGG in addition to metacyc. However, if you goal is to get a genome-scale model for flux balance analysis, I'd recommend following commands:

```sh
gapseq find -p all -m Bacteria model.fna
gapseq find-transport model.fna
gapseq draft -r model-all-Reactions.tbl -t model-Transporter.tbl -p model-all-Pathways.tbl -c model.fna -u 200 -l 100
```

**Comment by Zhelunnn** [comment]
Thank you for this, Silvio. But I have to say I couldn't quite understand why '-l all' would cause this.  Could you please make it clear? Should I think these 'no_blast' reactions as absent or present? Actually, in my project, I need to consider multiple database result.

**Comment by Waschina** [comment]
I'm not sure why `-l all` could have caused the issue. For your example I would need the entire "...-all-Reactions.tbl" file. I can try to have a gapseq run with that option locally; but I cannot promise when this will be done.

**Comment by Zhelunnn** [comment]
Hi Silvio,

I just uploaded a new draft model file and its Reactions.tbl file. This time I split the all-Reactions.tbl file into 4 files. So all the reactions data can be found on my github https://github.com/Zhelunnn/test.git.  I can't appreciate more you would help me with this. I would always use gapseq in my project, so please let me know once you have you final conclusion. 

Best,
Zhelun

**Comment by Waschina** [comment]
Hi Zhelun,
I finally had the time to look at your lists.

I used the following code to identify reaction, which are not expected to be part of the draft network as you descriped:

```R
library(data.table)
library(sybil)
library(stringr)

dmod <- readRDS("48-draft.RDS")

dt1 <- fread("48-p1-Reactions.tbl")
dt2 <- fread("48-p2-Reactions.tbl")
dt3 <- fread("48-p3-Reactions.tbl")
dt4 <- fread("48-p4-Reactions.tbl")

colnames(dt4) <- colnames(dt3) <- colnames(dt2) <- colnames(dt1)

dt <- rbindlist(list(dt1, dt2, dt3, dt4))

# rxn exptected to turn up in draft model
rxns_expected <- dt[status == "good_blast" | !is.na(pathway.status),
                    unlist(str_split(dbhit, " "))]
rxns_expected <- unique(rxns_expected[rxns_expected != ""])


# what reactions are in the draft network?
rxns_draft <- unique(gsub("_.0$","",dmod@react_id))
rxns_draft <- rxns_draft[!grepl("^EX_|^DM_|bio1", rxns_draft)]


# Reactions in draft but not exptected to be part of the draft
rxns_unexpected <- rxns_draft[!(rxns_draft %in% rxns_expected)]

# print reactions
printReaction(dmod, react = rxns_draft[!(rxns_draft %in% rxns_expected)])
```

This results in 188 reactions. However, all of these reactions are transporters, which you probably identified using the `gapseq find-transport` module. 

Thus, the draft model and your lists do perfectly fit together, and the results are as expected using the gapseq workflow. Please note that reactions with the label "no_blast" or "no seq data" can still be part of the draft network if these reactions participate in a pathway that was predicted to be present based on the completeness threshold and/or key-enzyme criteria.

**Comment by Zhelunnn** [comment]
Thank you so much! That was I'm looking for.

**Comment by Zhelunnn** [comment]
Thank you so much! That was what I am looking for.
