### ISSUE TITLE
Biomass reaction produces ATP

### ISSUE THREAD

**Issue by stefaniamagg** [jotech/gapseq#117]
I used gapseq doall on ALLmed.csv to create a metabolic reconstruction of a bacteria, but the resulting biomass reaction produces ATP (cpd00067[c0]), which must be a mistake. The biomass reaction also produces ADP (cpd00008[c0]) and phosphate (cpd00009[c0]).

Full biomass reaction:
bio1	36.5026 cpd00001[c0] + 0.00443444 cpd00056[c0] + 41.3099 cpd00002[c0] + 0.00443444 cpd00003[c0] + 0.00729432 cpd10515[c0] + 0.00729432 cpd10516[c0] + 0.302882 cpd00023[c0] + 0.302882 cpd00053[c0] + 0.00443444 cpd00042[c0] + 0.00443444 cpd00006[c0] + 0.00443444 cpd00010[c0] + 0.0434226 cpd00062[c0] + 0.00443444 cpd00015[c0] + 0.00443444 cpd00016[c0] + 0.131709 cpd00060[c0] + 0.00443444 cpd00017[c0] + 0.25153 cpd00054[c0] + 0.00443444 cpd00028[c0] + 0.0652348 cpd00038[c0] + 0.172125 cpd00041[c0] + 0.475007 cpd00033[c0] + 0.31049 cpd00035[c0] + 0.375631 cpd00039[c0] + 0.172125 cpd00132[c0] + 0.00729432 cpd00048[c0] + 0.00443444 cpd00220[c0] + 0.224428 cpd00051[c0] + 0.0401911 cpd00052[c0] + 0.0632392 cpd00065[c0] + 0.204458 cpd00066[c0] + 0.128856 cpd00069[c0] + 0.21682 cpd00161[c0] + 0.0660921 cpd00084[c0] + 0.00443444 cpd00087[c0] + 0.00443444 cpd00201[c0] + 0.00443444 cpd00345[c0] + 0.403209 cpd00107[c0] + 0.0142772 cpd00115[c0] + 0.00443444 cpd00118[c0] + 0.0950965 cpd00119[c0] + 0.357087 cpd00156[c0] + 0.186865 cpd00129[c0] + 0.02779 cpd00241[c0] + 0.0142772 cpd00357[c0] + 0.313819 cpd00322[c0] + 0.02779 cpd00356[c0] + 0.00443444 cpd00166[c0] + 0.00729432 cpd00149[c0] + 0.00189231 cpd02229[c0] + 0.00729432 cpd00030[c0] + 0.00729432 cpd00034[c0] + 0.00443444 cpd00264[c0] + 0.00443444 cpd11493[c0] + 0.00729432 cpd00063[c0] + 0.00729432 cpd00058[c0] + 0.00729432 cpd00205[c0] + 0.00729432 cpd00099[c0] + 0.00443444 cpd15500[c0] + 0.00443444 cpd15352[c0] + 0.00729432 cpd00254[c0] + 0.00868944 cpd15540[c0] + 0.00189231 cpd15667[c0] + 0.00189231 cpd15669[c0] + 0.00189231 cpd15668[c0] + 0.00868944 cpd15722[c0] + 0.00868944 cpd15723[c0] + 0.00443444 cpd00557[c0] + 0.00868944 cpd15793[c0] + 0.00868944 cpd15794[c0] + 0.00868944 cpd15795[c0] + 0.00868944 cpd15533[c0] + 0.00868944 cpd15696[c0] + 0.00868944 cpd15695[c0] + 0.00189231 cpd11459[c0] + 0.00189231 cpd15665[c0] + 0.00189231 cpd15748[c0] + 0.00189231 cpd15749[c0] + 0.00189231 cpd15750[c0] + 0.00189231 cpd15757[c0] + 0.00189231 cpd15758[c0] + 0.00189231 cpd15759[c0] + 0.00189231 cpd15766[c0] + 0.00189231 cpd15767[c0] + 0.00189231 cpd15768[c0] + 0.00189231 cpd15775[c0] + 0.00189231 cpd15776[c0] + 0.00189231 cpd15777[c0] 	->	0.285898 cpd00012[c0] + 41.2497 cpd00009[c0] + **41.257 cpd00067[c0]** + 41.257 cpd00008[c0] + 0.00443444 cpd03422[c0] + 0.00443444 cpd12370[c0] + 0.00756924 cpd15666[c0] + 0.00443444 cpd01997[c0] + cpd11416[c0]

---------------------
> for bug reports and errors please report the output of: ./gapseq test
gapseq version: 1.1 1999073
linux-gnu
#1 SMP Wed Feb 3 15:06:38 UTC 2021

#######################
#Checking dependencies#
#######################
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.4
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.5.0+
exonerate from exonerate version 2.4.0
bedtools v2.30.0
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
R scripting front-end version 4.1.2 (2021-11-01)
git version 2.34.1
GNU parallel 20211222

Missing dependencies: 0

#####################
#Checking R packages#
#####################
data.table 1.14.2
stringr 1.4.0
sybil 2.2.0
getopt 1.20.3
doParallel 1.0.16
foreach 1.5.1
R.utils 2.11.0
stringi 1.7.6
glpkAPI 1.3.3
BiocManager 1.30.16
Biostrings 2.62.0
jsonlite 1.7.2
CHNOSZ 1.4.1

Missing R packages:  0

##############################
#Checking basic functionality#
##############################
Optimization test: OK
Blast test: OK

Passed tests: 2/2

**Comment by jotech** [comment]
Hi @stefaniamagg 
thank you for using gapseq!

I'm wondering there might be a misunderstanding because actually cpd00067 is not atp but H+.
The metabolite id for atp is cpd00002 instead and it is found at the consumption (left) side of the biomass reaction you provided: (`41.3099 cpd00002[c0]`). So the basic atp hydrolysis reaction (ATP + H20 --> ADP + Pi) should be covered correctly within the biomass reaction!

The gapseq metabolites definition can be found [here](https://github.com/jotech/gapseq/blob/master/dat/seed_metabolites_edited.tsv) or also at the [modelseed webpage](https://modelseed.org/biochem/compounds/cpd00002), although there might be differences because the gapseq database is a derived and updated version of the modelseed database.

**Comment by stefaniamagg** [comment]
Thanks for the reply - you are correct (phew)! Well, I'm happy it was just a line-reading error on my part! :)

**Comment by jotech** [comment]
you are welcome :) I'm glad that it could be solved so quickly!
