### ISSUE TITLE
Complex Blast Results not reported in second pathway query

### ISSUE THREAD

**Issue by Waschina** [jotech/gapseq#12]
BLAST results for reactions with polymer enzyme structures (complexes) are only stated for the pathway with the first occurrence of this reaction but not for subsequent pathways.

An Example:

The two pathways PWY-6122 and PWY-6121 both contain the reaction EC 6.3.5.3. However the blast results table does report the results for this reaction only for the first pathway. To reproduce the issue run for instance the following command:

`./gapseq.sh -b 200 -p "PWY-6122|PWY-6121" -g -i 35 -k Bifidobacterium_longum_longum_JCM_1217.fasta `

The genome can be downloaded [here](https://www.ncbi.nlm.nih.gov/nuccore/NC_015067.1/?report=fasta)

**Comment by jotech** [comment]
i could reproduce but would propose a slightly different fix for it to avoid reporting reactions twice in log file. is it solving your issue?
