### ISSUE TITLE
[bugfix] gapseq_find.sh getting gene names and UniProt IDs

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [jotech/gapseq#121]
Thanks for building gapseq and making it available. MetaCyc has IDs like PWY-0 and **RXN-1** and the latter goes wrong with gapseq_find.sh lines 513 and 514. Tested fix:

    # geneName=$(cat $metaGenes | awk -v rea=$rea -F ',' '$1~rea {print $2}')
    geneName=$(cat $metaGenes | awk -v rea="|$rea|" -F ',' '$1==rea {print $2}')
    # geneRef=$(cat $metaGenes | awk -v rea=$rea -F ',' '$1~rea  {print $5}')
    geneRef=$(cat $metaGenes | awk -v rea="|$rea|" -F ',' '$1==rea  {print $5}')

Also, the code in getDBhit.sh seems incorporated and more evolved into gapseq_find.sh, perhaps move it to the ./src/graveyard/?

    ./gapseq test
    
    gapseq version: 1.2
    linux-gnu
    #2 SMP Fri Apr 8 14:50:24 PDT 2022
    
    
    #######################
    #Checking dependencies#
    #######################
    GNU Awk 5.1.0, API: 3.0
    sed (GNU sed) 4.8
    grep (GNU grep) 3.4
    This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
    tblastn: 2.12.0+
    exonerate from exonerate version 2.4.0
    bedtools v2.30.0
    barrnap 0.9 - rapid ribosomal RNA prediction
    R version 4.1.2 (2021-11-01) -- "Bird Hippie"
    R scripting front-end version 4.1.2 (2021-11-01)
    git version 2.35.1
    GNU parallel 20211222
    
    Missing dependencies: 0
    
    
    #####################
    #Checking R packages#
    #####################
    data.table 1.14.2
    stringr 1.4.0
    sybil 2.2.0
    getopt 1.20.3
    doParallel 1.0.17
    foreach 1.5.2
    R.utils 2.11.0
    stringi 1.7.6
    glpkAPI 1.3.3
    BiocManager 1.30.16
    Biostrings 2.62.0
    jsonlite 1.8.0
    CHNOSZ 1.4.3
    
    Missing R packages:  0
    
    
    ##############################
    #Checking basic functionality#
    ##############################
    Optimization test: OK
    Building full model: OK
    Blast test: OK
    
    Passed tests: 3/3

**Comment by Waschina** [comment]
Thank you so much! Fixed as suggested.
I'll check with @jotech if `getDBhit.sh` is still used somewhere.

**Comment by jotech** [comment]
Hi @MRMHmdeleeuw 
Thanks for your fix!
I slightly modified the code to not depend on the brackets '|' around the reaction id in case a reaction id already has the brackets. I hope everyone is okay with it!

Concerning the file `getDBhit.sh`, it is needed by `gapseq adapt`, and the plan was to use the external file instead of the inline version in `gapseq_find`! I will try to harmonize both.

**Comment by MRMHmdeleeuw** [comment]
Hi @jotech, yes this works and should be safer. Thanks for the info on getDBhit.
