### ISSUE TITLE
[DB error] custom_pwy.tbl missing reaction name for IMPSYN-HIGH-HCO3

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [jotech/gapseq#123]
Hello, entry IMPSYN-HIGH-HCO3 line 22 in `dat/custom_pwy.tbl` has five reactions, but only four reaction names.

     AIR-CARBOXYL-SYN-RXN
     SAICARSYN-RXN
     AICARSYN-RXN
     AICARTRANSFORM-RXN
     IMPCYCLOHYDROLASE-RXN

     1-(5-phosphoribosyl)-5-amino-4-imidazole-carboxylate carboxylase
     5'-phosphoribosyl-4-(N-succinocarboxamide)-5-aminoimidazole lyase
     aminoimidazole carboxamide ribonucleotide formyltransferase
     IMP cyclohydrolase

It looks like AICARSYN-RXN=adenylosuccinate lyase is missing?

**Comment by Waschina** [comment]
Your are right – thank you!
