### ISSUE TITLE
'gapseq medium' function

### ISSUE THREAD

**Issue by zhssakura** [jotech/gapseq#124]
Hey guys,

I've been recently using the 'gapseq medium' function to predict medium for experiments. First, I'd like to thank you for creating this function, and it would be grateful to include the idea/concept behind the algorism on the page of 'Growth medium definition'. 

I was attempting to get more information from the script predict_medium.R and medium_prediction_rules.tsv, in order to get some ideas about why certain compounds would be suggested and others were not into the medium file, or whether the compounds were suggested due to catabolism or anabolism. It would be of great help if some of these details could be included on the website.

Lastly, I found when the two pathways "HOMOSER-THRESYN-PWY" | "THRBIOSYN-GS" are absent from the draft model, L-Threonine will be suggested as a substrate. However, glycine biosynthesis IV (https://metacyc.org/META/NEW-IMAGE?object=GLYSYN-THR-PWY&redirect=T), which can create Threonine, should also be taken into account in relation to L-Threonine.

Please let me know how do you think about these. This function is amazing. Thank you very much!

Best wishes,

Shan

**Comment by zhssakura** [comment]
Hi @jotech 
Thank you for your time on this. The pFBA flux of reaction ("THREONINE-ALDOLASE-RXN") catalysed by L-Threonine aldolase (4.1.2.5/4.1.2.48) in the pathway "GLYSYN-THR-PWY" in my Actinobacteria model, is -0.000027, indicating that L-threonine is synthesised from glycine and aldehydes. 

Please see more details about this reaction in the pFBA simulation of this model:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/zzfanyi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/zzfanyi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



target_rxn_IDs | flux | Rid | met_id | Reactant | Product | met_name | met_Scoef | met_comp | react_id | react_name | react_rev | lowbnd | uppbnd
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
rxn00541_c0 | -2.71E-05 | rxn00541_Shan | cpd00161[c0],cpd00033[c0],cpd00071[c0] | Glycine[c0],Acetaldehyde[c0] | L-Threonine[c0] | L-Threonine[c0],Glycine[c0],Acetaldehyde[c0] | -1,1,1 | 1,1,1 | rxn00541 | L-threonine acetaldehyde-lyase (glycine-forming) | FALSE | 0 | 1000



</body>

</html>



I noticed that the reaction direction of rxn00541_c0 is not reversible (react_rev = FALSE), which conflicts with the flux value I gave above and the description for L-Threonine aldolase (https://metacyc.org/META/NEW-IMAGE?type=REACTION-IN-PATHWAY&object=THREONINE-ALDOLASE-RXN).

Attached are the Actinobacteria model, the medium used for its pFBA simulation, and the results of single species simulation. The reaction rxn00541_c0 was activated during the 9th to 15th iterations of the pFBA simulation. If Actinobacteria MAG lacks the ability to synthesise L-Threonine via the two pathways "HOMOSER-THRESYN-PWY" and "THRBIOSYN-GS", and L-Threonine aldolase is not activated during the first to 8th iterations, where should the L-Threonine come from for the microbial biomass? 

Thank you for helping to investigate this matter.

[Actino_5_Burgsdorf_2021_SZ.zip](https://github.com/jotech/gapseq/files/9061060/Actino_5_Burgsdorf_2021_SZ.zip)

**Comment by jotech** [comment]
Hi Shan,
I had a look at your model, but I don't see any flux for the reaction `rxn00541`:
|id          |name                                             |metacyc                |ec               | bit|origin |pwy                        |educt            |product                             |formula                                                  |formula.full                                                | flux|
|:-----------|:------------------------------------------------|:----------------------|:----------------|---:|:------|:--------------------------|:----------------|:-----------------------------------|:--------------------------------------------------------|:-----------------------------------------------------------|----:|
|rxn00541_c0 |L-threonine acetaldehyde-lyase (glycine-forming) |THREONINE-ALDOLASE-RXN |4.1.2.48/4.1.2.5 | 304|0      |&#124;GLYSYN-THR-PWY&#124; |(1) cpd00161[c0] |(1) cpd00071[c0] + (1) cpd00033[c0] |(1) cpd00161[c0] --> (1) cpd00071[c0] + (1) cpd00033[c0] |(1) L-Threonine-c0 --> (1) Acetaldehyde-c0 + (1) Glycine-c0 |    0|

Could it be a numerical issue with your solver?

In your case, threonine seems to be produced from glycine:

|id          |name                                   |metacyc    |ec       | bit|origin |pwy                            |educt                                                  |product                             |formula                                                                                         |formula.full                                                                               |    flux|
|:-----------|:--------------------------------------|:----------|:--------|---:|:------|:------------------------------|:------------------------------------------------------|:-----------------------------------|:-----------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------|-------:|
|rxn00273_c0 |Acetyl-CoA:glycine C-acetyltransferase |AKBLIG-RXN |2.3.1.29 | 167|0      |&#124;THREONINE-DEG2-PWY&#124; |(1) cpd00022[c0] + (1) cpd00033[c0]                    |(1) cpd00010[c0] + (1) cpd02053[c0] |(1) cpd00022[c0] + (1) cpd00033[c0] <==> (1) cpd00010[c0] + (1) cpd02053[c0]                    |(1) Acetyl-CoA-c0 + (1) Glycine-c0 <==> (1) CoA-c0 + (1) 2-Amino-acetoacetate-c0           |  0.3034|
|rxn11130_c0 |rxn11130                               |NA         |NA       |  NA|1      |NA                             |(1) cpd00067[c0] + (1) cpd00004[c0] + (1) cpd02053[c0] |(1) cpd00003[c0] + (1) cpd00161[c0] |(1) cpd00003[c0] + (1) cpd00161[c0] <==> (1) cpd00067[c0] + (1) cpd00004[c0] + (1) cpd02053[c0] |(1) NAD-c0 + (1) L-Threonine-c0 <==> (1) H+-c0 + (1) NADH-c0 + (1) 2-Amino-acetoacetate-c0 | -0.3034|

It seems to be related to the threonine degradation pathway (https://metacyc.org/META/NEW-IMAGE?object=THREONINE-DEG2-PWY). To me, the reversible reaction `rxn11130` looks suspicious! I will have a closer look!

I also noted that you are using metacyc and kegg pathways. This could also lead to some issues with overlapping pathways.

**Comment by jotech** [comment]
yes rxn11130 was wrongly set to irreversible, should be fixed by now!

**Comment by zhssakura** [comment]
Hi @jotech ,
Because I used a customised database to annotate reaction ids to reactions names but had missed to annotate many reactions from the pFBA analysis, including the rxn11130_c0, that's why I did not figure out where the L-Threonine came from then misinterpreted that the reaction rxn00541_c0 can produce L-Threonine out of glycine. This is not correct as the flux of rxn00541_c0 remains zero in most simulation cycles before the arena is fully occupied and was only -2.71E-05 after the 9th iteration. 
Now I think I understand why even L-Threonine is not provided in the medium but the Actinobacteria can still grow: reactions from pathway |THREONINE-DEG2-PWY| were filled into the gapfilled model, so that cells can synthesise L-Threonine.
Thank you for your great help!
Shan

**Comment by zhssakura** [comment]
Hi @jotech 
Yes, I chose all pathway prediction database for model construction. While you say that using numerous databases will result in overlapping issues, does that imply that it is not advised to select various databases when building a model? What is your recommendation? Thanks :)

**Comment by zhssakura** [comment]
Hi @jotech ,

Yes, the medium prediction results about L-Threonine makes sense to me :)
Also, thank you for the interpretation regarding the database selecting. It greatly simplifies the process of making models 👍 

Shan
