### ISSUE TITLE
Version difference

### ISSUE THREAD

**Issue by Erique29** [jotech/gapseq#126]
Hi again,
I used gapseq 1.2 and 1.1 to gapfill the same genome, but the final growth rates in the log file were different. Why is that?
[version1.1.log](https://github.com/jotech/gapseq/files/8992507/version1.1.log)
[Version1.2.log](https://github.com/jotech/gapseq/files/8992509/Version1.2.log)

**Comment by Erique29** [comment]
Yes, I performed all gapseq steps within both version (the same parameters). Does this mean the predictions become more accurate or scientific?

**Comment by Waschina** [comment]
ideally, yes.

**Comment by Erique29** [comment]
thanks!
