### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by H1889** [jotech/gapseq#127]
Hi. When the gapfilling command ends, the top 10 metabolites produced are shown, for example:
Top 10 produced metabolites:
NH3:0.469, Acetate:0.235, CO2:0.189, Fe2+:0.1, MTTL:0.098, Propionate:0.093, Butyrate:0.092, H+:0.026, EX cpd11416 c0:0.014, 4-Hydroxybenzoate:0

What are the units of those numbers? What variable are measuring? Concenration? Flux?
Thanks

**Comment by Waschina** [comment]
The numbers denote fluxes. The unit is in `mmol / (gDW * hr)`

**Comment by H1889** [comment]
Thanks

**Comment by jotech** [comment]
good point! I added the unit to the printed message
