### ISSUE TITLE
Error in readRDS(rxnXgene.table) : bad 'file' argument Execution halted

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#13]
Dear All, 

In the folder where fna file is located I run
`/home/minerva/gapseq/gapseq_quickstart.sh *.fna /home/minerva/HydMic/Media/R2A.csv` 

But I am facing the follwing issue
```

Creating Gene-Reaction list... 1519 unique genes on 27 genetic element(s)
Constructing draft model: 
 1817 / 1817
Error in readRDS(rxnXgene.table) : bad 'file' argument
Execution halted
```

There is though such a file : `/home/minerva/HydMic/Model_Creation_GapSeq/230419/C1-1_S10/C1-1_S10_07042014-rxnXgenes.RDS`

Based on the fact that this RDS file is an intermediate file, there is something wrong in the `readRDS` pathway. 

Could you replicate this error and if possibly fix it?

Morever, is it possible to continue from the point where pipeline failed, as it takes hours until this point?

Kind Regards,
Georgios

**Comment by Waschina** [comment]
Hi Georgios, 

The error is only during gapfilling,  thus the time consuming step doesn't need to be repeated. I can have a look at your error tomorrow. 

Best, Silvio 


Am 23. April 2019 18:40:54 MESZ schrieb Georgios Marinos <notifications@github.com>:
>Dear All, 
>
>In the folder where fna file is located I run
>`/home/minerva/gapseq/gapseq_quickstart.sh *.fna
>/home/minerva/HydMic/Media/R2A.csv` 
>
>But I am facing the follwing issue
>```
>
>Creating Gene-Reaction list... 1519 unique genes on 27 genetic
>element(s)
>Constructing draft model: 
> 1817 / 1817
>Error in readRDS(rxnXgene.table) : bad 'file' argument
>Execution halted
>```
>
>There is though such a file :
>`/home/minerva/HydMic/Model_Creation_GapSeq/230419/C1-1_S10/C1-1_S10_07042014-rxnXgenes.RDS`
>
>Based on the fact that this RDS file is an intermediate file, there is
>something wrong in the `readRDS` pathway. 
>
>Could you replicate this error and if possibly fix it?
>
>
>Morever, is it possible to continue from the point where pipeline
>failed, as it takes hours until this point?
>
>Kind Regards,
>Georgios

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by maringos** [comment]
After applying the commit 39c3df723e678ab2fbe6d71060d8c35d19d3f24a, the error was corrected!
Thanks GM
