### ISSUE TITLE
Execution halted when writing SBML

### ISSUE THREAD

**Issue by NatashaJorge** [jotech/gapseq#134]
Hello!

I tried running gapseq doall with E. coli genome and I get the following error when writing the xml file.

Wrote file GCA_000005845.2_ASM584v2_genomic.xml
Patching file GCA_000005845.2_ASM584v2_genomic.xml ...Error in (grp_block_start + 1):n_lines : argument of length 0
Calls: write_gapseq_sbml -> grep -> is.factor
Execution halted

Please, do you know how I can fix it?

This is my command line:

$ time gapseq doall GCA_000005845.2_ASM584v2_genomic.fna

> for bug reports and errors please report the output of: ./gapseq test

gapseq version: 1.2 9b30141
linux-gnu
#1 SMP PREEMPT_DYNAMIC Thu Aug 4 02:06:53 UTC 2022 

#######################
#Checking dependencies#
#######################
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.4
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.13.0+
exonerate from exonerate version 2.4.0
bedtools v2.30.0
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.1.3 (2022-03-10) -- "One Push-Up"
R scripting front-end version 4.1.3 (2022-03-10)
git version 2.37.1
GNU parallel 20220722

Missing dependencies: 0

#####################
#Checking R packages#
#####################
data.table 1.14.2 
stringr 1.4.0 
sybil 2.2.0 
getopt 1.20.3 
doParallel 1.0.17 
foreach 1.5.2 
R.utils 2.12.0 
stringi 1.7.8 
glpkAPI 1.3.3 
BiocManager 1.30.18 
Biostrings 2.62.0 
jsonlite 1.8.0 
CHNOSZ 1.4.3 

Missing R packages:  0 

##############################
#Checking basic functionality#
##############################
Optimization test: OK 
Building full model: OK 
Blast test: OK

Passed tests: 3/3

Thanks for your time and attention,
Best wishes,
Natasha

**Comment by Waschina** [comment]
Hello @NatashaJorge ,

could you perhaps share the file `GCA_000005845.2_ASM584v2_genomic.RDS`? Then I can try to reproduce the error to find a possible solution.

**Comment by NatashaJorge** [comment]
Hi Waschina,

sorry for the late reply. I just saw your answer. Sure I can share. Is there an e-mail I can send it?

best,
Natasha

**Comment by NatashaJorge** [comment]
Hi, 

I think I was able to solve it by re-installing gapseq and installing the sybilSBML_3.1.2. Iit was probably the sybilSBML version. 

Thanks for the time and attention!
