### ISSUE TITLE
Some input files already annotated

### ISSUE THREAD

**Issue by Kisekya** [jotech/gapseq#137]
Hello @jotech ,
Thank you for your work! I have a question about the format of the input sequence.
I have some genomes already annotated and some not. For the unannotated ones I think there will be no worries.
But for others, does the previous annotation pose a problem for the gapseq construction for my metabolic networks?

Best regards,
Kisekya

**Comment by Waschina** [comment]
Just a small additional note: gapseq now also accepts multi-protein fasta files as genome input. You can find an example here: https://github.com/jotech/gapseq/issues/132#issuecomment-1263657262

**Comment by Waschina** [comment]
Please re-open if the question/issue still exists.
