### ISSUE TITLE
BRENDA E.C. alias (transferation from 1 EC to 2 or more)

### ISSUE THREAD

**Issue by Waschina** [jotech/gapseq#14]
I came across an issue were an EC number is wrongly assigned to reactions in the seed DB, due to a specific structure in the `brenda_ec.csv` table.

Example: Searching for the EC 4.2.99.20 with the command
`./gapseq.sh -e 4.2.99.20 -b 200 -i 35 bsub.fasta`
results in hits that corresbond also to reactions with EC 2.2.1.9

This is due to the following line in the `brenda_ec.csv`
`2.5.1.64;2-succinyl-6-hydroxy-2,4-cyclohexadiene-1-carboxylate synthase;transferred to EC 2.2.1.9 and EC 4.2.99.20.`
Apparently, the EC number 2.5.1.64 was deleted by the EC-Commission and replaced by the two individual sub-reactions EC 2.2.1.9 and EC 4.2.99.20. _B. subtilis_ for instance has two enzymes, one for EC 2.2.1.9 and one for EC 4.2.99.20. However, both genes are each assigned to both new reactions. This causes False-negative predictions for gene essentiality.

@jotech : My suggestion would be to omit all lines in the `brenda_ec.csv` where there are two ore more EC-numbers in the 3rd column.

Cheers,
Silvio

**Comment by jotech** [comment]
I see, thanks for pointing this out! 
From my side, I would say that the forward direction should still work (i.e. a search for 2.5.1.64 should find 2.2.1.9 and EC 4.2.99.20), but not the other way around. 
What do you think?

**Comment by Waschina** [comment]
Yes, this would be imo the ideal solution to this.

**Comment by jotech** [comment]
the easiest workaround for this would be to edit ``dat/altec.csv`` because this file has priority. Brenda is only used as last resort. 
I also tried to fix it for brenda. Can you give it a try?
