### ISSUE TITLE
access permission of updating log

### ISSUE THREAD

**Issue by ewelinarubin** [jotech/gapseq#140]
I am using gapseq on a university computer cluster. There are errors in the log file but the tool also generates all output files 

jotech -- could you check out my  error.txt file and log.txt file and let me know what I should tell my computer cluster support 

Thanks so much 
[error.txt](https://github.com/jotech/gapseq/files/9628680/error.txt)
[log.txt](https://github.com/jotech/gapseq/files/9628681/log.txt)

**Comment by jotech** [comment]
Hi
There seems to be a problem with the access permissions.
Could you please check whether you can have the rights to access the updating log file?

It should be something like this in your case:
`ls -l /apps/gapseq/1.2/gapseq/dat/seq/Bacteria/updating.log`

Maybe it is a general problem that the logfile is part of the main gapseq folder, which seems to be installed globally in your case with restricted permissions. we should thank about this, thanks for your input!

**Comment by ewelinarubin** [comment]
Thank you for responding 
This is what I get: 
 cannot access '/apps/gapseq/1.2/dat/seq/Bacteria/updating.log': Not a directory

I checked the directories of gapseq installation files and here are my options 
the below directory exists 
/apps/gapseq/1.2/dat/seq/Bacteria/
and withing following folders 
ls 
rev  rxn  unrev  user

Please let me know what else I can check 
Thank you

**Comment by jotech** [comment]
you do not seem to have write access in this folder. i would recommend to install in user space

**Comment by ewelinarubin** [comment]
I am not sure if I am combining the gapseq instructions with slurm job scheduling, correctly. Not sure if you will be able to help me but here it is: 

I installed miniconda and gapseq on my log-in node  (no problems there)
Now when I run a gapseq test all works fine 

**Here is how it goes** 

```
[ewelinarubin@login2 gapseq-data]$ conda activate gapseq-dev
(gapseq-dev) [ewelinarubin@login2 gapseq-data]$ 
(gapseq-dev) [ewelinarubin@login2 gapseq]$ ./gapseq test
```

I get 3/3 passes 


So for the actual genomes for which  I wanted to do the analysis -- I want to send a job request on a computer cluster: for example 

```
#!/bin/bash
#SBATCH --job-name=gapseq
#SBATCH --output=QC_%j.log
#SBATCH --error=QC_%j.err
#SBATCH --mem=16gb
#SBATCH --nodes=1                    
#SBATCH --ntasks=1                  	
#SBATCH --cpus-per-task=4 
#SBATCH --time=12:00:00
#SBATCH --account=juliemeyer
#SBATCH --qos=juliemeyer-b

conda activate gapseq-dev
./gapseq doall McBI.20.fasta

```
-------------------------------
and I get error like this 



CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

/tmp/slurmd/job47957023/slurm_script: line 14: ./gapseq: No such file or directory

**Comment by jotech** [comment]
It seems to be a problem with slurm and conda. at our cluster, I have to load a conda module first. maybe you could reach out to your tech support?

**Comment by ewelinarubin** [comment]
Yes -- thank you. I have reached out to them.
