### ISSUE TITLE
Update documentation re sybilSBML

### ISSUE THREAD

**Issue by jonasoh** [jotech/gapseq#143]
On recent versions of MacOS, the sybilSBML package can't be easily installed due to it linking dynamically to libSBML. An updated version of the package which is statically linked is available at https://www.cs.hhu.de/en/research-groups/computational-cell-biology/software-contributions/sybil. 

Updating the installation instructions to reflect this would greatly aid Mac users (and also simplify the whole SBML section – I assume installation is similarly facilitated on other systems as well when libsbml is no longer a dependency).

**Comment by jonasoh** [comment]
Spoke too soon. It's x86 only so while installation works it doesn't actually load later on on my ARM mac. Sorry for the noise. Will update if I find a solution that works on both architectures.

**Comment by jonasoh** [comment]
Don't think an issue is the best place to put this info, but for reference this is how I got sybilSBML installed and working on an M1 Mac:

First, build and install libSBML with fbc and group extensions:
```
cd libSBML-5.19.0-Source/
mkdir build
cd build
cmake -DENABLE_FBC=ON -DENABLE_GROUPS=ON ..
make
sudo make install
```

Then, download sybilSBML 3.1.3 source tarball from https://www.cs.hhu.de/fileadmin/redaktion/Oeffentliche_Medien/Fakultaeten/Mathematisch-Naturwissenschaftliche_Fakultaet/Informatik/Bioinformatik/sybilSBML_3.1.3.tar.gz

Build and install it:
```
export R_LD_LIBRARY_PATH="`R RHOME`/lib:/usr/local/lib"
R CMD INSTALL sybilSBML_3.1.3.tar.gz
```

The `R_LD_LIBRARY_PATH` environment variable needs to be exported prior to running gapseq.

**Comment by Waschina** [comment]
Thank you so much! We appreciate any help to get sybilSBML running on different platforms.

I'll add a link to this issue in the documentation.

**Comment by jonasoh** [comment]
Perfect, happy to help!

**Comment by MRMHmdeleeuw** [comment]
Hello, wanted to post an update on this. On MacOS Sequoia, libSBML-5.19.0 does not compile anymore, the latest release [libSBML 5.20.4](https://github.com/sbmlteam/libsbml/releases) does. Now for sybilSBML 3.1.3 to correctly compile, I needed to do two things in addition to the instructions above from @jonasho:

1) tell sybilSBML 3.1.3 to also actually activate the GROUPS and FBC plugins and also where to find the libSBML includes. For this one needs the following in ~/.R/Makevars
```
PKG_CFLAGS=-DHAVE_FBC_PLUGIN=1 -DHAVE_GROUPS_PLUGIN=1 
CFLAGS=-I/usr/local/include
```
2) add a missing libSBML include to src/sybilSBML.c (obviously for this one needs to extract the source tar file and run an `R CMD install .` from the extracted source directory)
```
/* FBC PLUGINS*/
#include <sbml/packages/fbc/extension/FbcExtension.h>
```

After this, sybilSBML 3.1.3 compiles still with warnings but the XML output test from `gapseq test-long` works.
