### ISSUE TITLE
Gapfill data access

### ISSUE THREAD

**Issue by kristycyw** [jotech/gapseq#144]
Dear gapseq team, 

I was introduced to Gapseq at the recent JGI annual meeting and have tried it, I would like to know if there is a way to access the gapfill summary generated. For example when running ./gapseq doall, you get an output as such:
1. Initial gapfilling: Make model grow on given media using all reactions
Utilized candidate reactions:  57
Gapfill summary:
Added reactions:       54 
Added core reactions:  11 
Final growth rate:     1.761851 

I am interested in finding out the 54 added reactions and 11 added core reactions as a means of gaining a better understanding of my model. Is there any way to access this information for this step and the followup steps?

Thank you!

**Comment by Waschina** [comment]
Hi @kristycyw ,

yes, this is possible.

The documentation has a tutorial on [Reaction tracing](https://gapseq.readthedocs.io/en/latest/tutorials/traceability.html), which you can follow to find out when and why a reaction was added to the model.

In your case, you can filter for those reaction with the `gs.origin` key of 1 , which will give you all 54 reactions added in Gapfill Step 1. In this list, you can additionally check for those reactions with a bitscore >= 100, which is the default threshold for reactions to be considered "core reaction" in the gapfilling algorithm.

An example to retrieve and filter the tables:

```R
library(data.table)
library(sybil)

mod <- readRDS("model.RDS") # adjust with the respective model name

# retrieve a data table from the model with all relevant info
dt <- data.table(mod@react_attr[,c("seed", "name", "ec", "gs.origin", "pident",
                                   "evalue","bitscore","qcovs","stitle")])

# list added reactions in gapfill step 1
dt[gs.origin == 1]

# list added core reactions in gapfill step 1
dt[gs.origin == 1 & bitscore >= 100]

```

**Comment by Waschina** [comment]
Please re-open if follow-up questions come up.
