### ISSUE TITLE
Reaction rxn00068

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#15]
Hi all,

Thanks for your great job. I have a question concerning the direction of a reaction.

The reaction rxn00068 should be to this direction `<`  according to [ModelSEED](http://modelseed.org/biochem/reactions/rxn00068). Here I can read in [database](https://github.com/jotech/gapseq/blob/master/dat/seed_reactions_corrected.tsv) that the direction is `=`.

Any opinion from you side?

Kind Regards,
Georgios

**Comment by jotech** [comment]
Actually the direction is the same in both!
Column 9 and 10 are for reversibility and direction of a reaction.
