### ISSUE TITLE
Warning: [blastn] Query is Empty!

### ISSUE THREAD

**Issue by ewelinarubin** [jotech/gapseq#152]
I am running the gapseq on a metagenomically assembled genome, and I am getting most of the out files, but I also see some warnings ? 
Should I be concerned about those? 
Please see - the below log and err file. 

[QC_48008849-log.txt](https://github.com/jotech/gapseq/files/9843165/QC_48008849-log.txt)
[QC_48008849-err.txt](https://github.com/jotech/gapseq/files/9843166/QC_48008849-err.txt)

**Comment by Waschina** [comment]
Hi! No, that is nothing to worry about. The warning occurs at the beginning of the draft network reconstruction, where gapseq tries to predict the biomass reactions (Archaea, Gram-pos. Bacteria, or Gram-neg. Bacteria) from the 16S sequence of the input genome file. Sometimes, no 16S rRNA gene sequence can be found in the genome, leading to an empty query in the blastn alignment. Especially MAGs are frequently missing a 16S rRNA gene. In this case, the biomass reactions is predicted based on kmer patterns and previous pathway predictions.

**Comment by Waschina** [comment]
Feel free to re-open the issue if something remains unclear.
