### ISSUE TITLE
help with output interpretation

### ISSUE THREAD

**Issue by mrgambero** [jotech/gapseq#157]
Dear gapseq developers,

Thanks for the cool tool!
After reading the paper where the tool was presented, I decided tp try to  use gapseq to have similar results as presented in figure 5 from a list of MAGs i retrieved from metagenomic data. 
I have a list of MAGs that tend to disappear in certain samples and I would like to know how the general metabolic potential of these MAGs compared to others that increase in those samples.

I would like to have similar graphic representation as figure 5 in the publication, both the ordination and the barplot. Neverthtless i cannot understand how the data was imputed and produced to create these graphs. Would it be possible to have an explanation/guided tutorial on the analyses done in the paper? or is the R code published somewhere?

Thanks in advance and thanks for your awesome job!
Gabri

**Comment by jotech** [comment]
Hi @mrgambero 
thank you for using gapseq!
Figure 5 from our paper can be reproduced using the following code:


```R
library(FactoMineR)
library(factoextra)
library(data.table)

sub.mat <- readRDS("refsoil-20190911-sub.RDS")
agora.mat <- readRDS("agora_20190917-sub.RDS")


energy_sub <- c("Acteyl-Coa-Biosynthesis", "CHEMOAUTOTROPHIC-ENERGY-METABOLISM", "Electron-Transfer", "Entner-Duodoroff-Pathways", "Fermentation", "GLYCOLYSIS-VARIANTS", "Hydrogen-Production", "OTHER-ENERGY", "Pentose-Phosphate-Cycle", "Photosynthesis", "Respiration", "TCA-VARIANTS")
all.mat <- rbind(sub.mat[,match(energy_sub, colnames(sub.mat))], agora.mat[,match(energy_sub, colnames(sub.mat))])             

mat.pca <- all.mat[,apply(all.mat, 2, function(x){(length(unique(x))>1)})] # remove constant rows
pca <- PCA(mat.pca, graph = F)
col.ind <- factor(ifelse(rownames(all.mat) %in% rownames(sub.mat), "refsoil", "agora"))
fviz_pca_biplot(pca, geom.ind="point", col.ind = col.ind, col.var="black", geom.var=c("arrow","text"), repel=T, select.var = list(name = c("Respiration", "Hydrogen-Production", "Photosynthesis", "GLYCOLYSIS-VARIANTS", "Fermentation", "CHEMOAUTOTROPHIC-ENERGY-METABOLISM", "TCA-VARIANTS")), title = "PCA: Energy metabolism")+
  theme_bw(base_size = 14) + theme(strip.background = element_blank(),
                                   axis.ticks = element_blank(),
                                   axis.text.x = element_text(angle = 45, hjust = 1),
                                   panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                                   legend.title = element_blank())
````
It's based on the pathways predicted by `gapseq find` which were summarized into subsystems.

[agora-refsoil_sup.zip](https://github.com/jotech/gapseq/files/10124256/agora-refsoil_sup.zip)
