### ISSUE TITLE
Unziping Error due to Git LFS

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#16]
Hi,

I am facing an error appearing twice
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
This happens in the very beginning and the pipeline **does** **not** stop.
I am suspecting the unzip function for the files that contain sequences (sequences.tar.gz) in the folders $seqpath/rev/ and $seqpath/unrev/

Could you replicate it?

Kind Regards,
Georgios

**Comment by maringos** [comment]
I have found the reason behind the issue. The sequence file is connected to GitHub through Git LFS. Once someone installs Git LFS locally and clone the repository again, the unzip works. But an warning arises : 
```
Encountered 1 file(s) that should have been pointers, but weren't:
	dat/seq/Archaea/unipac90/sequences.tar.gz
```
I think this happens because this file is not connected to Git LFS. Should it be?

**Comment by jotech** [comment]
git lfs is removed and direct download is added
