### ISSUE TITLE
Reactions included in gapseq reconstruction

### ISSUE THREAD

**Issue by nnursimulu** [jotech/gapseq#162]
Dear gapseq developers,

Could you please clarify which reactions are considered in reconstructions?  Are they the ones in seed_reactions_corrected.tsv under gapseq/dat?  If so, are they the ones marked either as "corrected" or "approved"?

Thank you very much for your help!

Best wishes

**Comment by jotech** [comment]
hi @nnursimulu 
The reactions listed in `dat/seed_reactions_corrected.tsv` are considered in reconstructions depending on the status (last column). If the status is `removed` or `not.assessed` then the reactions are dismissed. In contrast, the status `corrected` and `approved` indicates that the reaction will be considered for model building!

There are also some scripts to query the reaction database: https://github.com/Waschina/gapseq.biochem

Let us know if this can work for you!

**Comment by nnursimulu** [comment]
This is great!  Thank you very much!
