### ISSUE TITLE
gapseq adapt not working

### ISSUE THREAD

**Issue by jonasoh** [jotech/gapseq#164]
Hi,
I noticed that `adapt` is no longer working:

```
$ $gapseq adapt -a 14DICHLORBENZDEG-PWY -m toy/myb71.RDS
Loading required package: glpkAPI
using GLPK version 5.0
Warning message:
glpkAPI is used but cplexAPI is recommended because it is much faster 
Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 14 columns, inconsistent with item 1 which has 9 columns. To fill missing columns use fill=TRUE.
Calls: rbind -> rbind -> rbindlist
Execution halted
```

I think this might have been introduced in 82222bdd019f9c90bc8414ffd42628f924a302d4. In the previous commit, b8ec2155f16f02a7bf286f73dc24e005252851db, `adapt` works but gives a warning about malformed `custom_pwy.tbl`.

**Comment by danfrks** [comment]
Hi, I have noticed the same problem!

**Comment by jonasoh** [comment]
Maybe this one
https://github.com/jotech/gapseq/blob/3d319196ba07c6ec4e215c8fa56ce01ea75d979f/src/adapt.R#L100

should be changed to `all.pwy <- rbind(meta.pwy[,1:9],custom.pwy[,1:9])`?

**Comment by danfrks** [comment]
Hi,

I have some issues with adapt too. Maybe I am not understanding the correct usage.

When adapting the toy model for growth with, for example, naphthalene, there are no relevant reactions added in the adapt step (checked with reaction tracing in R).

here is a reproducible example:

`~/gapseq/gapseq adapt -m myb71.RDS -w cpd00618:TRUE -c myb71-rxnWeights.RDS  -g myb71-rxnXgenes.RDS -b myb71Reactions.tbl >> gapseq_output.txt`

> Loading model files myb71.RDS 
> [1] "adapt model to growth table"
>         sub growth
> 1: cpd00618   TRUE
> [1] "EX_cpd00618_e0"
> 
> Try to gapfill Naphthalene cpd00618 
> Utilized candidate reactions:  126
> Gapfill summary:
> Added reactions:       24 
> Added core reactions:  21 
> Final growth rate:     3.809524 
> 
>     nr            rxn lethal     status
>  1:  1           ESP1  FALSE       <NA>
>  2:  2           ESP2  FALSE       <NA>
>  3:  3           ESP3  FALSE       <NA>
>  4:  4           ESP4  FALSE       <NA>
>  5:  5           ESP5  FALSE       <NA>
>  6:  6    rxn00587_c0  FALSE  bad_blast
>  7:  7    rxn00598_c0  FALSE good_blast
>  8:  8    rxn00929_c0  FALSE  bad_blast
>  9:  9    rxn01094_c0  FALSE  bad_blast
> 10: 10    rxn01258_c0  FALSE  bad_blast
> 11: 11    rxn01859_c0  FALSE  bad_blast
> 12: 12    rxn01893_c0  FALSE  bad_blast
> 13: 13    rxn02143_c0  FALSE good_blast
> 14: 14    rxn05064_c0  FALSE  bad_blast
> 15: 15    rxn05226_c0  FALSE  bad_blast
> 16: 16    rxn05287_c0  FALSE  bad_blast
> 17: 17    rxn05573_c0  FALSE  bad_blast
> 18: 18    rxn05909_c0  FALSE  bad_blast
> 19: 19    rxn07775_c0  FALSE  bad_blast
> 20: 20    rxn08669_c0  FALSE  bad_blast
> 21: 21    rxn08806_c0  FALSE  bad_blast
> 22: 22    rxn08848_c0  FALSE  bad_blast
> 23: 23    rxn10209_c0  FALSE  bad_blast
> 24: 24    rxn10254_c0  FALSE  bad_blast
> 25: 25    rxn10263_c0  FALSE  bad_blast
> 26: 26    rxn16111_c0  FALSE  bad_blast
> 27: 27    rxn40053_c0   TRUE       <NA>
> 28: 28    rxn90090_c0   TRUE   no_blast
> 29: 29    rxn90092_c0   TRUE       <NA>
> 30: 30 EX_cpd00355_e0  FALSE       <NA>
> 31: 31 EX_cpd00834_e0  FALSE       <NA>
> 32: 32 EX_cpd02591_e0  FALSE       <NA>
>     nr            rxn lethal     status
> Added reactions: rxn40053_c0 rxn90090_c0 rxn90092_c0 
> abbreviation	equation
> rxn40053_c0	(1) cpd00001[c0] + (4) cpd00109[c0] + (1) cpd00165[c0] --> (1) cpd00075[c0] + (4) cpd00110[c0] + (5) cpd00067[e0]
> rxn90090_c0	(1) cpd00007[c0] + (1) cpd00013[c0] + (1) cpd15561[c0] --> (1) cpd00001[c0] + (1) cpd00067[c0] + (1) cpd15560[c0] + (1) cpd00165[c0]
> rxn90092_c0	(2) cpd00110[c0] + (3) cpd00067[e0] + (1) cpd15560[c0] --> (1) cpd00067[c0] + (2) cpd00109[c0] + (1) cpd15561[c0]
> Patching file ./myb71-adapt.xml ... done


Checking reactions
`library(sybil)
mod <- readRDS("myb71-adapt.RDS")
mod@react_attr
mod@react_attr[,c("seed", "name", "ec", "gs.origin")]

grep("10", mod@react_attr$gs.origin, value = TRUE) `
Output:
`character(0)`
