### ISSUE TITLE
Possibly misclassified sequence for SULFATE-ADENYLYLTRANS-RXN

### ISSUE THREAD

**Issue by jonasoh** [jotech/gapseq#165]
Hi,
I noticed a wrongly classified reaction in one of my models. In `dat/seq/Bacteria/rxn/SULFATE-ADENYLYLTRANS-RXN.fasta`, the following sequence is included (https://www.uniprot.org/uniprotkb/Q92R20/entry):
```
>sp|Q92R20|SYC_RHIME Cysteine--tRNA ligase OS=Rhizobium meliloti (strain 1021) OX=266834 GN=cysS PE=3 SV=1
MGGMPILKLYNTLTREKADFRPIDPQNVRMYVCGPTVYDYAHIGNARPIIVFDVLFRLLR
HVYGADHVTYARNITDVDDKINARALRDYPGLPLNEAIRHVTEKTETQFLEDATVLGCLD
PTVQPRATENIAGMIEIIEKLIAKGHAYEAEGEVLFDTRSMDDYGQLSKRNLDEQQAGAR
VAVEAHKKNPGDFVLWKLSAEHEPGWDSPWGRGRPGWHIECSAMSGRYLGDVFDIHGGGI
DLIFPHHENEIAQSRCAHGTEVMANVWMHNGFLQVEGRKMSKSEGNFITIYELLHTEKFG
GRKWPGEVLRLAMLMTHYREPIDFSIKRLEEAEHLLSKWPVYGDAAGEADPAVVTALADD
LNTVAAIQALHALAQKASADSRHLGTFAASAALLGVVPKEVELDEAVVHEIDGRVRERLE
LLKAKNYAEADGIRADLLARGIQLKDGKDPETGERVTTWEVKRSQV
```

This leads to `rxn00379` being included in my model with a `gs.origin` of 0. I'm guessing the correct sequence here should be corresponding to https://www.uniprot.org/uniprotkb/P56893/entry maybe?

**Comment by Waschina** [comment]
Hi @jonasoh 

Thanks for pointing this out. In MetaCyc both, [Q92R20](https://www.uniprot.org/uniprot/Q92R20) and [P56892](https://www.uniprot.org/uniprot/P56892), are assigned to `SULFATE-ADENYLYLTRANS-RXN`.

https://metacyc.org/gene?orgid=META&id=G-12420
https://metacyc.org/gene?orgid=META&id=G-12421

So the sequence Q92R20 is correct here, but only a hit for Q92R20 should not cause the reaction prediction as 'present' if the second subunit (e.g., P56892) is missing. 

Perhaps we can fix this issue by moving `SULFATE-ADENYLYLTRANS-RXN.fasta` to the user sequence directory and adding "subunit 1" somewhere in the fasta header of Q92R20. @jotech, do you agree?

**Comment by jonasoh** [comment]
Hm, I can't access metacyc, but shouldn't it be P56893 and P56892 as subunits 1 and 2? Uniprot has both these assigned to EC 2.7.7.4.

**Comment by Waschina** [comment]
I see, perhaps this be a wrong assignment in MetaCyc?

**Comment by Waschina** [comment]
Until Metacyc fixes the ID mapping mistake, the commit 2dfa8c801e9faed3e4fb020cab2cfa4df40874e7 should solve the issue in gapseq.

Thank you, @jonasoh

**Comment by jonasoh** [comment]
Excellent, thanks!

**Comment by Waschina** [comment]
MetaCyc will correct the mismatch in the upcoming release
