### ISSUE TITLE
gapseq sequence archives are missing for Archaea 

### ISSUE THREAD

**Issue by XuejianXiong** [jotech/gapseq#166]
Good morning,

I was trying to run gapseq for protein sequences using the following commands:

gapseq find -p all -v 0 -b 200 -t auto aaa.fasta
gapseq find-transport -v 0 -b 200 aaa.fasta
gapseq draft -r aaa-all-Reactions.tbl -t aaa-Transporter.tbl -p aaa-all-Pathways.tbl -c aaa.fasta -u 200 -l 100
gapseq fill -m aaa-draft.RDS -n aaa-medium.csv -c aaa-rxnWeights.RDS -g aaa-rxnXgenes.RDS -b 100

Then I got the following warning messages:

/tmp/tmp.aijTANQXtO
Protein fasta detected.
Predicted taxonomy: Archaea
ATTENTION: gapseq sequence archives are missing! Sequences will be needed to be downloaded from uniprot directly which is rather slow.
..........(many No such file or directory messages)......
md5sum: /home/xuejian/gapseq/src/../dat/seq/Archaea/rev/sequences.tar.gz: No such file or directory
stat: cannot stat '/home/xuejian/gapseq/src/../dat/seq/Archaea/rev/sequences.tar.gz': No such file or directory
..........(the rest messages are about Constructing draft mode and gapfilling)

There are two issues with this model construction:
1) How to get /dat/seq/Archaea/rev/sequences.tar.gz? Does it affect the construction significantly?
2) The biomass function included in the final aaa.xml file is from "Bacterial Gram-positive biomass reaction" but not "Archaeal biomass reaction", even though I specify "-b archaea" or "-b biomass_archaea.json" in the gasseq draft command. 

<reaction metaid="R_bio1" id="R_bio1" name="Bacterial Gram-positive biomass reaction" reversible="false" fast="false" fbc:lowerFluxBound="default_0" fbc:upperFluxBound="default_ub">

Please help me to solve these issues. Thanks!

Best,
Xuejian

**Comment by Waschina** [comment]
Hi Xuejian,

to update the Archaea reference protein sequences please cd into your gapseq installation directory and run

```sh
bash src/update_sequences.sh Archaea
```

Concerning your second point: Could you provide your logs of the draft reconstruction step?

Best
Silvio

**Comment by XuejianXiong** [comment]
Hi Silvio,

With the updated Archaea database, I ran gapseq without any error messages. However, the biomass function in the xml file is still "Bacterial Gram-positive biomass reaction". I attached the log file here. 
[gapseq_log.txt](https://github.com/jotech/gapseq/files/10873279/gapseq_log.txt)

Thank you!

Best,
Xuejian

**Comment by Waschina** [comment]
Mhh, I cannot find anything in the logs that indicates a potential issue. I also tested the draft reconstruction with an archaea genome with and without automatic biomass reaction prediction, which worked as expected: Adding the "Archaeal biomass reaction."

Could you share the exact commands you used for `gaspeq draft ...`?

**Comment by Waschina** [comment]
Please re-open if the issue persists.
