### ISSUE TITLE
Training a bacterial model to eat up VB12 (calomide/cobalamin)

### ISSUE THREAD

**Issue by zhssakura** [jotech/gapseq#169]
Hello,
I have a question regarding the synthesis/utilization of vitamin B12 based on recent discoveries from my bacterial/archaeal model.
I noticed that calomide is one compound of the gram-pos, -neg, and archaea biomass, as well as the dat/nutrients.tsv file, containing different vitamin B12 synonyms, such as Calomide, Cob(II)alamin, Cob(I)alamin. 
I have a complete genome of alphaproteobacteria (bin.1.fa), which I used to create a model by using all the 753 nutrients from the nutrients.tsv file. In the gap-filled model (bin.1.RDS), I could not find the reaction for transportation of vitamin B12. Instead, reactions that were associated with biosynthesis of calomide were found as gap-filled ones, such as rxn03538.
This causes a bit of concern, since it might prevent the observation of vitamin B12 exchange between microbes. What would you recommend regarding this? Thank you very much!
PS. Here is the link including the input and output files of bin.1.fa
https://github.com/zhssakura/Gh_Sflabelliformis_8_MAGs/tree/main/09_Collaboration/MAG_from_Willis/Cymbastela_concentrica

**Comment by zhssakura** [comment]
Upon the above question, there is another issue, which is what the ModelSEED compound ID to be used in the medium? This is important since if the compound ID is not the end-product of VB biosynthesis pathway and the biomass compound at the same time, it is hard to see that one bacterium produces VB12 for its own biomass and secretes additional VB12 to support other bacteria who are auxotrophic of it.

**Comment by jotech** [comment]
Hi @zhssakura 
I'm sorry for not getting back to you sooner!
As far as I can see, no B12 biosynthesis pathway is found for your organism (PWY-7376, PWY-7377). Maybe the genes are unknown, or the metagenomic data is insufficient. B12 synthesis is a rather complex pathway with many reactions. Therefore it could be hard to predict from metagenomic data. What do you think?

Besides adding the missing reactions via gap filling, you could also use gapseq adapt to do the job
```
./gapseq adapt -a PWY-7376,PWY-7377 -m toy/myb71.RDS
```
I hope it helped a bit.
