### ISSUE TITLE
Error in checkForRemoteErrors(val)

### ISSUE THREAD

**Issue by BinhongLiu** [jotech/gapseq#173]
**the output of: ./gapseq test**

(gapseq) liuhongbin@node7:~/soft/gapseq$ ./gapseq test

gapseq version: 1.2 2dfa8c80
linux-gnu
#1 SMP Fri Dec 18 16:34:56 UTC 2020 

#######################
#Checking dependencies#
#######################
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.4
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.13.0+
exonerate from exonerate version 2.4.0
bedtools v2.30.0
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
git version 2.38.1
GNU parallel 20230122
HMMER 3.3.2 (Nov 2020); http://hmmer.org/

Missing dependencies: 0

#####################
#Checking R packages#
#####################
data.table 1.14.8 
stringr 1.4.0 
sybil 2.2.0 
getopt 1.20.3 
doParallel 1.0.17 
foreach 1.5.2 
R.utils 2.12.2 
stringi 1.7.8 
glpkAPI 1.3.4 
BiocManager 1.30.18 
Biostrings 2.66.0 
jsonlite 1.8.4 
CHNOSZ 1.4.3 
httr 1.4.5 

Missing R packages:  0 

##############################
#Checking basic functionality#
##############################
Warning message:
程辑包‘Matrix’是用R版本4.2.2 来建造的 
Warning message:
程辑包‘glpkAPI’是用R版本4.2.2 来建造的 
Optimization test: OK 
Warning messages:
1: 程辑包‘data.table’是用R版本4.2.2 来建造的 
2: 程辑包‘Matrix’是用R版本4.2.2 来建造的 
Building full model: OK 
Blast test: OK

Passed tests: 3/3

**error of the test script**
./gapseq doall toy/myb71.fna.gz

Error in checkForRemoteErrors(val) : 
  one node produced an error: URL using bad/illegal format or missing URL
Calls: parLapply ... clusterApply -> staticClusterApply -> checkForRemoteErrors

the log file:
[log.txt](https://github.com/jotech/gapseq/files/10986357/log.txt)

**Comment by gmhhope** [comment]
Similar error also in my run

```
2023-04-03 21:39:44 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [193] -> ".listing" [1]
2023-04-03 21:39:49 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [18391310] -> "sequences.tar.gz" [1]
2023-04-03 21:39:50 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [194] -> ".listing" [1]
2023-04-03 21:40:23 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [345319929] -> "sequences.tar.gz" [1]
2023-04-03 21:40:24 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz [193] -> ".listing" [1]
Warning: [blastp] Query_1 UniRef50_O30642 M.. : One or more O characters replaced by X for alignment score calculations at positions 201 
Warning: [blastp] Query_1 UniRef90_Q18TV3 T.. : One or more O characters replaced by X for alignment score calculations at positions 330 
Error in checkForRemoteErrors(val) : 
  one node produced an error: URL using bad/illegal format or missing URL
Calls: parLapply ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
md5sum: def5a3cbe47f19f7ab34d01ba7a0b1f7.fasta: No such file or directory
cat: def5a3cbe47f19f7ab34d01ba7a0b1f7.fasta: No such file or directory
Wrote file ./S_lugdunensis-c9_0034-F01-draft.xml
Loading required package: glpkAPI
using GLPK version 5.0
Warning message:
glpkAPI is used but cplexAPI is recommended because it is much faster 
Warning in media_check(media.file, mod.orig, seed_x_mets) :
  For pectin the identifier cpd27519 is recommended.
Warning in media_check(media.file, mod.orig, seed_x_mets) :
  For starch the identifier cpd90003 is recommended.
Warning in media_check(media.file, mod.orig, seed_x_mets) :
  For cellulose the identifier cpd90020 is recommended.
Wrote file ./S_lugdunensis-c9_0034-F01.xml
```

**Comment by AshSudarshan** [comment]
Facing the same issue. But I get an output with gapes find.

Any explanation as to why this occurs?

Thanks!

**Comment by Waschina** [comment]
Thanks for reporting!

It looks like, that some special character/or symbol encoding causes this error in one specific uniqrot query. However, it is very unlikely that this error affects the model outcomes or predictions.

I will look into this in more detail, to see qhich query is affected.

**Comment by Waschina** [comment]
The error was most likely due to the quote character (") in some reaction names, for instance in anthocyanidin-3-O-glucoside-6"-O-malonyltransferase

The issue should be solved now. Please re-open if the same error occurs (perhaps other special characters cause a similar problem).
