### ISSUE TITLE
A way to add reactions with 'good_blast' that are not in gapseq database?

### ISSUE THREAD

**Issue by utkinaira** [jotech/gapseq#174]
Dear gapseq team,

I have been exploring starch/oligosaccharides degradation reactions present in my models and have noticed that certain reactions are labeled as 'good_blast' in the *Reactions.tbl file and have a corresponding pathway predicted to be present in the *Pathways.tbl file, but are marked as 'not.assessed', i.e., they are not in the gapseq database, and thus cannot be added to the model using gapseq adapt. I was wondering if it would be possible to add these reactions manually to the .xml file, or if there is another recommended approach.

Examples of such reactions I found in my models:
- sucrose:fructan 6-fructosyltransferase (2.4.1.0)  - rxn15452 rxn20032 rxn23736 rxn23739  
- isoamylase (3.2.1.68) - rxn17983 rxn22743 rxn23920 rxn28284 rxn30585 
- maltooligosyl-trehalose trehalohydrolase (3.2.1.141) - rxn17922 rxn27554

Additionally, I am curious about the rule for adding reactions with multiple aliases. If there is a good blast hit for an enzyme and a corresponding pathway is also present, and there are multiple reaction IDs (let's say, N) that correspond to this enzyme, are all N reactions added or is there a specific rule for selecting which reactions to proceed with?

I also encountered an issue where certain degradation reactions are present in the model, but no transporter for the substrate is present, rendering the degradation reaction blocked. For example, all my models have a stachyose degradation reaction present (rxn02596). The transport reaction for stachyose (rxn18552) is present in all the *Transport.tbl files with the bitscore higher than the threshold 200, but since it’s labeled as ‘not.assessed’, it isn’t included in the gapseq database (thus cannot be added to the model). 
To work around this, I found an alternative transport reaction (rxn05693) that is included in the gapseq database and added it using gapseq adapt. Could there be any solution for that, for example, at the 'find transporter' step - if there is a transporter reaction with bitscore>threshold but not in gapseq db, add an alternative reaction from gapseq db instead?

Thank you very much for any help!

Best,
Irina

**Comment by Waschina** [comment]
Dear Irena,

thank you for the feedback and the detailed analysis. The short answer to the question in the issue title is: Unfortunately, there's not a quick way to do that.

The examples you mentioned are related to glycan degradation. These are always tricky to handle in genome-scale metabolic networks, as the diversity of different possible glycan structures is massive, making it impossible to include all possibilites in the metabolic network model. One solution is to add generic metabolites (such as "A starch molecule with n-subunits"); however that has a number of disadvantages for the application of the model for flux predictions. In gapseq we follow a different approach: We aim to add 'prototypes' of complex polymer structures. For instance for starch we have a prototype with 27 subunits, three alpha-1->6 linkages and  23 alpha-1->4 linkages. Obviously, this disregards the complexity of glycans but ensures that reactions in the model are mass-balanced.

I have updated the gapseq database with regard to your examples:

- sucrose:fructan 6-fructosyltransferase (EC 2.4.1.10) is now part of gapseq's biochemistry with ID `rxn90120`.
- related to (EC 2.4.1.10) I have also added two reactions associated to EC [3.2.1.154 ](https://metacyc.org/META/NEW-IMAGE?type=REACTION&object=3.2.1.154-RXN)
  1. `rxn90121`: 6-kestotriose + H<sub>2</sub>O -> sucrose + fructose
  2. `rxn90122`: 6,6-kestotetraose + H<sub>2</sub>O -> 6-kestotriose + fructose
- isoamylase (3.2.1.68) is now added as `rxn90123`. This 'prototype' instance of an isoamylase reaction is the hydrolysis of a glycogen with 5 glucose subunits and 1 alpha-1-6 linkage. It releases a maltose (2x glucose) and Maltotriose (3x glucose, a.k.a. amylotriose)
- maltooligosyl-trehalose trehalohydrolase (3.2.1.141): This reaction was already before part of the gapseq database (`rxn10817`), but was not attributed with the EC number. I have corrected that.

Concering your question about multiple reaction IDs per reaction in the file `-reactions.tbl`: If the reaction was found, all associated reaction IDs are added to the model as long as they are also part of gapseq's curated reaction database (tags: corrected, approved).

The reaction for the ATP-dependent import of stachyose (`rxn18552`) is now approved and part the gapseq database.

Hope this helps.
