### ISSUE TITLE
gapseq for protein sequence and gapfilling

### ISSUE THREAD

**Issue by mhjonathan** [jotech/gapseq#175]
Hi,

I'm trying to use gapseq against multiple protein sequences referring to [this](https://github.com/jotech/gapseq/issues/132#issuecomment-1263657262), and I got an warning message that "FASTA-Reader:Ignoring invalid residues at position(s)". It seems gapseq keep reagarding my input sequence as DNA sequence? The command I used is "gapseq fill -t Bacteria -m Bacteria -i 50 -c 80 -p all -b 200 input.faa".

In case of gapfilling, I want to be sure whether I understand right way. So, it suppose the applied bacteria can survive under the predefined medium or optimum medium, and it fill the gap of input sequence like, "Oh, it can survive under this environment, but doesn't have this gene and this gene comprising essential pathway to survive. Let's fill this gap!". Am I right?

Thank you in advance!

**Comment by Waschina** [comment]
Hi!

You mentioned using the command "gapseq fill -t Bacteria -m Bacteria -i 50 -c 80 -p all -b 200 input.faa".

This might be a typo, but please note, that the correct command is:
```
"gapseq find -t Bacteria -m Bacteria -i 50 -c 80 -p all -b 200 input.faa"
```

Concerning your question on the gap-filling algorithm: Yes, the gap-filling medium is assumed to support the growth of the organism. The gapseq algorithm uses an optimization algorithm to identify which reactions should be added.
