### ISSUE TITLE
gapseq find gets stuck 

### ISSUE THREAD

**Issue by gzampieri** [jotech/gapseq#177]
Hi,

I am having trouble with the first step.
Every time I run it, the execution gets up to this point:
```
1746/2924: Checking for pathway map00196 Photosynthesis - antenna proteins with 1 reactions
(kegg;Metabolism;Energy metabolism)
```
After that point, the process keeps running for several hours without any update in the log. The command is the following:
```
gapseq find -p all -l all -m Bacteria -t Bacteria -b 200 -K 10 -T tmp/ proteome.faa
```

I tried with two different input protein fasta and found the same issue with both. The version of gapseq is the latest.

I am not sure this is related, but my impression is that the issue arose after gapseq automatically updated `gapseq/src/../dat/seq/Bacteria`.

This is the output of `gapseq test`: [gapseq_test.txt](https://github.com/jotech/gapseq/files/11220497/gapseq_test.txt)

Thanks in advance,
Guido

**Comment by Waschina** [comment]
Thanks for reporting, Guido!  I can reproduce this issue with the command 

```sh
gapseq find -p map00196 -l all -m Bacteria -t Bacteria -b 200 -K 10 proteome.faa.gz
```

I will try to fix this issue in the next days. In the meanwhile, the command should work without issues if you skip the option `-l all`, but this will only search for MetaCyc-Pathways.

Best
Silvio

**Comment by gzampieri** [comment]
Thanks Silvio!

I have noticed that the row for map00196 in `dat/kegg_pwy.tbl` has empty reaId and reaEc fields. I therefore tried removing that row from the file and re-running the command. Now gapseq stalls at
```
155/522: Checking for pathway map01010 Overview of biosynthetic pathways with 1 reactions
(kegg;Metabolism;Chemical structure transformation maps)
```
which is the next pathway having no reaId and reaEc in the table. So it seems that pathways with missing reaction data could be part of the issue.

I hope this helps!

**Comment by jotech** [comment]
Hi Guido,
Thank you for reporting this! I drafted a short fix for the issue. Pathways that do not contain reactions are excluded from now on. Only kegg pathways seem to be affected.
As a short notice, the kegg pathway prediction needs to be better curated in gapseq, and I would not recommend it for model creation.

**Comment by gzampieri** [comment]
Hi Johannes,

Brilliant, thanks a lot for the fix and the tip.

Best,
Guido
