### ISSUE TITLE
Is it possible to see the similarity of the generated GSMM?

### ISSUE THREAD

**Issue by B-1991-ing** [jotech/gapseq#179]
Hi Silvio,

Although I still don't have the xml format file yet, I am wondering that is it possible to see the similarity (metabolic distance) of the generated GSMM using Jaccard distances by **gapseq generated output files**? 

The original method may be from the paper - A systematic assessment of current genome-scale metabolic reconstruction tools.
But the author never shown up on the GitHub.

I also saw the calculation of distance of GSMM in another paper.
<img width="904" alt="Screenshot 2023-04-26 at 22 21 47" src="https://user-images.githubusercontent.com/54441633/234693320-b849ac0d-0fc0-4c2c-9d88-7c77d30fc7eb.png">

Best,

Bing

**Comment by Waschina** [comment]
A comparison of different models is not possible with gapseq.
