### ISSUE TITLE
Duplicated reactions / metabolites in the reaction database

### ISSUE THREAD

**Issue by sulheim** [jotech/gapseq#181]
Hi, and thanks for developing and maintaining this valuable software. A few observations from my first use of this tool, that I'd like to hear your opinion on:

From running memote on my reconstucted draft models I find that there are duplicated metabolites:
 [["cpd00179_c0","cpd00665_c0"],["cpd02651_c0","cpd02431_c0"],["cpd01749_c0","cpd11254_c0"],["cpd00084_c0","cpd00547_c0"],["cpd00108_c0","cpd00724_c0"],["cpd00208_c0","cpd01354_c0"],["cpd00334_c0","cpd03571_c0"],["cpd00232_c0","cpd21149_c0"],["cpd02788_c0","cpd24650_c0"],["cpd03389_c0","cpd01608_c0"],["cpd03046_c0","cpd14699_c0"],["cpd02943_c0","cpd02862_c0"],["cpd00208_e0","cpd01354_e0"],["cpd00541_c0","cpd14958_c0"],["cpd15619_c0","cpd01088_c0"],["cpd00399_c0","cpd16638_c0"],["cpd16503_c0","cpd27796_c0"],["cpd07274_c0","cpd27797_c0"],["cpd16494_c0","cpd27182_c0"],["cpd19587_c0","cpd02746_c0"]]

This is e.g. generic and specific form of glucose (alpha-D-glucose, vs Glucose). I believe that this might cause problems in the reconstructed models, and that it would be best to curate this in the reaction DB. However, it is not clear if one should always go with the generic form? The alternative is of course to have a reaction that converts between the different forms to avoid that the different variants (which are actually the same molecule) leads to blocked reactions. 

There are also a bunch of duplicate reactions:
[["rxn00126_c0","rxn28979_c0"],["rxn00182_c0","rxn19827_c0"],["rxn00256_c0","rxn19316_c0"],["rxn00468_c0","rxn15055_c0"],["rxn00502_c0","rxn37807_c0"],["rxn00649_c0","rxn19041_c0"],["rxn00808_c0","rxn15121_c0"],["rxn00816_c0","rxn35560_c0"],["rxn00818_c0","rxn15141_c0"],["rxn00819_c0","rxn15143_c0"],["rxn00890_c0","rxn15153_c0"],["rxn00915_c0","rxn32380_c0"],["rxn01134_c0","rxn15225_c0"],["rxn01213_c0","rxn19872_c0"],["rxn01300_c0","rxn38151_c0"],["rxn01316_c0","rxn15255_c0"],["rxn01544_c0","rxn33365_c0"],["rxn01617_c0","rxn01879_c0"],["rxn01835_c0","rxn15341_c0"],["rxn02093_c0","rxn15380_c0"],["rxn02596_c0","rxn15418_c0"],["rxn02867_c0","rxn06586_c0"],["rxn02988_c0","rxn20661_c0"],["rxn03838_c0","rxn15541_c0"],["rxn05210_c0","rxn05313_c0"],["rxn05312_c0","rxn09120_c0"],["rxn05513_c0","rxn27352_c0"],["rxn05573_c0","rxn08616_c0"],["rxn05582_c0","rxn08660_c0"],["rxn05598_c0","rxn90005_c0"],["rxn05651_c0","rxn13116_c0"],["rxn07584_c0","rxn15699_c0"],["rxn08173_c0","rxn27727_c0"],["rxn08188_c0","rxn10448_c0"],["rxn08323_c0","rxn09688_c0"],["rxn09975_c0","rxn19124_c0"],["rxn11551_c0","rxn15123_c0"],["rxn11552_c0","rxn15127_c0"],["rxn15136_c0","rxn15588_c0"],["rxn29921_c0","rxn32301_c0"],["EX_cpd00208_e0","EX_cpd01354_e0"],["rxn13243_c0","rxn13244_c0"],["rxn13243_c0","rxn31203_c0"],["rxn13243_c0","rxn32206_c0"],["rxn13244_c0","rxn31203_c0"],["rxn13244_c0","rxn32206_c0"],["rxn31203_c0","rxn32206_c0"],["rxn13361_c0","rxn24116_c0"]]

And finally, 
one metabolite without formula: "cpd11416_c0"

**Comment by Waschina** [comment]
Hi @sulheim 

Thank you for pointing out the issue of duplicate reactions and metabolites. As the gapseq database is derived from the ModelSEED biochemistry database, we also have some of the duplicates that were already part of ModelSEED. When we have noticed specific cases of duplicates, we also try to resolve them on a case-by-case basis. When resolving duplicates, we have to be careful not to lose specific links such as EC numbers or cross-references to other databases.

The metabolite ID "cpd11416" is the compound ID for the biomass, so adding a formula to it is tricky.
