### ISSUE TITLE
How to produce the Fig.3 and Fig.4 in the gapseq paper

### ISSUE THREAD

**Issue by LiZhihua1982** [jotech/gapseq#184]
> for bug reports and errors please report the output of: ./gapseq test

**Comment by Waschina** [comment]
https://github.com/Waschina/gapseqEval

**Comment by LiZhihua1982** [comment]
Dear Prof. Silvio Waschina,
     Thank you very much for your help! I found the Fig.4 in the manuscript  "The heatmaps display the predicted metabolite production (red) and consumption (blue) during exponential growth before the inflection point",which the predicted metabolite production (red) and consumption (blue) are combination on one Figure, while in the https://github.com/Waschina/gapseqEval is separate the script is as below:
So how to combine them into one Figure like Figure.4? Thank you very much!
p <- ggplot(a[stat == "production" & grepl(sub.incl, sub)], aes(sub, reorder(spec.name, dplyr::desc(spec.name)))) +
  #geom_tile(data = tmp[!grepl(sub.excl, V1)], aes(V1, V2, fill = N)) +
  geom_tile(aes(fill=mflux2)) + scale_fill_gradient(low = "white", high = "red", name = "Production\n [unit]", trans = "log",
                                                                                  breaks = my_breaks, labels = my_breaks) +
  theme_bw() +
  facet_grid(time~recon) + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                 panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p
ggsave(filename = "plots/comm_fullheat_gg_red.pdf", plot = p, width = 10, height = 20)

p <- ggplot(a[stat == "uptake" & grepl(sub.incl, sub)], aes(sub, reorder(spec.name, dplyr::desc(spec.name)))) +
  #geom_tile(data = tmp[!grepl(sub.excl, V1)], aes(V1, V2, fill = N)) +
  geom_tile(aes(fill=mflux2)) + scale_fill_gradient(low = "white", high = "blue", name = "Production\n [unit]", trans = "log",
                                                                                  breaks = my_breaks, labels = my_breaks) +
  theme_bw() +
  facet_grid(time~recon) + theme(axis.text.x = element_text(angle = 45, hjust = 1),
                                 panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_x_discrete(drop = FALSE)
p
ggsave(filename = "plots/comm_fullheat_gg_blue.pdf", plot = p, width = 10, height = 20)

[cid:a18a4d73-b14a-4557-b2e0-c5c174b128fe]
[https://opengraph.githubassets.com/abf282e93d3025f586bb79072cac7a2fe70be59f1158d9b20b4bd90cdf1b8891/Waschina/gapseqEval]<https://github.com/Waschina/gapseqEval>
GitHub - Waschina/gapseqEval: Data and scripts for evaluations tests<https://github.com/Waschina/gapseqEval>
Data and scripts for evaluations tests. Contribute to Waschina/gapseqEval development by creating an account on GitHub.
github.com


________________________________
发件人: Silvio Waschina ***@***.***>
发送时间: 2023年7月3日 21:44
收件人: jotech/gapseq ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [jotech/gapseq] How to produce the Fig.3 and Fig.4 in the gapseq paper (Issue #184)


https://github.com/Waschina/gapseqEval

―

**Comment by Waschina** [comment]
To combine both, we used the Software Inkscape for Vector Graphics.

**Comment by LiZhihua1982** [comment]
Dear Prof.Silvio Waschina,
    Thank you very much for your quick reply! Another question, if I have assembled 100 MAGs from an environment community, (1) is ./gapseq for each individual MAGs; (2), combine the MAGs and then ./gapseq. I do not which is better? If (1) is better, I want to know how to combine the *.RDS files, Thank you very much!

Best regards

Li Zhihua
________________________________
发件人: Silvio Waschina ***@***.***>
发送时间: 2023年8月20日 22:02
收件人: jotech/gapseq ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [jotech/gapseq] How to produce the Fig.3 and Fig.4 in the gapseq paper (Issue #184)


To combine both, we used the Software Inkscape for Vector Graphics.

―

**Comment by LiZhihua1982** [comment]
Dear Dr.Silvio Waschina,
     I have installed Inkscape, would you tell me more detail Vector Graphics? For example, step-by-step. Thank you again!

Best regards

Li Zhihua

________________________________
发件人: Silvio Waschina ***@***.***>
发送时间: 2023年8月20日 22:02
收件人: jotech/gapseq ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [jotech/gapseq] How to produce the Fig.3 and Fig.4 in the gapseq paper (Issue #184)


To combine both, we used the Software Inkscape for Vector Graphics.

―

**Comment by LiZhihua1982** [comment]
Dear Dr.Silvio Waschina,
    I understand how to combine both. Thanks.

Best regards

Li  Zhihua

________________________________
发件人: Silvio Waschina ***@***.***>
发送时间: 2023年8月20日 22:02
收件人: jotech/gapseq ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [jotech/gapseq] How to produce the Fig.3 and Fig.4 in the gapseq paper (Issue #184)


To combine both, we used the Software Inkscape for Vector Graphics.

―

**Comment by LiZhihua1982** [comment]
Dear Prof. Silvio Waschina,
     I  want to ask a question that if I have done with doall for gap filling, then I want to do in the anaerobic medium(condition),Could I use the result" ./gapseq doall toy/myb71.fna dat/media/anerobic.csv" and use the "gapseq medium -m xxx.RDS -p xxx .tbl -c "cpd00007:0;cpd00159:10""(https://gapseq.readthedocs.io/en/latest/usage/medium.html)? Thanks again!

Best regards

Li Zhihua
________________________________
发件人: Silvio Waschina ***@***.***>
发送时间: 2023年8月20日 22:02
收件人: jotech/gapseq ***@***.***>
抄送: Li Zhihua ***@***.***>; Author ***@***.***>
主题: Re: [jotech/gapseq] How to produce the Fig.3 and Fig.4 in the gapseq paper (Issue #184)


To combine both, we used the Software Inkscape for Vector Graphics.

―
