### ISSUE TITLE
gapseq advice for colonisation

### ISSUE THREAD

**Issue by schmittel** [jotech/gapseq#185]
Hi there,

I'm on a bit of a steep learning curve when it comes to bacterial metabolism and I'm wondering if you can help me. If I have a gut-isolated bacterium that is unable to mono-colonise a mouse, could I use gapseq to predict one or more appropriate bacteria for co-colonisation/cross-feeding to support the metabolic requirements of my bacterium of interest? If you have any advice or could point me in the right direction, that would be much appreciated.

Many thanks!

**Comment by jotech** [comment]
Hi @schmittel 
I think the easiest approach would be to predict a growth medium for your organism by `gapseq medium` and have a look at the nutritional requirements. From this, you can probably get an idea of potential cross-feeding partners. What do you think?
