### ISSUE TITLE
missing biomass components for archaea

### ISSUE THREAD

**Issue by jotech** [jotech/gapseq#19]
The [biomass reaction](http://bigg.ucsd.edu/universal/reactions/BIOMASS_Mb_30) for archaea is taken from the [Methanosarcina barkeri iAF692model](http://bigg.ucsd.edu/models/iAF692).  

Right now not all of the components can be produced even when all reactions from the seed database are used.

List of missing biomass compounds:

1. **cpd15817** &nbsp;&nbsp; 3hdpgpe  &nbsp;&nbsp; _2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycero-l-phosphoethanolamine_
2. **cpd15818**  &nbsp;&nbsp; 3hdpgpg  &nbsp;&nbsp; _2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycerol-1-phospho-3'-sn-glycerol_
3. **cpd15819**  &nbsp;&nbsp; 3hdpgpi  &nbsp;&nbsp; _2-O-(3'-hydroxyl)phytanyl-3-O-phytanyl-sn-glycero-1-phospho-myo-inositol_
4. **cpd15820**  &nbsp;&nbsp; 3hdpgps &nbsp;&nbsp;  _2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycero-l-phosphoserine_
5. **cpd15834**  &nbsp;&nbsp; adocblhbi  &nbsp;&nbsp; _Adenosylcobalamin-HBI_
6. **cpd02817**   &nbsp;&nbsp; cob  &nbsp;&nbsp; _coenzyme b_
7. **cpd15858**  &nbsp;&nbsp; dpgpe &nbsp;&nbsp;  _2,3-O-phytanyl-sn-glycero-1-phosphoethanolamine_
8. **cpd15859**  &nbsp;&nbsp; dpgpg  &nbsp;&nbsp; _2,3-di-O-phytanyl-sn-glycerol-1-phospho-3'-sn-glycerol_
9. **cpd15860**   &nbsp;&nbsp; dpgpi  &nbsp;&nbsp; _2,3-O-phytanyl-sn-glycero-1-phospho-myo-inositol_
10. **cpd15861**  &nbsp;&nbsp; dpgps  &nbsp;&nbsp; _2,3-O-phytanyl-sn-glycero-1-phosphoserine_
11. **cpd15862**  &nbsp;&nbsp; f390a  &nbsp;&nbsp; _coenzyme F390 (adenosine)_
12. **cpd15863**  &nbsp;&nbsp; f390g  &nbsp;&nbsp; _coenzyme F390 (guanosine)_
13. **cpd03425**  &nbsp;&nbsp; f430  &nbsp;&nbsp; _coenzyme F430_
14. **cpd15880**  &nbsp;&nbsp; gdpgpi &nbsp;&nbsp;  _glucosaminyl archaetidyl-myo-inositol_
15. **cpd15884**  &nbsp;&nbsp; h4spt  &nbsp;&nbsp; _tetrahydrosarcinapterin_

All other biomass compounds (incl. coenzym m: cpd02246) can already be produced.

**Comment by Waschina** [comment]
**cpd15834** (Adenosylcobalamin-HBI) should be replaced with **cpd00166** in the biomass reactions.

**Comment by Waschina** [comment]
List of remaining missing biomass compounds:

1.     **cpd15817**    3hdpgpe    2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycero-l-phosphoethanolamine
2.     **cpd15818**    3hdpgpg    2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycerol-1-phospho-3'-sn-glycerol
3.     **cpd15819**    3hdpgpi    2-O-(3'-hydroxyl)phytanyl-3-O-phytanyl-sn-glycero-1-phospho-myo-inositol
4.     **cpd15820**    3hdpgps    2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycero-l-phosphoserine
5.     **cpd15834**    adocblhbi    Adenosylcobalamin-HBI
6.     **cpd15858**    dpgpe    2,3-O-phytanyl-sn-glycero-1-phosphoethanolamine
7.     **cpd15859**    dpgpg    2,3-di-O-phytanyl-sn-glycerol-1-phospho-3'-sn-glycerol
8.     **cpd15860**    dpgpi    2,3-O-phytanyl-sn-glycero-1-phospho-myo-inositol
9.     **cpd15861**    dpgps    2,3-O-phytanyl-sn-glycero-1-phosphoserine
10.     **cpd15880**    gdpgpi    glucosaminyl archaetidyl-myo-inositol
11.     **cpd15884**    h4spt    tetrahydrosarcinapterin

**Comment by Waschina** [comment]
**cpd15834** (_adocblhbi_ – Adenosylcobalamin-HBI) is replaced with the new metabolite entry **cpd33626** (adenosyl factor III), which denotes the same metabolite but whose biosynthesis pathways are based on MetaCyc ([PWY-7969](https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-7969)). It can new be produced with the gapseq reaction database.
**cpd15884** (h4spt – tetrahydrosarcinapterin) can now also be produced.

List of remaining missing archaea biomass compounds, that cannot be produced:

1. **cpd15817** (_3hdpgpe_ – 2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycero-l-phosphoethanolamine)
2. **cpd15818** (_3hdpgpg_ – 2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycerol-1-phospho-3'-sn-glycerol)
3. **cpd15819** (_3hdpgpi_ – 2-O-(3'-hydroxyl)phytanyl-3-O-phytanyl-sn-glycero-1-phospho-myo-inositol)
4. **cpd15820** (_3hdpgps_ – 2-O-(3'-hydroxy)phytanyl-3-O-phytanyl-sn-glycero-l-phosphoserine)
5. **cpd15858** (_dpgpe_ – 2,3-O-phytanyl-sn-glycero-1-phosphoethanolamine)
6. **cpd15859** (_dpgpg_ – 2,3-di-O-phytanyl-sn-glycerol-1-phospho-3'-sn-glycerol)
7. **cpd15860** (_dpgpi_ – 2,3-O-phytanyl-sn-glycero-1-phospho-myo-inositol)
8. **cpd15861** (_dpgps_ – 2,3-O-phytanyl-sn-glycero-1-phosphoserine)
9. **cpd15880** (_gdpgpi_ – glucosaminyl archaetidyl-myo-inositol)

**Comment by Waschina** [comment]
Following the recent commit 39ab2cb45b17fc657a25f3cc894af8a1bb2c660d , also all remaining biomass components can now be produced.
