### ISSUE TITLE
 stat: cannot stat '/scratch/users/nus/e0512805/gapseq/src/../dat/seq/Bacteria/rev/sequences.tar.gz': No such file or directory 

### ISSUE THREAD

**Issue by arijitnus** [jotech/gapseq#190]
> for bug reports and errors please report the output of: ./gapseq test
gapseq version: 1.2 139b3b42
linux-gnu
#1 SMP Mon Oct 18 14:34:11 EDT 2021 

#######################
#Checking dependencies#
#######################
ldconfig (GNU libc) 2.28
libsbml NOT FOUND
libglpk NOT FOUND
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.11
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.14.1+
exonerate from exonerate version 2.4.0
bedtools v2.31.0
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
git version 2.42.0
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
GNU parallel 20230722
HMMER 3.3.2 (Nov 2020); http://hmmer.org/
bc 1.07.1

Missing dependencies: 2

#####################
#Checking R packages#
#####################
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
data.table 1.14.8 
stringr 1.5.0 
sybil 2.2.0 
getopt 1.20.3 
doParallel 1.0.17 
foreach 1.5.2 
R.utils 2.12.2 
stringi 1.7.12 
glpkAPI 1.3.4 
BiocManager 1.30.22 
Biostrings 2.68.1 
jsonlite 1.8.7 
CHNOSZ 2.0.0 
httr 1.4.7 

Missing R packages:  0 

##############################
#Checking basic functionality#
##############################
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
Warning message:
package 'Matrix' was built under R version 4.3.1 
Optimization test: OK 
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
Warning message:
package 'Matrix' was built under R version 4.3.1 
Building full model: OK 
Blast test: OK

Passed tests: 3/3

**Comment by arijitnus** [comment]
This is what I am receiving after trying ./gapseq doall /test_file.fna

**Comment by Waschina** [comment]
Hi @arijitnus,
thanks for using gapseq. 
Most likely you have not downloaded yet the reference sequence database. You can do that by 

```sh
cd <gapseq_dir>
bash ./src/update_sequences.sh
```

**Comment by arijitnus** [comment]
Hi @Waschina 
I tried the suggested command- 

However, the problem seems to persist, see below- 

Checking updates for Bacteria /home/users/nus/e0512805/gapseq/src/../dat/seq/Bacteria
failed: No route to host.
failed: No route to host.
failed: No route to host.
stat: cannot stat '/home/users/nus/e0512805/gapseq/src/../dat/seq/Bacteria/rev/sequences.tar.gz': No such file or directory

Appreciate any leads

**Comment by Waschina** [comment]
Hmm, could it be that the system where you have gapseq does not have internet access, or is blocking FTP connections?

**Comment by arijitnus** [comment]
@Waschina I am using a linux server which can download from web using http addresses. Since this is a university system I'm using, ftp access could be problematic. Do you suggest any workaround? Thanks

**Comment by arijitnus** [comment]
@Waschina I am using a linux server which can download from web using http addresses. Since this is a university system I'm using, ftp access could be problematic. Do you suggest any workaround? Thanks

**Comment by arijitnus** [comment]
This is resolved by using system with access to ftp.

**Comment by Waschina** [comment]
Thank you for the update, and it is good to hear you found a solution. We are planning to change the hosting of the reference protein sequence data soon. We will try to allow HTTP and FTP protocols. So thank you for the feedback!
