### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :   Timeout was reached: [rest.uniprot.org] SSL connection timeout

### ISSUE THREAD

**Issue by arijitnus** [jotech/gapseq#191]
> for bug reports and errors please report the output of: ./gapseq test
I seeing this error while running ./gapseq doall. Albeit I find that the outpur files are generated. Is it something I should be concerned and affect the results? Here is the error report?

#error report
Warning: [tblastn] Query_5 UniRef50_A0A6J4S0.. : Could not calculate ungapped K$
Warning: [tblastn] Query_1 UniRef50_O30642 M.. : One or more O characters repla$
Warning: [tblastn] Query_1 UniRef90_Q18TV3 T.. : One or more O characters repla$
Error in curl::curl_fetch_memory(url, handle = handle) :
  Timeout was reached: [rest.uniprot.org] SSL connection timeout
Calls: GET_retries ... request_fetch -> request_fetch.write_memory -> <Anonymou$
Execution halted
md5sum: def5a3cbe47f19f7ab34d01ba7a0b1f7.fasta: No such file or directory
cat: def5a3cbe47f19f7ab34d01ba7a0b1f7.fasta: No such file or directory
Wrote file ./10B2-draft.xml
Loading required package: glpkAPI
using GLPK version 5.0
Warning message:
glpkAPI is used but cplexAPI is recommended because it is much faster
Wrote file ./10B2.xml

##Output for ./gapseq test
gapseq version: 1.2 fb3631d5
linux-gnu
#1 SMP Wed Aug 10 16:21:17 UTC 2022 

#######################
#Checking dependencies#
#######################
ldconfig (GNU libc) 2.17
libsbml NOT FOUND
libglpk.so.36 -> libglpk.so.36.0.1
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.11
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.14.1+
exonerate from exonerate version 2.4.0
bedtools v2.31.0
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
git version 2.42.0
GNU parallel 20230922
HMMER 3.3.2 (Nov 2020); http://hmmer.org/
bc 1.07.1

Missing dependencies: 1

#####################
#Checking R packages#
#####################
data.table 1.14.8 
stringr 1.5.0 
sybil 2.2.0 
getopt 1.20.3 
doParallel 1.0.17 
foreach 1.5.2 
R.utils 2.12.2 
stringi 1.7.12 
glpkAPI 1.3.4 
BiocManager 1.30.22 
Biostrings 2.68.1 
jsonlite 1.8.7 
CHNOSZ 2.0.0 
httr 1.4.7 

Missing R packages:  0 

##############################
#Checking basic functionality#
##############################
Optimization test: OK 
Building full model: OK 
Blast test: OK

Passed tests: 3/3

**Comment by Waschina** [comment]
When reporting issues, please provide the exact gapseq command(s) used. Otherwise we cannot investigate the issue.

Also: Please use code-block formatting for code lines and logs (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Comment by arijitnus** [comment]
@Waschina apologies for making this question unclear. 
I am actually receiving this when running the following command for 10B2.fna file- 
```
./gapseq doall 10B2.fna
```
#Error report:

```
Warning: [tblastn] Query_5 UniRef50_A0A6J4S0.. : Could not calculate ungapped K$
Warning: [tblastn] Query_1 UniRef50_O30642 M.. : One or more O characters repla$
Warning: [tblastn] Query_1 UniRef90_Q18TV3 T.. : One or more O characters repla$
Error in curl::curl_fetch_memory(url, handle = handle) :
Timeout was reached: [rest.uniprot.org] SSL connection timeout
Calls: GET_retries ... request_fetch -> request_fetch.write_memory -> <Anonymou$
Execution halted
md5sum: def5a3cbe47f19f7ab34d01ba7a0b1f7.fasta: No such file or directory
cat: def5a3cbe47f19f7ab34d01ba7a0b1f7.fasta: No such file or directory
Wrote file ./10B2-draft.xml
Loading required package: glpkAPI
using GLPK version 5.0
Warning message:
glpkAPI is used but cplexAPI is recommended because it is much faster
Wrote file ./10B2.xml
```
#Output for ./gapseq test

```
gapseq version: 1.2 https://github.com/jotech/gapseq/commit/fb3631d5157dbc15724b05a49b7d412ba1cbb12f
linux-gnu
https://github.com/jotech/gapseq/issues/1 SMP Wed Aug 10 16:21:17 UTC 2022

#######################
#Checking dependencies#
#######################
ldconfig (GNU libc) 2.17
libsbml NOT FOUND
libglpk.so.36 -> libglpk.so.36.0.1
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.11
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.14.1+
exonerate from exonerate version 2.4.0
bedtools v2.31.0
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
git version 2.42.0
GNU parallel 20230922
HMMER 3.3.2 (Nov 2020); http://hmmer.org/
bc 1.07.1

Missing dependencies: 1

#####################
#Checking R packages#
#####################
data.table 1.14.8
stringr 1.5.0
sybil 2.2.0
getopt 1.20.3
doParallel 1.0.17
foreach 1.5.2
R.utils 2.12.2
stringi 1.7.12
glpkAPI 1.3.4
BiocManager 1.30.22
Biostrings 2.68.1
jsonlite 1.8.7
CHNOSZ 2.0.0
httr 1.4.7

Missing R packages: 0

##############################
#Checking basic functionality#
##############################
Optimization test: OK
Building full model: OK
Blast test: OK

Passed tests: 3/3

```

**Comment by jotech** [comment]
the uniprot server seems unreachable. have you tried it again? alternatively you can use 
`./gapseq find -p all -t auto -O 10B2.fna` 
(`-O` enables offline mode)

**Comment by arijitnus** [comment]
@jotech , thanks for the lead. I could solve this issue by running ./gapseq find in offline mode. Hence closing this issue.
