### ISSUE TITLE
Download sequences fails

### ISSUE THREAD

**Issue by pbelmann** [jotech/gapseq#195]
Recently, I can no longer download the sequences file.

ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz

It just leads to connection refused:

```
>wget ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz
--2023-10-13 07:01:00--  ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz
           => ‘sequences.tar.gz’
Resolving ftp.rz.uni-kiel.de (ftp.rz.uni-kiel.de)... 134.245.2.194
Connecting to ftp.rz.uni-kiel.de (ftp.rz.uni-kiel.de)|134.245.2.194|:21... failed: Connection refused.
```

**Comment by jotech** [comment]
hi @pbelmann 
thank you for reporting, I can confirm the issue.

We will move the database to zenodo soon, you can already access the missing sequences here:
https://zenodo.org/records/7643340

**Comment by Waschina** [comment]
The issue should be fixed now. However, I keep it pinned for a bit more in case users experience problems. If yes, please re-open this issue.
