### ISSUE TITLE
Photosynthesis

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#20]
Dear All,

I would like to ask you about photosynthesis pathways. According to my collaborator, a marine bacterium should be able to make photosynthesis, but I see that there is oxygen dependency in the respective model. Assuming that the genomic information is complete, would gapseq add photosynthesis pathways?

Kind Regards,
Georgios

**Comment by Waschina** [comment]
Enabling the reconstruction of photosynthetic bacteria, where light is used to fuel certain reaction will be included in the future.

**Comment by jotech** [comment]
in many cases, photosynthetic pathways are already predicted. You can check this by looking at the ``gapseq.sh`` output file ``*-all-Pathways.tbl``. Nonetheless, model reactions are not able to capture this yet!

**Comment by Waschina** [comment]
Photosynthesis pathways should work now.
See 209ed244355881ef246cb15ecce339e52a17bae5 and preceding commits.
