### ISSUE TITLE
[Request Update] [Tutorial] For anyone who intend to use CPLEX in gapseq

### ISSUE THREAD

**Issue by ElderMedic** [jotech/gapseq#201]
Information regarding "cplex solver support" in the documentation of gapseq is outdated, the cplexAPI R package is deprecated, and most of the links used do not exist now. 

- **Rcplex** package is an alternative to the **cplexAPI** (not on CRAN anymore), installation is very similar and requires specifying the location of CPLEX 
  - prerequisite: R install package **slam** and sybilSBML.
- Before installing the cplex R API, do install CPLEX Studio itself first with its binary installer (linux x86_64). 
  - If you want to deploy gapseq with cplex in docker, prepare a response.properties file, here is a reference to [our project:](https://gitlab.com/m-unlock/docker/-/tree/main/cwl/builder/docker/gapseq?ref_type=heads)
  - changing the default CPLEX Studio install path is risky, don't recommend doing that. 

> for bug reports and errors please report the output of: ./gapseq test
```shell
gapseq version: 1.2 13661828
linux-gnu
#224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023


#######################
#Checking dependencies#
#######################
ldconfig (Ubuntu GLIBC 2.31-0ubuntu9.12) 2.31
libsbml.so.5 -> libsbml.so.5.18.0
libglpk.so.40 -> libglpk.so.40.3.1
GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)
sed (GNU sed) 4.8
grep (GNU grep) 3.11
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi
tblastn: 2.14.1+
exonerate from exonerate version 2.4.0
bedtools v2.31.1
barrnap 0.9 - rapid ribosomal RNA prediction
R version 4.3.2 (2023-10-31) -- "Eye Holes"
git version 2.42.0
GNU parallel 20231122
HMMER 3.4 (Aug 2023); http://hmmer.org/
bc 1.07.1

Missing dependencies: 0


#####################
#Checking R packages#
#####################
data.table 1.14.8
stringr 1.5.1
sybil 2.2.0
getopt 1.20.4
doParallel 1.0.17
foreach 1.5.2
R.utils 2.12.3
stringi 1.8.2
glpkAPI 1.3.4
BiocManager 1.30.22
Biostrings 2.68.1
jsonlite 1.8.7
CHNOSZ 2.0.0
httr 1.4.7

Missing R packages:  0


##############################
#Checking basic functionality#
##############################
Optimization test: OK
Building full model: OK
Blast test: OK

Passed tests: 3/3
```

**Comment by ElderMedic** [comment]
Some helpful links may be helpful for potential trouble shooting:
http://jrzubizarreta.com/INSTALL
https://cran.r-project.org/web/packages/Rcplex/INSTALL
https://github.com/cran/cplexAPI/blob/master/inst/INSTALL
https://stackoverflow.com/questions/57058478/could-not-link-cplex-library-in-r

For CPLEX Studio installation (22.1.0 for now), refer to the README.html attached to download. 
https://www.ibm.com/docs/en/icos/22.1.1?topic=2211-silent-installation-cplex-optimization-studio

**Comment by Porthmeus** [comment]
Largest problem is that gapseq itself is not using cplexAPI, but sybil is which is called by gapseq. Sybil is not maintained within gapseq but here: https://github.com/SysBioChalmers/sybil. So you might cross post the issue there if you want to see it implemented.

If you need CPEX within gapseq, you can install the old cplexAPI by following the instructions given here: https://github.com/Waschina/MicrobiomeGS2

**Comment by Waschina** [comment]
Hi @ElderMedic,

Thanks for the feedback. I updated the CPLEX support part of the documentation.

We are working on a solution to remove gapseq's dependencies on the R-packages *sybil* and *glpkAPI*/*cplexAPI*. The final goal is to make the installation easier across systems.
