### ISSUE TITLE
Any plans on updating MetaCyc database?

### ISSUE THREAD

**Issue by VadimDu** [jotech/gapseq#208]
Dear developers,

I wanted to ask you which version of MetaCyc do you use currently in GapSeq? And do you have any plans on updating it to the latest version (e.g. 27.0 or 27.1 / 27.5) ?

And of course well done on the great tool!

Best regards
VadimD

**Comment by jotech** [comment]
Dear Vadim

we already updated in December to 27.0 https://github.com/jotech/gapseq/commit/024476a609b7add2cc550a77d290122f8b97cc13

Do you have a specific pathway in mind that is missing?

**Comment by VadimDu** [comment]
Dear @jotech 

Thank you for the fast response!
I wasn't looking for a specific pathway, just wanted to see if MetaCyc was up to date, before analyzing some data with gapseq.

all the best
VadimD
