### ISSUE TITLE
Missing exchange reactions are not being added in the "adapt" module

### ISSUE THREAD

**Issue by utkinaira** [jotech/gapseq#214]
Dear gapseq team,

Firstly, I want to thank you for your efforts in developing and maintaining the gapseq tool. It's been incredibly useful for model generation.

I've noticed in the "adapt" module that although the script for the function "add_missing_exchanges" is loaded, it doesn't seem to be used. And as a result, the adapted models may lack certain exchange reactions for metabolites in newly introduced reactions or pathways.
I thought to mention this as integrating "add_missing_exchanges" into the "adapt" workflow could make the models more comprehensive and reduce the need for manual adjustments. 

Best regards,
Irina

**Comment by Waschina** [comment]
Hi Irina,

thank you for the feedback! It sounds logical to include the function of the adapt workflow. I will try to implement it in the next few days.

Best
Silvio

**Comment by Waschina** [comment]
Hi Irina,

Do you have an example of the `gapseq adapt ...` command that results in a new extracellular metabolite without the corresponding exchange reaction? I want to test it with a use case.

**Comment by Waschina** [comment]
The issue should now be fixed. I tested it by adding the pathway "INULIN-DEGRADATION-EXO", which includes extracellular metabolites, which now get an exchange reaction if the metabolite is new after the `gapseq adapt ...` command.

Thanks for reporting!
