### ISSUE TITLE
Seawater and related media

### ISSUE THREAD

**Issue by lxsteiner** [jotech/gapseq#215]
Hi,

Not an issue but a few questions on the seawater recipe and adding other related media.

How was the existing "meerwasser" recipe made, or what was the reference? 
https://github.com/jotech/gapseq/commit/5d0aeafc3d40a0430aaed84b4f6eb9aba2549df6#diff-d82c35c23e1d05980fc5b6b31e9b25b406f669fdf8c34a76805931fc784ae6a4

I'd like to predict the growth with a "marine broth" (MB) medium https://www.dsmz.de/microorganisms/medium/pdf/DSMZ_Medium514.pdf    
and I was looking at KOMODO https://komodo.modelseed.org/servlet/KomodoTomcatServerSideUtilitiesModelSeed?MediaList but it doesn't seem like the resources are available anymore. I also looked at ModelSEED but none of the recipes from KOMODO exist there https://modelseed.org/list-media/ unless I am looking at the wrong location. It also seems like the recipes there only list the compounds rather than specifying the concentration (i.e. all values are 0.001).
Could you please advise how or where to get the recipes then?

I was hoping to get some hints on how to culture a bacterium based on missing compounds, identified by comparing the compounds listed in the seawater and MB medium with a predicted medium by gapseq. Do you think that makes sense?

Thank you.

**Comment by jotech** [comment]
Hi @lxsteiner 

The seawater medium (meerwasser.csv) is a very generic growth medium that we once created for modeling microbes from sponges. Although it is not very specific, it could be worth extending it. But be aware that the actual lower bounds are all set to -100.

I'm sorry, I don't know what happened to the modelseed komodo server.
