### ISSUE TITLE
Include in-vitro data in the pipeline

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#22]
Dear All,

Once I have made some simulations with gapseq models under a specific minimal medium. When my collaborators tested the bacteria under this medium, some bacteria failed to grow, some others grew. Would it possible to include this fail/success information in the pipeline of model creation?

Kind Regards,
Georgios

**Comment by jotech** [comment]
if you have a list with carbon sources which can/cannot be used this can already be done!

**Comment by maringos** [comment]
What specific kind of format is accepted? Which argument does enable this feature?

**Comment by jotech** [comment]
it is done by the module ``gs.adapt`` which will be integrated in gapseq main program soon

**Comment by Waschina** [comment]
Functionality integrated in `adapt.R`
