### ISSUE TITLE
gapseq with Gurobi

### ISSUE THREAD

**Issue by Brunokemon** [jotech/gapseq#225]
Hi 
is there a way to use Gurobi as the optimizer instead of cplex?

**Comment by Waschina** [comment]
Unfortunately, no.

gapseq currently relies on the R package "sybil" and it's interfaces to various solvers. A Gurobi interface does not appear to be available. We are currently working on a replacement for "sybil", but adding GUROBI support is not on our priority list, at least not at the moment.

**Comment by Brunokemon** [comment]
Oh I see :( 
Thanks!
