### ISSUE TITLE
Addition of a compound in the network

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#23]
Dear All,

I need to check the production or consumption of a molecule (EX_cpd00281_e0) in some models. Unfortunately, it is not included in the networks. How can I include it (and the relevant reactions) in the model?
I have tried to add it in the predifined medium during the model construction, but this leads only to consumption as expected.

Kind Regards,
Georgios

**Comment by Waschina** [comment]
You can manually add reactions after the reconstruction using the sybil::addReact(…) function.

**Comment by maringos** [comment]
Thanks for the useful answer!
