### ISSUE TITLE
I can not install sybilSBML_3.1.2.tar.gz

### ISSUE THREAD

**Issue by qikongwanli** [jotech/gapseq#235]
> for bug reports and errors please report the output of: ./gapseq test
❯ R CMD INSTALL --configure-args=" \
--with-sbml-include=$CONDA_PREFIX/include \
--with-sbml-lib=$CONDA_PREFIX/lib" sybilSBML_3.1.2.tar.gz
rm sybilSBML_3.1.2.tar.gz

* installing to library '/home/qing/miniconda3/envs/gapseq-dev/lib/R/library'
* installing *source* package 'sybilSBML' ...
** package 'sybilSBML' successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda-linux-gnu-cc accepts -g... yes
checking for x86_64-conda-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... x86_64-conda-linux-gnu-cc -E
checking for pkg-config... /home/qing/miniconda3/envs/gapseq-dev/bin/pkg-config
configure: set compile and link flags according to pkg-config
configure: compile flags are -I/home/qing/miniconda3/envs/gapseq-dev/include -I/home/qing/miniconda3/envs/gapseq-dev/include/libxml2 -I/home/qing/miniconda3/envs/gapseq-dev/include
configure: link flags are -L/home/qing/miniconda3/envs/gapseq-dev/lib -lsbml
checking for grep that handles long lines and -e... /home/qing/miniconda3/envs/gapseq-dev/bin/grep
checking for egrep... /home/qing/miniconda3/envs/gapseq-dev/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sbml/SBMLTypes.h usability... yes
checking sbml/SBMLTypes.h presence... yes
checking for sbml/SBMLTypes.h... yes
checking for library containing readSBML... none required
checking for readSBML in -lsbml... yes
checking for sbml/packages/fbc/common/FbcExtensionTypes.h... yes
checking for sbml/packages/groups/common/GroupsExtensionTypes.h... yes
checking for SBase_getPlugin... yes
checking for SBMLExtensionRegistry_getRegisteredPackages... yes
checking for GeneProductAssociation_setAssociation... yes
checking for FbcReactionPlugin_getLowerFluxBound... yes
configure: creating ./config.status
config.status: creating src/Makevars.tmp
config.status: creating src/Makevars
config.status: creating src/config.h
** libs
using C compiler: 'x86_64-conda-linux-gnu-cc (conda-forge gcc 14.1.0-1) 14.1.0'
x86_64-conda-linux-gnu-cc -I"/home/qing/miniconda3/envs/gapseq-dev/lib/R/include" -DNDEBUG -DHAVE_CONFIG_H -I/home/qing/miniconda3/envs/gapseq-dev/include -I/home/qing/miniconda3/envs/gapseq-dev/include/libxml2 -I/home/qing/miniconda3/envs/gapseq-dev/include   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/qing/miniconda3/envs/gapseq-dev/include -I/home/qing/miniconda3/envs/gapseq-dev/include -Wl,-rpath-link,/home/qing/miniconda3/envs/gapseq-dev/lib    -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/qing/miniconda3/envs/gapseq-dev/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1723488709275/work=/usr/local/src/conda/r-base-4.3.3 -fdebug-prefix-map=/home/qing/miniconda3/envs/gapseq-dev=/usr/local/src/conda-prefix  -c init.c -o init.o
x86_64-conda-linux-gnu-cc -I"/home/qing/miniconda3/envs/gapseq-dev/lib/R/include" -DNDEBUG -DHAVE_CONFIG_H -I/home/qing/miniconda3/envs/gapseq-dev/include -I/home/qing/miniconda3/envs/gapseq-dev/include/libxml2 -I/home/qing/miniconda3/envs/gapseq-dev/include   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/qing/miniconda3/envs/gapseq-dev/include -I/home/qing/miniconda3/envs/gapseq-dev/include -Wl,-rpath-link,/home/qing/miniconda3/envs/gapseq-dev/lib    -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/qing/miniconda3/envs/gapseq-dev/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1723488709275/work=/usr/local/src/conda/r-base-4.3.3 -fdebug-prefix-map=/home/qing/miniconda3/envs/gapseq-dev=/usr/local/src/conda-prefix  -c sbml.c -o sbml.o
x86_64-conda-linux-gnu-cc -I"/home/qing/miniconda3/envs/gapseq-dev/lib/R/include" -DNDEBUG -DHAVE_CONFIG_H -I/home/qing/miniconda3/envs/gapseq-dev/include -I/home/qing/miniconda3/envs/gapseq-dev/include/libxml2 -I/home/qing/miniconda3/envs/gapseq-dev/include   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/qing/miniconda3/envs/gapseq-dev/include -I/home/qing/miniconda3/envs/gapseq-dev/include -Wl,-rpath-link,/home/qing/miniconda3/envs/gapseq-dev/lib    -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/qing/miniconda3/envs/gapseq-dev/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1723488709275/work=/usr/local/src/conda/r-base-4.3.3 -fdebug-prefix-map=/home/qing/miniconda3/envs/gapseq-dev=/usr/local/src/conda-prefix  -c sybilSBML.c -o sybilSBML.o
In file included from sybilSBML.c:56:
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/sbml/FluxObjective.h:1215:1: error: unknown type name 'FbcVariableType_t'
 1215 | FbcVariableType_t
      | ^~~~~~~~~~~~~~~~~
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/sbml/FluxObjective.h:1470:31: error: unknown type name 'FbcVariableType_t'
 1470 |                               FbcVariableType_t variableType);
      |                               ^~~~~~~~~~~~~~~~~
sybilSBML.c: In function 'getSBMLSpeciesList':
sybilSBML.c:1128:44: error: passing argument 1 of 'FbcSpeciesPlugin_isSetCharge' from incompatible pointer type [-Wincompatible-pointer-types]
 1128 |           if (FbcSpeciesPlugin_isSetCharge(SpeciesPlug)) {
      |                                            ^~~~~~~~~~~
      |                                            |
      |                                            SBasePlugin_t * {aka struct SBasePlugin *}
In file included from sybilSBML.c:52:
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcSpeciesPlugin.h:677:49: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  677 | FbcSpeciesPlugin_isSetCharge(FbcSBasePlugin_t * fbc);
      |                              ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1129:66: error: passing argument 1 of 'FbcSpeciesPlugin_getCharge' from incompatible pointer type [-Wincompatible-pointer-types]
 1129 |               INTEGER(metcharge)[i] = FbcSpeciesPlugin_getCharge(SpeciesPlug);
      |                                                                  ^~~~~~~~~~~
      |                                                                  |
      |                                                                  SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcSpeciesPlugin.h:647:47: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  647 | FbcSpeciesPlugin_getCharge(FbcSBasePlugin_t * fbc);
      |                            ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1134:53: error: passing argument 1 of 'FbcSpeciesPlugin_isSetChemicalFormula' from incompatible pointer type [-Wincompatible-pointer-types]
 1134 |           if (FbcSpeciesPlugin_isSetChemicalFormula(SpeciesPlug)) {
      |                                                     ^~~~~~~~~~~
      |                                                     |
      |                                                     SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcSpeciesPlugin.h:761:58: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  761 | FbcSpeciesPlugin_isSetChemicalFormula(FbcSBasePlugin_t * fbc);
      |                                       ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1135:90: error: passing argument 1 of 'FbcSpeciesPlugin_getChemicalFormula' from incompatible pointer type [-Wincompatible-pointer-types]
 1135 |               SET_STRING_ELT(metchemic, i, Rf_mkChar(FbcSpeciesPlugin_getChemicalFormula(SpeciesPlug)));
      |                                                                                          ^~~~~~~~~~~
      |                                                                                          |
      |                                                                                          SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcSpeciesPlugin.h:745:56: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  745 | FbcSpeciesPlugin_getChemicalFormula(FbcSBasePlugin_t * fbc);
      |                                     ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c: In function 'getSBMLReactionsList':
sybilSBML.c:1401:53: error: passing argument 1 of 'FbcReactionPlugin_isSetLowerFluxBound' from incompatible pointer type [-Wincompatible-pointer-types]
 1401 |           if (FbcReactionPlugin_isSetLowerFluxBound(reactionPlug))
      |                                                     ^~~~~~~~~~~~
      |                                                     |
      |                                                     SBasePlugin_t * {aka struct SBasePlugin *}
In file included from sybilSBML.c:51:
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:832:58: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  832 | FbcReactionPlugin_isSetLowerFluxBound(FbcSBasePlugin_t * fbc);
      |                                       ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1403:110: error: passing argument 1 of 'FbcReactionPlugin_getLowerFluxBound' from incompatible pointer type [-Wincompatible-pointer-types]
 1403 |               parm = Model_getParameterById(R_ExternalPtrAddr (sbmlmod) ,FbcReactionPlugin_getLowerFluxBound(reactionPlug));
      |                                                                                                              ^~~~~~~~~~~~
      |                                                                                                              |
      |                                                                                                              SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:816:56: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  816 | FbcReactionPlugin_getLowerFluxBound(FbcSBasePlugin_t * fbc);
      |                                     ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1413:53: error: passing argument 1 of 'FbcReactionPlugin_isSetUpperFluxBound' from incompatible pointer type [-Wincompatible-pointer-types]
 1413 |           if (FbcReactionPlugin_isSetUpperFluxBound(reactionPlug))
      |                                                     ^~~~~~~~~~~~
      |                                                     |
      |                                                     SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:766:58: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  766 | FbcReactionPlugin_isSetUpperFluxBound(FbcSBasePlugin_t * fbc);
      |                                       ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1415:110: error: passing argument 1 of 'FbcReactionPlugin_getUpperFluxBound' from incompatible pointer type [-Wincompatible-pointer-types]
 1415 |               parm = Model_getParameterById(R_ExternalPtrAddr (sbmlmod) ,FbcReactionPlugin_getUpperFluxBound(reactionPlug));
      |                                                                                                              ^~~~~~~~~~~~
      |                                                                                                              |
      |                                                                                                              SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:750:56: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  750 | FbcReactionPlugin_getUpperFluxBound(FbcSBasePlugin_t * fbc);
      |                                     ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1484:61: error: passing argument 1 of 'FbcReactionPlugin_isSetGeneProductAssociation' from incompatible pointer type [-Wincompatible-pointer-types]
 1484 |           if( FbcReactionPlugin_isSetGeneProductAssociation(reactionPlug) ) {
      |                                                             ^~~~~~~~~~~~
      |                                                             |
      |                                                             SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:884:66: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  884 | FbcReactionPlugin_isSetGeneProductAssociation(FbcSBasePlugin_t * fbc);
      |                                               ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1485:91: error: passing argument 1 of 'FbcReactionPlugin_getGeneProductAssociation' from incompatible pointer type [-Wincompatible-pointer-types]
 1485 |               GeneProductAssociation_t* gpa = FbcReactionPlugin_getGeneProductAssociation(reactionPlug);
      |                                                                                           ^~~~~~~~~~~~
      |                                                                                           |
      |                                                                                           SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:898:64: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  898 | FbcReactionPlugin_getGeneProductAssociation(FbcSBasePlugin_t * fbc);
      |                                             ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c: In function 'exportSBML':
sybilSBML.c:1942:45: error: passing argument 1 of 'FbcSpeciesPlugin_setChemicalFormula' from incompatible pointer type [-Wincompatible-pointer-types]
 1942 |         FbcSpeciesPlugin_setChemicalFormula(SpeciesPlug, CHAR(STRING_ELT(met_form, i)));
      |                                             ^~~~~~~~~~~
      |                                             |
      |                                             SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcSpeciesPlugin.h:781:56: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  781 | FbcSpeciesPlugin_setChemicalFormula(FbcSBasePlugin_t * fbc, const char * chemicalFormula);
      |                                     ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:1958:36: error: passing argument 1 of 'FbcSpeciesPlugin_setCharge' from incompatible pointer type [-Wincompatible-pointer-types]
 1958 |         FbcSpeciesPlugin_setCharge(SpeciesPlug, INTEGER(met_charge)[i]);
      |                                    ^~~~~~~~~~~
      |                                    |
      |                                    SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcSpeciesPlugin.h:696:47: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  696 | FbcSpeciesPlugin_setCharge(FbcSBasePlugin_t * fbc, int charge);
      |                            ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:2080:51: error: passing argument 1 of 'FbcReactionPlugin_setGeneProductAssociation' from incompatible pointer type [-Wincompatible-pointer-types]
 2080 |       FbcReactionPlugin_setGeneProductAssociation(reactionPlug,gpa);
      |                                                   ^~~~~~~~~~~~
      |                                                   |
      |                                                   SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:915:64: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  915 | FbcReactionPlugin_setGeneProductAssociation(FbcSBasePlugin_t * fbc,
      |                                             ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:2282:43: error: passing argument 1 of 'FbcReactionPlugin_setLowerFluxBound' from incompatible pointer type [-Wincompatible-pointer-types]
 2282 |       FbcReactionPlugin_setLowerFluxBound(reactionPlug, para_lb);
      |                                           ^~~~~~~~~~~~
      |                                           |
      |                                           SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:852:56: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  852 | FbcReactionPlugin_setLowerFluxBound(FbcSBasePlugin_t * fbc, const char * LowerFluxBound);
      |                                     ~~~~~~~~~~~~~~~~~~~^~~
sybilSBML.c:2283:43: error: passing argument 1 of 'FbcReactionPlugin_setUpperFluxBound' from incompatible pointer type [-Wincompatible-pointer-types]
 2283 |       FbcReactionPlugin_setUpperFluxBound(reactionPlug, para_ub);
      |                                           ^~~~~~~~~~~~
      |                                           |
      |                                           SBasePlugin_t * {aka struct SBasePlugin *}
/home/qing/miniconda3/envs/gapseq-dev/include/sbml/packages/fbc/extension/FbcReactionPlugin.h:786:56: note: expected 'FbcSBasePlugin_t *' {aka 'struct FbcSBasePlugin *'} but argument is of type 'SBasePlugin_t *' {aka 'struct SBasePlugin *'}
  786 | FbcReactionPlugin_setUpperFluxBound(FbcSBasePlugin_t * fbc, const char * UpperFluxBound);
      |                                     ~~~~~~~~~~~~~~~~~~~^~~
make: *** [/home/qing/miniconda3/envs/gapseq-dev/lib/R/etc/Makeconf:193: sybilSBML.o] Error 1
ERROR: compilation failed for package 'sybilSBML'
* removing '/home/qing/miniconda3/envs/gapseq-dev/lib/R/library/sybilSBML'

**Comment by ryan-boobybiome** [comment]
I think the solution to this is to have libsbml v5.18.0 installed. A later version of libsbml was giving me the same error.

**Comment by Waschina** [comment]
Yes, this is an issue with sybilSBML and not gapseq.

As @ryan-boobybiome mentioned, a current workaround is to downgrade libsbml to 5.18.0

In an upcoming version of gapseq, sybilSBML will no longer be a dependency of gapseq, and later versions of libSBML will be compatible.

**Comment by Waschina** [comment]
With the new gapseq development version, 'sybilSBML' is no longer needed. Gapseq should now be compatible with libSBML >=5.18.0.

**Comment by Waschina** [comment]
Closing the issue, since gapseq does not depend on sybilSBML anymore.
