### ISSUE TITLE
Documentation rebuild after changes

### ISSUE THREAD

**Issue by Waschina** [jotech/gapseq#239]
@jotech, it looks like that readthedoc is not automatically updating the gapseq documentation webpage after a change in the documentation files. Are there perhaps some configurations that need to be changed?

**Comment by jotech** [comment]
There seems to be a problem with the GitHub integration in readthedocs. I regenerated the webhook and rebuilt the documentation manually, but it should work automatically for future commits.

**Comment by Waschina** [comment]
works :) thanks!
