### ISSUE TITLE
gapseq_quickstart missing

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#24]
Dear All,
I have noticed that the script gapseq_quickstart is missing from the main folder of gapseq. Has it been removed intentionally ?
Kind Regards,
Georgios

**Comment by jotech** [comment]
gapseq has a new starter which bundles all feature in one script! See ``./gapseq`` for details :)

**Comment by maringos** [comment]
Many thanks for your answer! If I understood the code correctly, there is no way to change the parameter dat/media/ALLmed.csv . Could you clarify this?

**Comment by jotech** [comment]
no this is not correct! only the ``doall`` mode was using the default medium. you can specify whatever you want with ``./gapfill fill``. anyway, the latest update also allows medium selection for ``doall`` :)
