### ISSUE TITLE
Include cobrar in the conda env file

### ISSUE THREAD

**Issue by Unaimend** [jotech/gapseq#240]
Hi, AFAIK, cobrar is on conda but it's currently not being installed when installing the requirements from the conda env file. 

Thanks for your time 
Thomas

**Comment by Unaimend** [comment]
Might also be relevant for the bioconda version

**Comment by Waschina** [comment]
Hi! cobrar is already specified in th conda env file. This should install cobrar when using the env file for a conda environment.

https://github.com/jotech/gapseq/blob/792194b752523570b7cb0bdde3025f918d876cc2/gapseq_env.yml#L30

As for the bioconda package for gapseq, we wanted to wait 2-3 weeks to see if users report issues with the cobrar implementation in gapseq developments version. After that, we want to make a new release, along with an update of gapseq on bioconda.

Thanks!

**Comment by Unaimend** [comment]
Well, that is embarrassing, must have overlooked it.
Thanks for the pointer

**Comment by Waschina** [comment]
No worries, thanks for testing!

**Comment by Calvin2077** [comment]
I can't seem to install r-cobrar can I have some help please
