### ISSUE TITLE
gapseq transporter error

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#25]
Hi,
I think the transporter file should be called by `$dir/src/transporter.sh -b 200 $file `

https://github.com/jotech/gapseq/blob/3cb64e71aa7dfa3ea77c59eae41912dcb78002ae/gapseq#L78

Regards,
Georgios 
Thanks for your rapid support beforehand :)

**Comment by jotech** [comment]
never call it 'rapid' before it's done :D
