### ISSUE TITLE
-draft error in automated pipeline

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#26]
The addition of  "-draft" in the line below causes an error in gapseq automated pipeline, as the input of gf.suite.R is` gf.suite.R -m ./${id}.RDS`

https://github.com/jotech/gapseq/blob/7d697730ea9c8486dc9affa67aa9b54c7f0caf21/src/generate_GSdraft.R#L359

https://github.com/jotech/gapseq/blob/7d697730ea9c8486dc9affa67aa9b54c7f0caf21/gapseq#L80

**Comment by Waschina** [comment]
Thanks for pointing this out. I hope it is fixed now.
