### ISSUE TITLE
doall stall

### ISSUE THREAD

**Issue by aassie** [jotech/gapseq#30]
Sorry to start another issue thread.

When I run `gapseq doall` I can see that some commands are running but at one point the scripts seem to hang. I don't have any output printed on the terminal and there are no files created in the folder. 

Do you have an idea of what could be the issue?

I did just try to run `gapseq find -p all` and this seems to work, I can see the script looking for pathways.

**Comment by aassie** [comment]
Not sure if it helps but I found out that the update_sequence.sh did not unpack the sequence.tar.gz files. I will have a closer look at this issue next week.

**Comment by jotech** [comment]
good avise! I added a parameter for this.
Could you try ``./gapseq -n doall`` and report where it hangs?

**Comment by jotech** [comment]
ok let's continue next week! thanks for your input :)

**Comment by aassie** [comment]
Hello Johannes,

I finally had time to go back to the Gapseq tool. I have updated the tool to the latest github version and rerun with your command.
It worked fine and generated all the files nicely, except for the sbml conversion where for the life of me I can't install SybilSbml (I have opened an issue on BacArena but it's probably the wrong place to do so).

One thing though, on the version I used a month ago gapseq was going through 2738 pathways and now it only goes through 1682. Why the switch? And is there somewhere the possibility to have the previous database? I have annotated a few genomes with the old DB and would like to keep using it for the next ones.

**Comment by jotech** [comment]
hi Adrien,
great to hear that it is running now!
The difference in the number of pathways is caused by a new setting that restricts metacyc pathway to bacteria-related pathways.
```
gapseq_find.sh -b 200 -p all -m bacteria fasta
```
If you remove ``-m bacteria`` you will get the old number of pathways again.

**Comment by jotech** [comment]
please reopen if still an issue
