### ISSUE TITLE
clpexAPI related bug on Virtual machine

### ISSUE THREAD

**Issue by aassie** [jotech/gapseq#33]
Hello Johannes,

So I still can't install `cplexAPI` on my virtual machine and couldn't find how to have the glpk solver used instead. I have digged a bit in the code and found out that the `adapt.R` and `gf.suite.R` scripts have to both load the `cplexAPI` before checking if it is present in the installed package.

if you move the 
```
suppressMessages(library(cplexAPI))
```

within the the if loop below
```
if( "cplexAPI" %in% rownames(installed.packages()) ){
  sybil::SYBIL_SETTINGS("SOLVER","cplexAPI"); ok <- 1
}else{
  warning("glpkAPI is used but cplexAPI is recommended because it is much faster")
  sybil::SYBIL_SETTINGS("SOLVER","glpkAPI"); ok <- 5
}
```

like this

```
if( "cplexAPI" %in% rownames(installed.packages()) ){
  suppressMessages(library(cplexAPI))
  sybil::SYBIL_SETTINGS("SOLVER","cplexAPI"); ok <- 1
}
```

it seems to fix the script crashing because it can't load the cplexAPI so it can't choose the solver =)

**Comment by Waschina** [comment]
Hello Adrien,

Thank you very much for pointing this out! The commit ac4259e should fix the issue in the same way as you suggested.
We'll also run some tests to comparemodels between glpk and cplex. 

Thanks again! 
Silvio

**Comment by Waschina** [comment]
Hello Adrien,

just as a small addition. I also struggled with the installation of `cplexAPI` but it worked for me using the following commands. Maybe it works for you the same way. 

```
CPLEXDIR=/dir/to/cplex129/cplex # adjust this with the path to your cplex installation
SYSTEM=`ls -d ${CPLEXDIR}/lib/*`
LIBFORMAT=static_pic
CPLEXLIBDIR=${SYSTEM}/${LIBFORMAT}

R CMD INSTALL --configure-args=" \
PKG_CFLAGS='-m64 -fPIC' \
PKG_CPPFLAGS='-I${CPLEXDIR}/include' \
PKG_LIBS='-L${CPLEXLIBDIR} -lcplex -lm -pthread -ldl'" \
cplexAPI_1.3.6.tar.gz
```
