### ISSUE TITLE
running GapSeq with customized pathways

### ISSUE THREAD

**Issue by songweizhi** [jotech/gapseq#34]
Dear GapSeq developers,
Thanks for developing this wonderful tool. 
I am trying to use GapSeq to see the occurence of a few customized pathways in my genomes. 

To do this, I removed the kegg_pwy.tbl, meta_pwy.tbl and seed_pwy.tbl in the dat folder, made-up my own pathways according to the pwy file format and added them to custom_pwy.tbl.

One thing I'd like to know is what does the last four columns in the pwy files refer to (e.g. 13	13	FALSE	TRUE )? Also, can I simply leave the "taxrange" column blank if I am not sure about what to put there? Do you have any description docs for the pwy files?

Thanks in advance,
Weizhi

**Comment by Waschina** [comment]
Dear Weizhi,

thank you for using GapSeq and your question. We will add a documentation on how to analyse a user-defined pathway soon. But here is what you can do right away:

Like you already said, you can add a user-defined pathway in the `dat/custom_pwy.tbl` file.

The columns are:
`id` - An unique Identifier for the new Pathway
`name` and `alname` - Name and alternative name the new pathway.
`hierachy` - This corresponds to the pathway-hierarchy / ontologie as in MetaCyc. In case you are unsure, simply use `|THINGS|` here.
`taxrange` - Corresponds to the taxonomic ranges as used defined in MetaCyc. For bacteria enter `|TAX-2|`
`reaId` - comma-separated list of the reaction identifiers (you can freely define new identifieres)
`recEc` - comma-separated list of reactions' EC-numbers. Should be the same length and in the same order as `reaId`. If no EC number is defined for a reaction, leave this field free (e.g. "1.1.1.1,,1.9.1.3", in case there is no EC-number for the second reaction")
`keyRea` - Identifier of the key-reaction of the pathway. Leave empty if you do not want to specifiy/know the key reaction. Can also be multiple key-reactions (separated by comma).
`reaName` - semicolon-separated list of reaction names. You are free to choose names here, but its recommended to use the Enzyme Commission Primary Name if available. Same length and order as `reaId`

You can ignore the last four columns. I think there are some entries there by mistake. I'll have a look at this :)

Once you have entered your user-defined pathway in `dat/custom_pwy.tbl` you can specificyll analyse your pathway in a genome using:

./gapseq find -l custom -p {NEW-PWY-ID} genome.fna.gz

In this way you don't need to delete the other pathway-database files "kegg_pwy.tbl" or "seed_pwy.tbl"

Hope this helpfs. Please let us know if this works for your case.

Best,
Silvio

**Comment by songweizhi** [comment]
Thanks for your detailed description, Silvio!!
I'll prepare the pwy file as you suggested here.
Weizhi
