### ISSUE TITLE
tmp files error & archaea

### ISSUE THREAD

**Issue by arianccbasile** [jotech/gapseq#35]
Dear GapSeq developers,
Thank you for the development of such an interesting source. I have installed it and everything went fine. I tried to run `./gapseq doall toy/myb71.fna.gz ` and I got the following error. 

`Checking updates for Bacteria /mnt/data_SSD/gapseq/src/../dat/seq/Bacteria
2020-07-24 16:30:56 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [193] -> ".listing" [1]
2020-07-24 16:31:22 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rev/sequences.tar.gz [21329707] -> "sequences.tar.gz" [1]
2020-07-24 16:31:22 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [194] -> ".listing" [1]
2020-07-24 16:36:55 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/unrev/sequences.tar.gz [254056885] -> "sequences.tar.gz" [1]
2020-07-24 16:36:56 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz [193] -> ".listing" [1]
2020-07-24 16:36:57 URL: ftp://ftp.rz.uni-kiel.de/pub/medsystbio/Bacteria/rxn/sequences.tar.gz [734237] -> "sequences.tar.gz" [1]
Updated Bacteria reviewed sequences
Updated Bacteria unreviewed sequences
Updated Bacteria additional reaction sequences
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  oggetto "finalize_filexp" non trovato
Calls: readAAStringSet ... .read_XStringSet -> fasta.index -> .finalize_filexp_list -> ::: -> get
Esecuzione interrotta
cat: /tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta: No such file or directory
cat: /tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta: No such file or directory
cp: cannot stat '/tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta': No such file or directory
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  oggetto "finalize_filexp" non trovato
Calls: readAAStringSet ... .read_XStringSet -> fasta.index -> .finalize_filexp_list -> ::: -> get
Esecuzione interrotta
cat: /tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta: No such file or directory
cat: /tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta: No such file or directory
cp: cannot stat '/tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta': No such file or directory
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  oggetto "finalize_filexp" non trovato
Calls: readAAStringSet ... .read_XStringSet -> fasta.index -> .finalize_filexp_list -> ::: -> get
Esecuzione interrotta
cat: /tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta: No such file or directory
cat: /tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta: No such file or directory
cp: cannot stat '/tmp/tmp.DjAQqNaSp8/subunit_tmp.fasta': No such file or directory
`

Do you have any suggestion on how to solve it?
Many thanks in advance. 

Arianna Basile

**Comment by jotech** [comment]
Hi Arianna, hm this looks strange indeed! It seems that something in the subunit detection is not running correctly. Do you have [exonerate](https://www.ebi.ac.uk/about/vertebrate-genomics/software/exonerate) installed? gapseq needs fastaindex and fastafetch from this package.

**Comment by arianccbasile** [comment]
Hi,
I followed your suggestion and I checked exonerate, but it is properly installed. I have performed additional checks on the other dependencies needed and they seem ok.
I was wondering if the problem could be due to lack of space in the "/tmp/" directory where gapseq is trying to save these files (there are a couple of Gb available). Alternatively, is it possible to set the working directory where gapseq is writing these files?
Thanks again for your assistance.
Arianna

**Comment by arianccbasile** [comment]
Hi,
After a series of trials, I managed to fix all the installation problems, they were mainly related to the sybilSBML that was not properly installed at the beginning. We would like to know if you are planning in the next future to complete the section related to Archaea pathways prediction and implementation in the models.
Thanks in advance.
Sincerely
Arianna

**Comment by Waschina** [comment]
Dear Arianna,
We are currently testing and implementing first features for the reconstruction of archaeal metabolic networks. We aim to add the possibility to reconstruct Archaea models in the next 3-4 weeks and provide an example workflow for Archaea in the gapseq documentation. 
In the meanwhile, the first step of gapseq, the pathway prediction, works already for Archaea. For instance:

`$gapseq find -p all -t Archaea ../genomes/genome.fna.gz`

I hope this helps and we will let you know, when more features for Archaea are implemented.

Best wishes
Silvio

**Comment by arianccbasile** [comment]
Dear Silvio,
thank you a lot for your help and the useful information. 
Looking forward to the Archaea universe then :)

Best regards,
Arianna

**Comment by arianccbasile** [comment]
Dear Silvio,
any news about the Archaea universe?  🥇

**Comment by Waschina** [comment]
Dear Arianna,
yes, we are still performing some tests for Archaea-specific pathways, but with the latest gapseq development version you can do the following example workflow to reconstruct a metabolic model for an Archaeal genome (in this example `xyz.fna.gz`):

```
#!/bin/bash

model="xyz"

# Reaction & pathway prediction
./gapseq find -p all -t Archaea $model.fna.gz

# Transporter prediction
./gapseq find-transport $model.fna.gz

# Draft network reconstruction 
./gapseq draft -r $model-all-Reactions.tbl -t $model-Transporter.tbl -p $model-all-Pathways.tbl -l 100 -b archaea

# Gapfilling
./gapseq fill -m $model-draft.RDS -n [media.csv] -c $model-rxnWeights.RDS -g $model-rxnXgenes.RDS -b 100

```

For `[media.csv]` please provide the path to the gapfilling media. In the gapseq directory `dat/media/` there are two minimal growth media, that we used in our test cases for Methanogens:

- `dat/media/MM_anaerobic_Acetate_H2.csv`
- `dat/media/MM_anaerobic_CO2_H2.csv`

We hope this helps and please let us know if you experience issues.

Best regards
Silvio

**Comment by jotech** [comment]
there is also a tutorial on archaea reconstruction out:
https://gapseq.readthedocs.io/en/latest/tutorials/archaea.html

**Comment by jotech** [comment]
please reopen if still an issue
