### ISSUE TITLE
Enzymes with two or more subunits in Bacteria but only one in Archaea

### ISSUE THREAD

**Issue by alegarritano** [jotech/gapseq#36]
Hello all,

currently I am trying to use gapseq to analyse the completeness of a specific pathway that happens both in Bacteria and Archaea. I am able to add the protein sequences that I am interested in for both Bacteria and Archaea in the EC.fasta file, however when I run gapseq, it misses the Archaea sequences as it is expecting that protein to have subunits instead of a single hit. 

Is there a way around this? 

thank you in advance,
Alessandro

**Comment by Waschina** [comment]
Hi Alessandro,

gapseq analyses the headers "> …" of the fasta sequences in a `[EC].fasta` in order to predict if the enzyme consists of subunits and if yes, which subunits are expected.
In your case, there might be substrings like "subunit xyz", "chain xyz", or "component xyz" in the headers of the archaeal protein sequences. One workaround could be so simply delete the respective parts in the sequence headers and see if gapseq accepts also single hits.

Hope this helps. If you still observe unexpected behaviour from gapseq, please let know.

Silvio

**Comment by alegarritano** [comment]
Hey Silvio,

I'm sorry for the super late reply. I kept using gapseq and completely forgot to check your answer.

Thanks for getting back to me :) 

Unfortunately, I'm returning here because I'm having issues when analyzing Archaea genomes. 
Currently I'm using gapseq setting the parameter `-z  3`, which will use reviewed + unreviewed sequences. 
When working with bacterial genomes, gapseq works perfectly. However, when I run it with `-t Archaea `, I get several error messages. It seems that there is a conflict with the unreviewed sequences for Archaea. I tried to delete the whole Archaea folder and download all the sequences again, but I'm still getting the same error. 

Do you have any suggestions on what I could do to fix this?

Once again, I'm really sorry for the late reply.
Thank you in advance,
Alessandro


Command line that I am using: 
gapseq find -t Archaea -p all -b 200 -z 3 Methanospirillum_hungatei.fna
Screenshot of the error messages: https://imgur.com/a/RBPzZY6

**Comment by jotech** [comment]
Hi Alessandro, I hope it's fine that I jump into the discussion :) I just had a look at this and you are right there was a problem with duplicated fasta entries. I uploaded a fix for it, maybe you can have a try?
best wishes johannes

**Comment by alegarritano** [comment]
Hi Johannes,
thanks for the quick reply.

Unfortunately, I'm still getting the same error. 

I deleted the folders with both the reviewed and unreviewed sequences, ran gapseq again, it downloaded the tar files from Kiel's repository and updated all the sequences. However, it's still returning the same duplicate fasta identifier message.

Thanks for the attention,
Alessandro
