### ISSUE TITLE
Required R Packages 

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#4]
Dear All,

It would be helpful if you write a code that installs all the required R packages automatically.
For example, my brand new R installation needed `data.table getopt stringr sybil` and for sure some others that I may have already installed but I cannot directly identify.

Kind Regards,
George

**Comment by jotech** [comment]
you are right! things are changing right now but we will come up with a detailed install description soon :)

**Comment by jotech** [comment]
readme is updated to current state of the art
