### ISSUE TITLE
Blast problems

### ISSUE THREAD

**Issue by iaunicorn** [jotech/gapseq#45]
> for bug reports and errors please report the output of: ./gapseq test.
>the output:
gapseq version: 1.1 1fa79b7
#######################
#Checking dependencies#
#######################
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
POSIX options:          GNU long options:
        -f progfile             --file=progfile
        -F fs                   --field-separator=fs
        -v var=val              --assign=var=val
        -m[fr] val
        -O                      --optimize
        -W compat               --compat
        -W copyleft             --copyleft
        -W copyright            --copyright
        -W dump-variables[=file]        --dump-variables[=file]
        -W exec=file            --exec=file
        -W gen-po               --gen-po
        -W help                 --help
        -W lint[=fatal]         --lint[=fatal]
        -W lint-old             --lint-old
        -W non-decimal-data     --non-decimal-data
        -W profile[=file]       --profile[=file]
        -W posix                --posix
        -W re-interval          --re-interval
        -W source=program-text  --source=program-text
        -W traditional          --traditional
        -W usage                --usage
        -W use-lc-numeric       --use-lc-numeric
        -W version              --version

To report bugs, see node `Bugs' in `gawk.info', which is
section `Reporting Problems and Bugs' in the printed version.

gawk is a pattern scanning and processing language.
By default it reads standard input and writes standard output.

Examples:
        gawk '{ sum += $1 }; END { print sum }' file
        gawk -F: '{ print $1 }' /etc/passwd

   GNU sed version 4.2.1
   grep (GNU grep) 2.10
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
   tblastn: 2.2.29+
   exonerate from exonerate version 2.2.0
   bedtools v2.29.2
   barrnap 0.9 - rapid ribosomal RNA prediction
   R version 3.5.0 (2018-04-23) -- "Joy in Playing"
   git version 2.19.2
Missing dependencies: 0

#####################
#Checking R packages#
#####################
ARGUMENT 'avail.packages~+~<-~+~installed.packages()' __ignored__

ARGUMENT 'i=0' __ignored__

ARGUMENT 'for(~+~pkg~+~in~+~needed.packages~+~){~+~' __ignored__

ARGUMENT '~+~~+~~+~~+~idx~+~<-~+~match(pkg,~+~avail.packages[,"Package"])' __ignored__

ARGUMENT '~+~~+~~+~~+~if(~+~!~+~is.na(idx)~+~){' __ignored__

ARGUMENT '~+~~+~~+~~+~~+~~+~~+~~+~cat("~+~~+~",pkg,~+~avail.packages[idx,"Version"],~+~"\n")~+~' __ignored__

ARGUMENT '~+~~+~~+~~+~}else{' __ignored__

ARGUMENT '~+~~+~~+~~+~~+~~+~~+~~+~cat("~+~~+~",~+~pkg,~+~"NOT~+~FOUND",~+~"\n")' __ignored__

ARGUMENT '~+~~+~~+~~+~~+~~+~~+~~+~i=i+1' __ignored__

ARGUMENT '~+~~+~~+~~+~}' __ignored__

ARGUMENT '}' __ignored__

ARGUMENT 'cat("\nMissing~+~R~+~packages:~+~",~+~i,~+~"\n\n")' __ignored__

##############################
#Checking basic functionality#
##############################
ARGUMENT 'data(Ec_core)' __ignored__

ARGUMENT 'sybil::optimizeProb(Ec_core)' __ignored__

Loading required package: Matrix
Loading required package: lattice.

**Comment by jotech** [comment]
Hi @iaunicorn thanks for opening a new issue for this!

The output is rather strange. I think we have to figure it out step by step.
At a first glimpse, Rscript seems to be not working correctly. Can you please copy the output of
```
Rscript --version
locate Rscript
```
?

**Comment by iaunicorn** [comment]
Hi jotech, thanks so much for your reply. 
> Rscript --version
R scripting front-end version 3.5.0 (2018-04-23)
>locate Rscript
/home/mao/R/R-3.5.0/bin/Rscript
/home/mao/R/R-3.5.0/doc/Rscript.1
/home/mao/R/R-3.5.0/src/gnuwin32/front-ends/Rscript.exe.manifest
/home/mao/R/R-3.5.0/src/gnuwin32/front-ends/Rscript64.exe.manifest
/home/mao/R/R-3.5.0/src/library/utils/man/Rscript.Rd
/home/mao/R/R-3.5.0/src/unix/Rscript
/home/mao/R/R-3.5.0/src/unix/Rscript.c
/home/mao/anaconda2/R-3.2.2/doc/Rscript.1
/home/mao/anaconda2/R-3.2.2/src/gnuwin32/front-ends/Rscript.exe.manifest
/home/mao/anaconda2/R-3.2.2/src/gnuwin32/front-ends/Rscript64.exe.manifest
/home/mao/anaconda2/R-3.2.2/src/library/utils/man/Rscript.Rd
/home/mao/anaconda2/R-3.2.2/src/unix/Rscript.c
/home/mao/anaconda2/envs/r-environment/bin/Rscript
/home/mao/anaconda2/envs/r-environment/lib/R/bin/Rscript
/home/mao/anaconda2/envs/r-environment/lib/R/library/xfun/html/Rscript.html
/home/mao/anaconda2/envs/r-environment/share/man/man1/Rscript.1
/home/mao/anaconda2/lib/R/library/xfun/html/Rscript.html
/home/mao/anaconda2/pkgs/r-base-3.5.1-h1e0a451_2/bin/Rscript
/home/mao/anaconda2/pkgs/r-base-3.5.1-h1e0a451_2/lib/R/bin/Rscript
/home/mao/anaconda2/pkgs/r-base-3.5.1-h1e0a451_2/share/man/man1/Rscript.1
/home/mao/anaconda2/pkgs/r-base-3.6.1-h9bb98a2_1/bin/Rscript
/home/mao/anaconda2/pkgs/r-base-3.6.1-h9bb98a2_1/lib/R/bin/Rscript
/home/mao/anaconda2/pkgs/r-base-3.6.1-h9bb98a2_1/share/man/man1/Rscript.1
/home/mao/anaconda2/pkgs/r-base-3.6.1-haffb61f_2/bin/Rscript
/home/mao/anaconda2/pkgs/r-base-3.6.1-haffb61f_2/lib/R/bin/Rscript
/home/mao/anaconda2/pkgs/r-base-3.6.1-haffb61f_2/share/man/man1/Rscript.1
/home/mao/anaconda2/pkgs/r-xfun-0.6-r36h6115d3f_0/lib/R/library/xfun/html/Rscript.html
/usr/local/bin/Rscript
/usr/local/lib/R/bin/Rscript
/usr/local/share/man/man1/Rscript.1

**Comment by jotech** [comment]
thanks! This looks good so far, what about:
``
Rscript -e 'print("hello")'
``

**Comment by iaunicorn** [comment]
It ran well. 
>xxx/tools/gapseq$ Rscript -e 'print("hello")'
[1] "hello"

**Comment by jotech** [comment]
alright, next step would be:

```
Rscript -e \
'
suppressMessages(library(sybil))
suppressMessages(library(glpkAPI))
data(Ec_core)
sol <- sybil::optimizeProb(Ec_core); sol.ok <- sol@lp_stat == 5
cat("Optimization test:", ifelse( sol.ok, "OK", "FAILED"), "\n")
'
```

**Comment by iaunicorn** [comment]
Yeah. I was not sure if the following output was ture or not.
xxx/tools$ Rscript -e \
> '
> suppressMessages(library(sybil))
> suppressMessages(library(glpkAPI))
> data(Ec_core)
> sol <- sybil::optimizeProb(Ec_core); sol.ok <- sol@lp_stat == 5
> cat("Optimization test:", ifelse( sol.ok, "OK", "FAILED"), "\n")
> '
ARGUMENT 'suppressMessages(library(glpkAPI))' __ignored__

ARGUMENT 'data(Ec_core)' __ignored__

ARGUMENT 'sol~+~<-~+~sybil::optimizeProb(Ec_core);~+~sol.ok~+~<-~+~sol@lp_stat~+~==~+~5' __ignored__

ARGUMENT 'cat("Optimization~+~test:",~+~ifelse(~+~sol.ok,~+~"OK",~+~"FAILED"),~+~"\n")' __ignored__

**Comment by jotech** [comment]
okay the original error again, are you on a mac ? [[1](https://stackoverflow.com/questions/21733137/how-to-pass-rscript-e-a-multiline-string)]
The problem seems to be multiline input, what about this:
```
Rscript -e 'suppressMessages(library(sybil)); suppressMessages(library(glpkAPI)); data(Ec_core); sol <- sybil::optimizeProb(Ec_core); sol.ok <- sol@lp_stat == 5; cat("Optimization test:", ifelse( sol.ok, "OK", "FAILED"), "\n"); '
```

**Comment by iaunicorn** [comment]
I ran it on Ubuntu 12.04 (an old server).
I got a right output this time (Optimization test: OK).

**Comment by jotech** [comment]
great! I updated the test script to avoid the issue you encountered. ``./gapseq test`` should work now!

But I think we still have the blast thing unsolved, can you please try the following:
```
fasta=dat/seq/Bacteria/rev/1.2.4.1.fasta
tmp_file=$(mktemp)
gunzip -c toy/myb71.fna.gz > $tmp_file
makeblastdb -in $tmp_file -dbtype nucl -out orgdb >/dev/null
tblastn -db orgdb -query $fasta -qcov_hsp_perc 75 -outfmt "6 $blast_format"
```

**Comment by iaunicorn** [comment]
great! I tested ./gapseq test. It worked well.

then I ran the following commands.
> makeblastdb -in myb71.fna -dbtype nucl -out orgdb >/dev/null   
(it worked well)

> tblastn -db orgdb -query 1.2.4.1.fasta -qcov_hsp_perc 75 -outfmt "6 $blast_format"
Error: Unknown argument: "qcov_hsp_perc"   (version: BLAST 2.2.29+)

**Comment by jotech** [comment]
Now we are getting close to your initial problem :) 

I checked it, your blast version is too old, ``qcov_hsp_perc `` was only introduced in Blast 2.2.30 from 10/2014.
This was wrongly mentioned in the install documentation which should be up to date by now!

Do you have the possibility to try a more recent blast?

**Comment by iaunicorn** [comment]
yes, I can.
Thanks so much. I will try it later.

**Comment by jotech** [comment]
please reopen if still an issue
