### ISSUE TITLE
could the annotated sequence as the input for gapseq

### ISSUE THREAD

**Issue by hongzhonglu** [jotech/gapseq#46]
Hi @jotech ,
Thanks for your nice work! I have a question about the input sequence format to build model using gapseq.
For example, I have 2000 annotated proteins in a genome, is this can be as input for gapseq to generate the metabolic model? Looking forward to your help!

Best regards,
Hongzhong

**Comment by Waschina** [comment]
Hi Hongzhong,

in the current Version, gapseq supports only the genome input as nucleotide fasta sequence. But I agree, a protein fasta for the annotated proteins as alternative input would be a useful extension. I will mark this as a feature request, which we will address in an upcoming version.
Until then, you could use the coding sequences of your proteins in a nucleotide fasta as gapseq input as a workaround. 

Best regards,
Silvio

**Comment by hongzhonglu** [comment]
Thanks so much! Looking forward to the new functions.

**Comment by jdwinkler-lanzatech** [comment]
Yes, this would be great-BLASTP (or DIAMOND) would be much faster than TBLASTN based on my experience.

**Comment by Waschina** [comment]
Yes, we actually have plans in those directions; specifically to employ DIAMOND.
But since this is not per se an _issue_ in the workflow, would it be okay with you to convert this conversion to the discussion forum (a new feature in github)?

**Comment by jdwinkler-lanzatech** [comment]
Definitely!
