### ISSUE TITLE
definition of model variable 

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#5]
Dear All,

I would like to inform you that if someone uses a fasta file without the `.fna `file extension but with the` .fasta` extension, the `gapseq_quickstart.sh` breaks when it comes to the following line because of the `model` variable. https://github.com/jotech/gapseq/blob/0675eee4bc949be76dd89be814f2c31b78366c02/gapseq_quickstart.sh#L14

Therefore, please revise the following line accordingly (e.g. with a stop function)
https://github.com/jotech/gapseq/blob/0675eee4bc949be76dd89be814f2c31b78366c02/gapseq_quickstart.sh#L4

Regards,
Georgios

**Comment by maringos** [comment]
Maybe...you should consider the table of the fasta extensions on this [page]( https://en.wikipedia.org/w/index.php?title=FASTA_format&section=5#Filename_extension).

**Comment by jotech** [comment]
i also saw this its already. i think it is not perfect to do it this way. best is to split the extension whatever it is.

**Comment by jotech** [comment]
should work now, can you please have a try?

**Comment by maringos** [comment]
It returns no error! Thanks!
