### ISSUE TITLE
Gapseq on multiple files

### ISSUE THREAD

**Issue by martsper** [jotech/gapseq#52]
Hi Johannes and Silvio,

It is beautiful to see how gapseq evolves!

I have an easy noob question for you, probably not related to gapseq, but rather to linux. How can I run gapseq on multiple genomes at once?

I tried something like the following, but it did not work:

./gapseq find -e 5.4.99.17 {1}:::/MarReF_Genomes/*.fa

Best,
Martin

**Comment by jotech** [comment]
hi Martin!
Thanks for your feedback :)
Actually something like this should do the trick:
```
parallel ./gapseq find -e 5.4.99.17 {} ::: toy/*.fna.gz
```
Does it work for you?

**Comment by martsper** [comment]
Hi Johannes,
This did the trick. Thanks for the quick solve. It is now running in the background and will take a while. I will come back to you if I have any complaints ;)
Keep up to good work!
Martin
