### ISSUE TITLE
gaps in Pathways and Reaction table

### ISSUE THREAD

**Issue by mmpust** [jotech/gapseq#58]
Hello, 
in the final pathway and reaction output tables, I always get large gaps if the name contains an "&".
For example
```
|PWY-5129|	sphingolipid biosynthesis (plants)	false	23	3	0	0	
|PWY-5137|	fatty acid &beta						
|PWY-5142|	acyl-[acyl-carrier protein] thioesterase pathway	false	0	0	0	0	
|PWY-5143|	long-chain fatty acid activation	true	100	0	0	0	RXN-7904 
|PWY-5148|	acyl-CoA hydrolysis	false	0	0	0	0	
|PWY-5151|	L-tyrosine degradation II	false	40	1	0	0	TYROSINE-AMINOTRANSFERASE-RXN 
|PWY-5155|	&beta					
```

It seems as if the line is just cut off and there is no information on prediction state or completeness. Is there something I can do about it?

Marie

**Comment by mmpust** [comment]
I wrote a python script that gives a clean output. If someone is interested, you can find it here: https://github.com/mmpust/scripts_2021 
gapseq_reaction_clean.py

Cheers, 
Marie

**Comment by Waschina** [comment]
Hi Marie,
I have checked my recent output tables and don't see this issue. But it would be good to understand were that issue stems from in your case in order to avoid other users experience the same issue.

I know you posted the `gapseq test` output already in the other issue, but could you maybe post it here again to have everything related to this issue in the same place?

@jotech Do you have an Idea, why the output tables could be corrupt in Marie's case?

**Comment by jotech** [comment]
this looks a bit strange indeed! @mmpust could you post a complete output file? From you python script I got that you are running gapseq on a SLURM cluster. Could you tell us the name of the operation system too?

**Comment by mmpust** [comment]
I found that this is an error in the text editor not a gapseq tool error, it just splits the output because there is a semicolon in the same line and then it overwrites the remainder line. Like this:

Real output
UDP-&alpha;-D-galactose biosynthesis 0,1 
&beta;-(1,4)-mannan degradation,0,1

Output (text editor)
UDP-&alpha
&beta

**Comment by jotech** [comment]
Hi Marie, thank you for the update on this!
You are right there is a semicolon in the pathway names from time to time, it comes as you mentioned from the Greek symbols in the names. That is also why we are using the 'tabulator' as file delimiter. 
I hope it is fully working for you now :)
