### ISSUE TITLE
Question related to model quality

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#6]
Dear All,

I would like to ask you concerning the model that is produced after the step `Rscript src/generate_GSdraft.R -r myb71-all-blast.tbl -t myb71-Transporter.lst -c myb71.fna -b 200`. How much should someone trust it? What is the difference with a model that is produced by ModelSeed? Can I have a robust gap-filled model without any knowledge on the diet?

These questions may sound naive, but they will help me to understand the general concepts of gap-filling.

Kind Regards,
Georgios

**Comment by Waschina** [comment]
Hej Georgios,

the script `generate_GSdraft.R` does not perform gapfilling. It basically constructs a draft network that consists of those reactions, that have either sequence- or pathway level evidence. The script also adds the biomass reaction to the draft model.

We did not compare the quality of the models with the draft models generated by modelSEED. This is work in progress.

Best,
Silvio
