### ISSUE TITLE
Final model biomass production issue

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [jotech/gapseq#61]
Hi,

I am not sure if this is actually a bug, but I noticed that some (example genome fasta attached) of the test models I generated produced no biomass when I tested them using CobraPy. However, the log for the attached model generation job says biomass was in fact produced during the model generation process:

```
 Filled components:     4 ( Thiamin-e0,Neu5Ac-e0-e0,CoA-e0-e0,Cytosine-e0-e0 )
 Added reactions:       12
 Final growth rate:     0.9102846
 
 Uptake at limit:
 L-Glutamate:1, L-Aspartate:1, L-Arginine:1, L-Histidine:1, L-Alanine:1, L-Threonine:1, L-Asparagine:1, Glycine:1, L-cysteine:1, Thiamine_B1:0.1
 
 Top 10 produced metabolites:
 H+:180.607, Acetate:96.822, NH3:7.451, CO2:4.116, GABA:1.691, H2S:0.935, EX cpd11416 c0:0.91, Ornithine:0.786, Thiamin:0.095, Succinate:0.015
 Wrote file Cljung.xml
```

Upon inspection, it looks like all the exchange reactions have (0, 1000) bounds in the final model output by Gapseq. I'm not sure why that would be the case given the results during gapfilling. I've attached the model as well in case y'all can shed some light on what is going on.
[Cljung.fna.xml.gz](https://github.com/jotech/gapseq/files/6157103/Cljung.fna.xml.gz)

[Cljung.fna.gz](https://github.com/jotech/gapseq/files/6157123/Cljung.fna.gz)

**Comment by Waschina** [comment]
Hi,
I can have a look at this. Could you maybe also share your gapfilling-media file? I have the feeling the issue might be somewhere there, or in the media file handling.

**Comment by jdwinkler-lanzatech** [comment]
Sure, here you go! It's possible I defined something incorrectly, but let me know if something pops out at you.

The actual command I ran is:

```
gapseq doall Cljung.fna media.txt

```
[media.txt](https://github.com/jotech/gapseq/files/6158441/media.txt)
.

**Comment by Waschina** [comment]
Thanks! The media file looks okay so far. I'll let the command run and check the output tomorrow.

Just to be sure: Gapseq creates two sbml files, one for the draft network and one for the gapfilled model. The xml-file looks more like the draft network. Could you check if in both files the lower bounds of exchange reactions are set to 0?

**Comment by jdwinkler-lanzatech** [comment]
I could be overwriting the final model accidentally then since I'm using a workflow management system to run the models. Let me re-run my analysis to see what is happening before you put in any more time.

**Comment by jdwinkler-lanzatech** [comment]
Yep, I was copying the *.xml files and somehow did not notice the draft/final model distinction. Sorry for the silly mistake on my part!

**Comment by Waschina** [comment]
No worries – I'm glad we solved it :)
