### ISSUE TITLE
./gapseq test does no longer work

### ISSUE THREAD

**Issue by Camaika** [jotech/gapseq#63]
Hey gapseq Team!

I just wanted to let you know, that running ./gapseq test  right after installation fails the BLAST test, because the file /dat/seq/Bacteria/rev/1.2.4.1.fasta does not yet exist. It is only created when running e.g.  ./gapseq doall ./toy/myb71.fna.gz first.

**Comment by Waschina** [comment]
Hi! 
I just realized the same issue today when installing gapseq on another machine. 
The issue could be solved by running `src/./update_sequences.sh` in the gapseq installation directory before running the test script.

I'll fix the test script so downloading the bulk of all reference sequences in not required for running the test.

Thanks for posting the issue!
