### ISSUE TITLE
Issue with some metabolic categories of models

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [jotech/gapseq#66]
Hi,

I've been working more on generated some test models, and I noticed some potential issues that I wanted to run by you. I've attached the models. Media is also included in case I am not defining something correctly ([media.txt](https://github.com/jotech/gapseq/files/6272358/media.txt)). I'm happy to tweak and re-run the model generation process if you have any suggestions.

* Lactococcus lactis (GCF_016028815.1, [GCF_016028815.1_ASM1602881v1_genomic.fna.xml.gz](https://github.com/jotech/gapseq/files/6272315/GCF_016028815.1_ASM1602881v1_genomic.fna.xml.gz)) does not produce L-lactic acid strangely, even though I believe it is a homofermentative LAB like the ones you mention in the Gapseq paper. This could be due to the lack of a suitable carbon source in my media definition (e.g. no glucose, fructose, or lactose)?

* Chain elongators such as Clostridium kluyveri (GCF_000016505.1, [GCF_000016505.1_ASM1650v1_genomic.fna.xml.gz](https://github.com/jotech/gapseq/files/6272332/GCF_000016505.1_ASM1650v1_genomic.fna.xml.gz)) appear unable to make hexanoate or octanoate via the reverse beta-oxidation pathway. However, since I have manually added this pathway to E. coli before as part of my research, I realize it might be a pain to automatically infer its presence and generate the requisite repeat units for chain elongation.

* Methanobrevibacter wolinii SH (GCF_000621965.1, [GCF_000621965.1_ASM62196v1_genomic.fna.xml.gz](https://github.com/jotech/gapseq/files/6272344/GCF_000621965.1_ASM62196v1_genomic.fna.xml.gz)), a hydrogenotrophic methanogen, appears to degrade ethanol only as its carbon and energy source without producing any methane. There is literature evidence to support ethanol consumption as an energy source at least, but there should still be methane production as a result. This assembly is pretty bad though, so that could be a factor too.

* Methylotrophs such as Methylococcus capsulatus Bath (GCF_000008325.1, [GCF_000008325.1_ASM832v1_genomic.fna.xml.gz](https://github.com/jotech/gapseq/files/6272352/GCF_000008325.1_ASM832v1_genomic.fna.xml.gz))  don't appear to consume methane via methane monooxygenase as one of their carbon sources. I think this reactions are missing from the model based on my initial examination, but it may be the case that the downstream pathways (usually serine or RUMP) might be annoying to implement.

Please let me know if I can provide any additional information!

**Comment by Waschina** [comment]
Hi again,

these looks like new challenges for gapseq :) I will put the genomes in my lists of models to build and test. Just on a first glimpse, the media might be missing a carbon source that _L. lactis_ might like. According to [BacDive](https://bacdive.dsmz.de/strain/14702) the sugars Maltose, Glucose and Lactose could be good candidates as food for _L. lactis_ . As for the other three cases, I think @jotech might also be interested to look into those.

**Comment by jdwinkler-lanzatech** [comment]
Yeah, I figured most LABs prefer more standard carbohydrates so I'll give that a shot first! Thanks for the quick response.

**Comment by jdwinkler-lanzatech** [comment]
Interestingly, no luck with L. lactis when adding glucose to the media. I can switch to another lactic acid bacteria without any issue, but might be worth looking into still.

**Comment by Waschina** [comment]
I did the reconstruction for L. lactis genome using the Fermentation Test medium from the gapseq paper ([FT.txt](https://github.com/jotech/gapseq/files/6285683/FT.txt)). The model predicted acetate and lactate as main fermentation products. Maybe you could give the FT-medium a try.

In general, the prediction from gapseq reconstructions can be highly dependent on the medium used for gapfilling and/or flux predictions. There's probably not one medium that fits all organisms.

**Comment by jdwinkler-lanzatech** [comment]
True, I can play around to see how I can expand/alter the media. I'll take a look at FT.

**Comment by jdwinkler-lanzatech** [comment]
Just remembered that most methylotrophs require O2 (at least the canonical methylotrophs-ANME organisms do not), so that likely explains the issue with that model.

**Comment by jotech** [comment]
please reopen if still active
