### ISSUE TITLE
grep errors while trying to run gapseq

### ISSUE THREAD

**Issue by Avitzm** [jotech/gapseq#67]
> for bug reports and errors please report the output of: ./gapseq test
I get the following grep errors while trying to run gapseq:
Unknown option: will-cite
grep: unrecognized option '--colsep'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--colsep'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: invalid option – 'j'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: invalid option – 'j'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--nonall'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--nonall'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--onall'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--onall'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--pipe'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--pipe'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--recend'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--recend'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--recstart'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: unrecognized option '--recstart'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: invalid matcher tcdb_header
grep: invalid matcher tcdb_header

Any idea how to solve this problem?

**Comment by Waschina** [comment]
Hi @Avitzm,

could you provide the output of the gapseq test script?
```
./gapseq test
```
This will help to identify the issue. 
Best
Silvio

**Comment by Avitzm** [comment]
When we run the test script:
./gapseq test
it passes all tests:

gapseq version: 1.1 d8fdd6a
linux
#1 SMP Mon Sep 30 14:19:46 UTC 2019

#######################
#Checking dependencies#
#######################
GNU Awk 4.0.2
sed (GNU sed) 4.2.2
grep (GNU grep) 2.20
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux
tblastn: 2.6.0+

** (process:31949): WARNING **: 22:11:04.140: Compiled with assertion checking - will run slowly
exonerate from exonerate version 2.4.0
bedtools v2.26.0
barrnap 0.9 - rapid ribosomal RNA prediction
R version 3.5.3 (2019-03-11) -- "Great Truth"
R scripting front-end version 3.5.3 (2019-03-11)
git version 1.8.3.1

Missing dependencies: 0



#####################
#Checking R packages#
#####################
data.table 1.13.6
stringr 1.4.0
sybil 2.1.5
getopt 1.20.3
reshape2 1.4.4
doParallel 1.0.16
foreach 1.5.1
R.utils 2.10.1
stringi 1.5.3
glpkAPI 1.3.2
BiocManager 1.30.10
Biostrings 2.50.2
jsonlite 1.7.2
CHNOSZ 1.4.0-3

Missing R packages:  0

##############################
#Checking basic functionality#
##############################
Optimization test: OK
Blast test: OK

Passed tests: 2/2


However when we try to run it:
./gapseq doall GCF.xfa
We get warnings (Compiled with assertion checking - will run slowly) and eventually (after several hours) get grep failure. (Looks like parsing problems due to wrong/missing output somewhere in the pipeline - just a guess).

**Comment by jotech** [comment]
Hi, could you provide information about the file ``GCF.xfa``? 
To work properly, gapseq needs a nucleotide fasta file as input

**Comment by Avitzm** [comment]
Yes, that’s what GCF.xfa is, a nucleotide fasta file.

**Comment by jotech** [comment]
alright thanks for the clarification!
I'm not completely sure but from the error output you posted it seems that your version of gnu parallel may be outdated!
Could you post the output of ``parallel --version``?
And do you have the possibility to update it? Otherwise it is also possible to run gapseq without gnu parallel:
``
./gapseq find -v 0 -k -b 200 -p all -m bacteria GCF.xfa
./gapseq find-transport -k -b 200 GCF.xfa
./gapseq draft -r GCF-all-Reactions.tbl -t GCF-Transporter.tbl -c GCF.xfa -u 200 -l 100 -p GCF-all-Pathways.tbl
./gapseq fill -m GCF-draft.RDS -n dat/media/ALLmed.csv -c GCF-rxnWeights.RDS -b 100 -g GCF-rxnXgenes.RDS
``
The ``-k`` parameter disables parallelization

**Comment by Avitzm** [comment]
Thanks. This is the output of parallel --version:
GNU parallel 20141022
Copyright (C) 2007,2008,2009,2010,2011,2012,2013,2014 Ole Tange and Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

**Comment by jotech** [comment]
thanks! this is a quite outdated version, do you mind updating it or using the non-parallel workflow I outlined before?

**Comment by Avitzm** [comment]
I’ll try, thanks.

**Comment by jotech** [comment]
please reopen if still an issue :)
