### ISSUE TITLE
Input custom annotations to gapseq

### ISSUE THREAD

**Issue by PedroMTQ** [jotech/gapseq#70]
I'm trying to create metabolic reconstructions using gapseq, but I'd like to use custom annotations. 

1. Would it be possible to include our own annotations? I plan on using a variety of reference datasets, are there any essential for correct network reconstruction (e.g., TCDB)?
2. If it's possible, which format should be used? 
3. I see that you are using MNXref, would it be sufficient to use it for cross-linking custom annotations to the IDs used during network construction?
4. The medium for gapfill only accepts KEGG compound IDs or are other DBs accepted?
5. Any plans on adding "Automatic refinement using experimental data"?
6. When gapseq where are intermediate files kept? I couldn't find them... are they all kept in RAM?
7. I read an issue saying it's better to use fna files rather than faa. Assuming I start with fna as input could I just do my own gene-calling and annotations ("branch") and then feed this data to gapseq ("merge" )?

Regards and thanks,
Pedro

**Comment by Waschina** [comment]
Dear Pedro,

sorry for the late response – I was thinking of different ways how to support/implement new things that you seem to have in mind. However, as a short answer, I'm afraid that implementing an additional branch that supports own annotations is not something we can currently support or implement in the short/mid-term. But of course we are open to contributions! 

Concerning the other questions you asked:
- Yes, we try to include links to MNXref whenever possible. Yet, this cross-referencing should be handled with caution as  metabolites/reactions are often used in different databases with small but significant differences (e.g. protonation states) and cross-referencing is not always complete.
- The gapfilling medium definition should have the identifiers from the ModelSEED namespace
- Plans for "Automatic refinement using experimental data" is definitely an interest, but we cannot promise specific features or roll-out dates at the moment
- Important intermediate files are all stored in the directory from where you start gapseq. Please refer to the [documentation](https://gapseq.readthedocs.io/en/latest/usage/output.html).
- Protein Fasta support: This feature request is already being discussed in #64 and #71 

Thanks and best wishes
Silvio

**Comment by PedroMTQ** [comment]
Dear Silvio,

Thank you for the answer! I'm currently unsure if I will proceed in this direction, but if you are open to contributions perhaps we could discuss how the annotation steps were implemented and I could try to implement something that would allow me to use custom annotations. I already went through some of the code in the gapseq_find.sh but perhaps it would be easier if you explained the steps to generate the various files from the find and find-transport steps?

Regards,
Pedro

**Comment by PedroMTQ** [comment]
Hello Silvio, 
I'm looking at the transporter.sh and am wondering which reference data you used?  I see that you use both the tcdb.fasta and transporter.fasta. Where does transporter.fasta come from? Also, is there any particular reason why only part of the tcdb is used here? I surmise that you removed all non-bacterial transporters as well as the ones without an ID starting with 1,2,3,4 (but I'm not entirely sure)?
What would happen if I were to provide more TCDB IDs than the ones accepted? Would they be automatically rejected or could they affect the model (e.g., orphan nodes)?

**Comment by Waschina** [comment]
Hi Pedro,

the file `transporter.fasta` contains manually defined sequences. Here we have added a few sequences based on literature information. The mapping to gapseq's reaction database is facilitated by parsing the sequence headers and the transporter classification. The set sequences from TCDB is limited to transporters found in microorganisms.

Adding sequences to tcdb.fasta or transporter.fasta can have an influence on model reconstructions, as potentially more gene-protein-transporter relationships could be found.

Best wishes
Silvio

**Comment by jotech** [comment]
please reopen if still active
