### ISSUE TITLE
Thanks for the response. I am using the libsbml version 5.17.0 and sybilSBML version 3.0.1.

### ISSUE THREAD

**Issue by gemii064** [jotech/gapseq#72]
Thanks for the response. I am using the libsbml version 5.17.0 and sybilSBML version 3.0.1.
Also if you have proper way to install it in server please let me know, the only way I installed sybilSBML was in my personal system. 

So for other model I have to edit the lines as you have mentioned and it will run in memote and cobratoolbox ?

I checked the model you have send me  in memote using command : memote report snapshot --skip test_find_metabolites_not_produced_with_open_bounds --skip test_find_metabolites_not_consumed_with_open_bounds TelongatusBP-1.xml

The score comes out to be 77% however there is error in Biomass consistency (under Biomass heading).
Can this error will produce unreliable result during growth simulation study in bacArena ?

_Originally posted by @hites77 in https://github.com/jotech/gapseq/issues/42#issuecomment-701133300_

**Comment by gemii064** [comment]
HI，
I have the same problem in #42. I can run gapseq using libsbml version 5.17.0 and sybilSBML version 3.0.1. When I try to update libsbml and sybilSBML, it always show errors:
** using staged installation
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for pkg-config... /usr/bin/pkg-config
configure: set compile and link flags according to pkg-config
configure: compile flags are -I/usr/local/include -I/usr/include/libxml2
configure: link flags are -L/usr/local/lib -lsbml
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sbml/SBMLTypes.h usability... yes
checking sbml/SBMLTypes.h presence... yes
checking for sbml/SBMLTypes.h... yes
checking for library containing readSBML... no
configure: error: Could not link to libSBML:
      use --with-sbml-lib or PKG_LIBS to specify the library path and the libraries to pass to the linker.
ERROR: configuration failed for package ‘sybilSBML’
* removing ‘/home/xxx/R/x86_64-pc-linux-gnu-library/4.0/sybilSBML’

I have try to install directly and  by conda, and  specify the include and lib folder. Can you tell me how to fix it?

**Comment by jotech** [comment]
Hi @gemii064, thanks for reporting this issue!

Installing gapseq using conda should be the easiest way to run gapseq on a cluster or server.
You said that you already tried installing gapseq using conda, do you mind to provide some additional information on you system?
Just to be on the same page, you followed the instructions mentioned [here](https://github.com/jotech/gapseq/blob/master/docs/install.md#conda)? 

I'm just wandering because the current libsbml version on [bioconda](https://anaconda.org/bioconda/libsbml) is 5.18 and this one is also needed because previous version do not work properly! Maybe you could you try to update it?
If this still does not work, then the output of the following commands might be helpful:
```
echo $CONDA_PREFIX
ls $CONDA_PREFIX/include/sbml
ls $CONDA_PREFIX/lib | grep sbml
```

**Comment by gemii064** [comment]
Hi, @jotech, 
  I have fixed it today by creating a new environment in Conda. The previous attempts were all in the old environment. Maybe there are some errors in path which I have not found.
Thanks a lot.
Best wishes.

**Comment by jotech** [comment]
great news! Thank you for trying gapseq :)
