### ISSUE TITLE
ammonia oxidation missing

### ISSUE THREAD

**Issue by jotech** [jotech/gapseq#73]
Ammonia oxidizing bacteria and archaea can employ ammonia (NH3) as electron donor in combination with CO2 as carbon source. A model organism for this is Nitrosopumilus maritimus [[1]](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=436308).

Right now, gapseq not able to find a set of reactions to allow the simulation of growth for ammonia oxidation when using a minimal medium containing NH3, CO2, O2.

The shortcoming is most likely caused by multiple factors:

1. Inconsistencies in catabolic reactions (types of cytochromes and quinones invovled not harmonized to remaining energy metabolism)
2. Problems in CO2 fixation pathways (especially HP/HB cycles is flawed)
3. Missing Reverse electron transport (no reduction of NAD(P) possible for electron donors with higher redox potential than -320mV)

This issue provides information on how the problem is handled.

The initial report was thankfully brought up by  Shan Zhang.

**Comment by jotech** [comment]
First succesful gapfilling:
```
1. Initial gapfilling: Make model grow on given media using all reactions
Utilized candidate reactions:  237
Gapfill summary:
Added reactions:       214
Added core reactions:  71
Final growth rate:     0.1671
```

what is working: ammonia uptake, co2 fixation, O2 as electron acceptor, NO production
unsure: N2 production
```
               rxn                  name     fba
 1: EX_cpd00001_e0       H2O-e0 Exchange  160.65
 2: EX_cpd00418_e0        NO-e0 Exchange   18.28
 3: EX_cpd00009_e0 Phosphate-e0 Exchange   -0.16
 4: EX_cpd00013_e0       NH3-e0 Exchange -100.00
 5: EX_cpd00067_e0        H+-e0 Exchange   68.34
 6: EX_cpd00011_e0       CO2-e0 Exchange   -6.81
 7: EX_cpd00007_e0        O2-e0 Exchange  -83.52
 8: EX_cpd00528_e0        N2-e0 Exchange   39.89
 9: EX_cpd00048_e0      Sulfate Exchange   -0.05
10: EX_cpd11416_c0        EX cpd11416 c0    0.17

```

**Comment by Waschina** [comment]
This is a though one

After making Complex I reversible and apply some database corrections to get rid of futile cycles I get this
```
1. Initial gapfilling: Make model grow on given media using all reactions
Utilized candidate reactions:  235
Gapfill summary:
Added reactions:       208 
Added core reactions:  60 
Final growth rate:     0.174194 
```
Current predicted phenotype: ammonia uptake, co2 fixation, O2 as electron acceptor, "NO" production, No N2 production.

We'll need to check why there's no NO -> N2 ...

Those results are from the current developments on the `biochem_experimental` branch.

**Comment by jotech** [comment]
With the last commits, the ammonia oxidation seems to work as expected:
```
              rxn                  name     fba 
1: EX_cpd00001_e0       H2O-e0 Exchange  132.05 
2: EX_cpd00418_e0        NO-e0 Exchange   79.36 
3: EX_cpd00009_e0 Phosphate-e0 Exchange   -0.16 
4: EX_cpd00013_e0       NH3-e0 Exchange  -81.22 
5: EX_cpd00067_e0        H+-e0 Exchange   50.83 
6: EX_cpd00011_e0       CO2-e0 Exchange   -6.53 
7: EX_cpd00007_e0        O2-e0 Exchange -100.00 
8: EX_cpd00048_e0      Sulfate Exchange   -0.04 
9: EX_cpd11416_c0        EX cpd11416 c0    0.16
```
- co2 fixation (via HP/HB) 
- nh3 uptake and oxidation with o2 as electron acceptor
- nictric oxide (NO) as product
