### ISSUE TITLE
Format of Diet

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#8]
Hi,

I am planning to use _gapsep_ with my own nutritional input. Should the exchange reactions comply to a specific format? For instance, the compounds in the uploaded diets are not formatted like `EX_MetabolitesID`, but `MetabolitesID`. Should I put filler numbers for the available compounds or can I **assume** flux = molecular quantity ?

Kind Regards,
Georgios

**Comment by maringos** [comment]
Thanks for the clarification! GM

**Comment by maringos** [comment]
Just for clarification, the correct format of the diet should be:

```
name | compounds | maxFlux
Al | cpd24344 | 5.744570454E-05
Alanine | cpd00035 | 0.8418075291
```

**Comment by jotech** [comment]
no it should be:
`compounds,name,maxFlux`
`cpd24344,Al,5.744570454E-05`
