### ISSUE TITLE
GNU R package cplexAPI: R Interface to C API of IBM ILOG CPLEX

### ISSUE THREAD

**Issue by joelmhaske** [jotech/gapseq#82]
Hi, Greetings. 

A quick query about the installation of cplexAPI package, could you please advise? I could run all the other packages to install all other packages, but for the cplexAPI package I'm slightly confused to figure out the problem. For instance, the first step is to set variables, where after running the command as demonstrated, I get the following error :
R CMD INSTALL --configure-args =" \
   PKG_CFLAGS='-m64 -fPIC' \
   PKG_CPPFLAGS='-I<cplex_dir>/cplex/include' \
   PKG_LIBS='-L${CPLEXLIBDIR} -lcplex -m64 -lm -pthread'" \ cplexAPI_1.4.0.tar.gz
Warning: unknown option '--configure-args'
Warning: invalid package '= PKG_CFLAGS='-m64 -fPIC' PKG_CPPFLAGS='-I<cplex_dir>/cplex/include' PKG_LIBS='-L -lcplex -m64 -lm -pthread''
Warning: invalid package ' cplexAPI_1.4.0.tar.gz'
Error: ERROR: no packages specified

And for information, I am trying to get gapseq models on an ubuntu docker image. Many thanks in advance.

**Comment by Waschina** [comment]
Hi,

I am not sure what causes the issue but a few things to consider:
1. Please make sure that cplex is correctly installed on your system (not the free community version but the full cplex installation)
2. The r-Package 'cplexAPI' comes with [detailed installation instructions](https://cran.r-project.org/web/packages/cplexAPI/INSTALL). We recommend to follow those.
3. When running long commands in bash with line breaks, please make sure to use backslashes to escape the line breaks.

The command that worked for me is:
```sh
R CMD INSTALL --configure-args=" \
    PKG_CFLAGS='-m64 -fPIC' \
    PKG_CPPFLAGS='-I/opt/ibm/ILOG/CPLEX_Studio1210/cplex/include' \
    PKG_LIBS='-L/opt/ibm/ILOG/CPLEX_Studio1210/cplex/lib/x86-64_linux/static_pic -lcplex -lm -pthread -ldl'" \
    cplexAPI_1.4.0.tar.gz
```
The paths might be different depending on your cplex installation and system.

Best
Silvio

**Comment by joel8484** [comment]
> Hi,
> 
> I am not sure what causes the issue but a few things to consider:
> 
>     1. Please make sure that cplex is correctly installed on your system (not the free community version but the full cplex installation)
> 
>     2. The r-Package 'cplexAPI' comes with [detailed installation instructions](https://cran.r-project.org/web/packages/cplexAPI/INSTALL). We recommend to follow those.
> 
>     3. When running long commands in bash with line breaks, please make sure to use backslashes to escape the line breaks.
> 
> 
> The command that worked for me is:
> 
> ```shell
> R CMD INSTALL --configure-args=" \
>     PKG_CFLAGS='-m64 -fPIC' \
>     PKG_CPPFLAGS='-I/opt/ibm/ILOG/CPLEX_Studio1210/cplex/include' \
>     PKG_LIBS='-L/opt/ibm/ILOG/CPLEX_Studio1210/cplex/lib/x86-64_linux/static_pic -lcplex -lm -pthread -ldl'" \
>     cplexAPI_1.4.0.tar.gz
> ```
> 
> The paths might be different depending on your cplex installation and system.
> 
> Best
> Silvio

Hi Silvio, 

Thanks for your prompt reply. Your solution was correct, about installing the version of CPLEX installed from IBM. However, I tried running the code again, and it did start installing the package but it ran into an error: "configure: error: Could not find cplex.h:
      cplexAPI requires IBM ILOG CPLEX from http://www.ibm.com/.
      use --with-cplex-include or PKG_CPPFLAGS to specify the include path.
ERROR: configuration failed for package 'cplexAPI'
* removing '/usr/local/lib/R/site-library/cplexAPI'"
When I manually checked inside the include folder, I could see that cplex.h is located in the path. Did you face the same issue as well? Also, In the documentation for installing the cplexAPI package, we can use either of the 4 steps for installation is that correct? It doesn't mean that I have to run all the commands in the given order?

Again, many thanks for replying.
Kind Regards,
Joel

**Comment by joelmhaske** [comment]
> Hi,
> 
> I am not sure what causes the issue but a few things to consider:
> 
> 1. Please make sure that cplex is correctly installed on your system (not the free community version but the full cplex installation)
> 2. The r-Package 'cplexAPI' comes with [detailed installation instructions](https://cran.r-project.org/web/packages/cplexAPI/INSTALL). We recommend to follow those.
> 3. When running long commands in bash with line breaks, please make sure to use backslashes to escape the line breaks.
> 
> The command that worked for me is:
> 
> ```shell
> R CMD INSTALL --configure-args=" \
>     PKG_CFLAGS='-m64 -fPIC' \
>     PKG_CPPFLAGS='-I/opt/ibm/ILOG/CPLEX_Studio1210/cplex/include' \
>     PKG_LIBS='-L/opt/ibm/ILOG/CPLEX_Studio1210/cplex/lib/x86-64_linux/static_pic -lcplex -lm -pthread -ldl'" \
>     cplexAPI_1.4.0.tar.gz
> ```
> 
> The paths might be different depending on your cplex installation and system.
> 
> Best
> Silvio

**Comment by joelmhaske** [comment]
**UPDATE**

I used the 4th step demonstrated in the documentation and it seems like it was successfully able to install the package. :)

Many Thanks Silvio, for your comments.
