### ISSUE TITLE
Warning messages occuring during pathway prediction

### ISSUE THREAD

**Issue by joelmhaske** [jotech/gapseq#83]
Hi team,

Just an observation, I have the gapseq running in the background for the strain Lachnospiraceae bacterium, I tried running a command for the first time, so just for testing, I used the command for pathway prediction, while it has been running seamlessly I'm thinking for some while now, I can see it going through the nucleotide database and search through for metabolites and presence of reactions, however, I can see the following in repetition:

	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_NUMERIC = "en_US.UTF-8",
	LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:

Was just curious to know whether I'm facing any issue here which is impacting the process of model reconstructions or anything otherwise? Could you please provide your insights?

Many thanks and Kind Regards,
Joel

**Comment by joelmhaske** [comment]
Hi, 
It was left out from me to enter one more error message which is occuring : "BLAST Database error: No alias or index file found for nucleotide database [orgdb] in search path [/tmp/tmp.GcBDhKPWVY::]"
This might help understand what the issue is?

Thanks and Regards,
Joel

**Comment by Waschina** [comment]
Hi Joel,
could you provide the output of the script `./gapseq test` and the exact commands, that you have ran and resulted in the issue?

**Comment by joelmhaske** [comment]
Dear Waschina,

Below is the output of ./gapseq test

root@adbae60311a4:/gapseq/ggapseq# ./gapseq test
gapseq version: 1.1 6bb9af1
linux-gnu
#82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 


#######################
#Checking dependencies#
#######################
awk: not an option: --version

sed (GNU sed) 4.4
grep (GNU grep) 3.1
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
tblastn: 2.6.0+
exonerate from exonerate version 2.4.0
bedtools v2.26.0
Synopsis:
  barrnap 0.8 - rapid ribosomal RNA prediction
Author:
  Torsten Seemann <torsten.seemann@gmail.com>
Usage:
  barrnap [options] <chromosomes.fasta>
Options:
  --help            This help
  --version         Print version and exit
  --citation        Print citation for referencing barrnap
  --kingdom [X]     Kingdom: arc euk bac mito (default 'bac')
  --quiet           No screen output (default OFF)
  --threads [N]     Number of threads/cores/CPUs to use (default '8')
  --lencutoff [n.n] Proportional length threshold to label as partial (default '0.8')
  --reject [n.n]    Proportional length threshold to reject prediction (default '0.5')
  --evalue [n.n]    Similarity e-value cut-off (default '1e-06')
  --incseq          Include FASTA input sequences in GFF3 output (default OFF)

R version 4.0.2 (2020-06-22) -- "Taking Off Again"
R scripting front-end version 4.0.2 (2020-06-22)
git version 2.17.1
GNU parallel 20161222

Missing dependencies: 0


#####################
#Checking R packages#
#####################
data.table NOT FOUND 
stringr 1.4.0 
sybil 2.2.0 
getopt 1.20.3 
doParallel 1.0.16 
foreach 1.5.1 
R.utils 2.10.1 
stringi 1.6.2 
glpkAPI 1.3.2 
BiocManager 1.30.16 
Biostrings 2.58.0 
jsonlite 1.7.2 
CHNOSZ 1.4.1 

Missing R packages:  1 


##############################
#Checking basic functionality#
##############################
Optimization test: OK 
Blast test: OK

Passed tests: 2/2


........And the above warning messages appear when I used  the command :
root@adbae60311a4:/gapseq/ggapseq# ./gapseq find -p all toy/Lachnospiraceae_bacterium_3-1-57FAA_CTI_V1_genomic.fna.gz 
The above ran for more than 5-6 hours and I had to terminate it midway
 
2) On the contrary, I get a similar error:
 
perl: warning: Falling back to the standard locale ("C").
Error: package or namespace load failed for 'stringr':
 package 'stringr' was installed before R 4.0.0: please re-install it
Execution halted
cat: /tmp/tmp.qtb7uQ3U6J/subunit_tmp.fasta: No such file or directory
cat: /tmp/tmp.qtb7uQ3U6J/subunit_tmp.fasta: No such file or directory
cp: cannot stat '/tmp/tmp.qtb7uQ3U6J/subunit_tmp.fasta': No such file or directory
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_NUMERIC = "en_US.UTF-8",
	LANG = (unset)
    are supported and installed on your system.

.....after running the command:
root@adbae60311a4:/gapseq/ggapseq# ./gapseq doall toy/Lachnospiraceae_bacterium_3-1-57FAA_CTI_V1_genomic.fna.gz 

It does say that stringr package is installed before updating R to version 4.0.2? I created ran the installation script again for gapseq and it still showed the same warning.

Thanks very much for your time and consideration  :)
Warm Regards,
Joel

**Comment by Waschina** [comment]
Hi Joel, 
not all dependencies of gapseq are properly installed.

What you could try:
- (re)install the R-packages `data.table` and `stringr`
- I would suggest do update barrnap to version 0.9
- also, maybe you could try to update perl to version 30 since you are getting warnings from it
- also, awk already fails with `awk --version`, although I don't know why.

Alternatively, you could follow the gapseq installation instruction for conda, which should include all dependencies to get a run done smoothly: https://gapseq.readthedocs.io/en/latest/install.html#conda

Best
Silvio

**Comment by joelmhaske** [comment]
Hi Silvio,

Thanks for the alternative. I installed gapseq using conda, although I couldn't get perl to update to the latest version so I wasn't able to silence the warnings. I ran `./gapseq test` and the output is as follows:

`#######################
#Checking dependencies#
#######################
GNU Awk 5.1.0, API: 3.0
sed (GNU sed) 4.8
grep (GNU grep) 3.4
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
tblastn: 2.5.0+
exonerate from exonerate version 2.4.0
bedtools v2.30.0
barrnap 0.9 - rapid ribosomal RNA prediction
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
R scripting front-end version 3.6.1 (2019-07-05)
git version 2.23.0
GNU parallel 20161222

Missing dependencies: 0


#####################
#Checking R packages#
#####################
data.table 1.12.2 
stringr 1.4.0 
sybil 2.1.5 
getopt 1.20.3 
doParallel 1.0.14 
foreach 1.4.4 
R.utils 2.8.0 
stringi 1.4.3 
glpkAPI 1.3.2 
BiocManager 1.30.4 
Biostrings 2.54.0 
jsonlite 1.6 
CHNOSZ 1.4.1 

Missing R packages:  0 


##############################
#Checking basic functionality#
##############################
Optimization test: OK 
Blast test: OK

Passed tests: 2/2
`

***Final update after creating pathway, transporter and reaction tables, creating draft models and, gapfilling done which seems pretty okay. Pretty happy with how effortlessly it got done. Just that for me it took lot more than hours to complete the reconstruction. Also, I have multiple strains which I need to run through in gapseq so I saw #52 and will the command `parallel ./gapseq find -e 5.4.99.17 {} ::: toy/*.fna.gz` suffice? and does it have any upper bound as to how many strains it can complete at once?

Again, thanks very much for this handy tool. :)
Best Regards,
Joel

**Comment by Waschina** [comment]
Hi Joel,
this looks already much better :)

The perl warnings you get might not be an issue, but I can't promise. Maybe you could check Stackoverflow or other pages what the source of the warning could be and what solutions might exists.

Everything else looks just fine from the test script output. So happy gapseq'ing :)

Yes, the runtime for a model could be several hours. The other following gapseq modules need significant less time and should finish within seconds or minutes. On a multi-core system you can save a lot of time when starting gapseq in parallel for several genomes e.g. with
```sh
parallel ./gapseq find -p all {} ::: genomeDir/*.fna.gz
```
GNU parallel will automatically start as many reconstructions at once so tasks are nicely distributed across available cores; so you don't need to decide how many recons are being calculated at once. 

Best
Silvio
