### ISSUE TITLE
Questions about the result of using customer medium Gapfilling

### ISSUE THREAD

**Issue by zhouqCui** [jotech/gapseq#84]
Hello,

I try to build up the model by using my own medium. This medium has been published before and my target strains can grow in lab test (they did not grow as well as nutrient rich medium like LB). However, the result of Gapfilling showed "final growth rate:0". I try to use M9 medium to test my target strain for Gapfilling as a control which works well. The final growth rate is around 0.8. So I suppose the problem may caused by my medium? Below I have attached my medium file and the result of Gapfilling, would you give me some advice? 

thank you very much!

MEDIUM:
compounds | name | maxFlux
cpd00027 | Glucose | 10
cpd00067 | H+ | 100
cpd00099 | Cl- | 100
cpd00205 | K+ | 100
cpd00254 | Mg | 100
cpd00971 | Na+ | 100
cpd00001 | H2O | 100
cpd00009 | Phosphate | 100
cpd00011 | CO2 | 100
cpd00013 | NH3 | 10
cpd00082 | D-Fructose | 1
cpd00129 | L-Proline | 0.1
cpd00132 | L-Asparagine | 0.1
cpd00053 | L-glutamine | 0.1
cpd00054 | L-Serine | 1
cpd00133 | Nicotinamide | 0.1
cpd00007 | O2 | 27
cpd10515 | Fe2+ | 100
cpd10516 | fe3 | 100
cpd00058 | Cu2+ | 100
cpd00063 | Ca2+ | 100
cpd00030 | Mn2+ | 100
cpd00034 | Zn2+ | 100
cpd00149 | Co2+ | 100

RESULT:
1. Initial gapfilling: Make model grow on given media using all reactions
Utilized candidate reactions:  391Warning message:
In gapfill4(mod.orig = mod.orig, mod.full = mod, rxn.weights = copy(rxn.weights),  :
  Final model Ea110_genome cannot produce enough target even when all candidate reactions are added! obj=9.16282921393675e-13 lp_stat=5

2. Biomass gapfilling using core reactions only
Gapfill summary:
Filled components:     1 ( UTP-c0 )
Added reactions:       6 
Final growth rate:     0 

2b. Anaerobic biomass gapfilling using core reactions only
Gapfill summary:
Filled components:     0 (  )
Added reactions:       6 
Final growth rate:     0 

3. Energy source gapfilling with core reactions only
Gapfill summary:
Filled components:     10 ( L-Lysine-e0,L-Leucine-e0,Xylose-e0,L-Valine-e0,Taurine-e0,L-Isoleucine-e0,GABA-e0,D-Serine-e0,L-Idonate-e0,Cholate-e0-e0 )
Added reactions:       232 
Final growth rate:     0 

4. Checking for potential metabolic products with core reactions only
Gapfill summary:
Filled components:     2 ( D-Fructose-e0,Riboflavin-e0-e0 )
Added reactions:       2 
Final growth rate:     0 

Uptake at limit:
Choline:0, H2S2O3:0, PAN:0, Maltodextrin:0, NAD:0

**Comment by Waschina** [comment]
Hi,

the medium does not contain any source of sulfur. You could try to add for example
- sulfate (cpd00048)
- H2S (cpd00239)

I hope this solves the issue

Best
Silvio

**Comment by zhouqCui** [comment]
Hello Silvio,

I have tried all of my strains and it works well!!! Thank you very much!

Zhouqi

**Comment by Waschina** [comment]
Perfect :)
