### ISSUE TITLE
Empty columns in gene matrix and some minor issues

### ISSUE THREAD

**Issue by hites77** [jotech/gapseq#86]
I was doing sanity check of the model generated from gapseq through cobratoolbox and found that model stood well in most of the test. However, there were lots of empty column in rxngenematrix and also some duplicate reactions in same compartment. Also i found that there are nearly 60% flux inconsistent metabolites and around 40% flux inconsistent reactions. So want to know whether it will affect FBA analysis or by removing it will result in more high quality model.

Also want to know that as the gapseq is constantly updated, so is there way to say that if I ran model one month back will be of less quality than after one month. Or it can be highlighted that this change can have large or small impact in generated model.

**Comment by Waschina** [comment]
Hi,

I am not experienced in using the cobratoolbox, so could you perhaps provide some more detail? 
- do empty columns in rxngenematrix denote reactions without gene associations or genes without mappings to reactions?
- what are the definitions of "flux inconsistent metabolites" and " flux inconsistent reactions"? What does it indicate?

Yes, we are constantly working on gapseq. And of course, we make changes that, we think, make the models better. The impact of the changes on the models depends on the organism/genome, thus, we cannot make a general and quantitative statements on the level of improvement for every model.

Best wishes
Silvio
