### ISSUE TITLE
Improvements: Clean up tmpdir and bypass databases download

### ISSUE THREAD

**Issue by glucksfall** [jotech/gapseq#87]
> for bug reports and errors please report the output of: ./gapseq test

Hello @jotech,

I'd like to suggest cleaning up the tmpdir after running gapseq_find.sh and transporter.sh. I'm reconstructing GSMMs for >700 bacteria strains and the storage was exhausted. I did 270 reconstructions that needed around 50GB.

Also, it would be nice to bypass the databases download step(s).

Thanks for your time
Best regards.

**Comment by glucksfall** [comment]
Sorry, I didn't see the issue #68 about deleting tmpdir. However, only predict_biomass_from16S.sh deletes the tmpdir, not the other scripts.

Best!

**Comment by Waschina** [comment]
Hi,

after the commit by @jotech (ba47ef026bae4d8330cd56d5b4a586fee607d5f1) the tmpdir should in principle be deleted once 'gapseq find' has successfully finished. I reconstructed job arrays of more than 5000 genomes and and never ran into storage issues. I will try to figure out what could be the causes of the issue in your case.

Best
Silvio

**Comment by glucksfall** [comment]
Hi @Waschina,

Thank you for your answer. Now I understand the purpose of ```trap 'rm -rf "$tmpdir"' EXIT```, and I also see it is weird that the tmp directories are not being deleted. Could it be related that I'm using SLURM to queue jobs? The output signal for all completed jobs is 0 and that should be OK to delete files, right?

Moreover, I have 64 directories from gapseq (25 with results from blast), the storage problem is not generated by gapseq itself. Those 64 directories only have 1.5GB in total, so I will close this issue.

Best!

**Comment by Waschina** [comment]
Okay. We are also using SLURM for large batches of jobs. If you notice any odd behavior by gapseq, please let us know.

Best
