### ISSUE TITLE
Multimer Enzymes not predicted

### ISSUE THREAD

**Issue by Waschina** [jotech/gapseq#9]
GapSeq predicts that the enzyme with EC 1.6.5.3 should consists of 12 different subunits. But only 6 are found in E. coli, where all should be present.

The command for reproduction of this issue:

`gapseq.sh -p PWY0-1335 -b 200 GCF_000005845.2_ASM584v2_genomic.fna.gz`

This genome of E. coli can be downloaded [here](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz)

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz

**Comment by jotech** [comment]
should work better now :)
