### ISSUE TITLE
Question about fill medium

### ISSUE THREAD

**Issue by Erique29** [jotech/gapseq#92]
Hi,

the maxFlux values correspond to the (potential) maximum uptake rates of the nutrient by the organism. The unit is `mmol/hr/gDW` (mmol per hour and per gram dry weight).

As an example: The maximum uptake rate of Glucose by _Salmonella typhimurium_ ranges from 7.6 to 21.6 mmol/hr/dDW ([link](https://bionumbers.hms.harvard.edu/bionumber.aspx?id=109672&ver=3&trm=glucose+uptake+rate&org=)).

Hope this helps

_Originally posted by @Waschina in https://github.com/jotech/gapseq/issues/80#issuecomment-860205845_

**Comment by Erique29** [comment]
Hi @Waschina ,
  Can I use the same medium file like dat/medium/LB in many bacteria's models? Or I should change the maxflux in every bacteria model like you said above? All the bacteria grow in same medium. Thank for your help!

**Comment by Waschina** [comment]
Hi @Erique29,

yes, if you know that they can all grow in the same LB medium, you can also use the same LB-gapfill medium for all the organisms.

**Comment by Erique29** [comment]
Thanks！
