### ISSUE TITLE
Are there ready-to-use gapseq-rebuilt models?

### ISSUE THREAD

**Issue by Ezio0o** [jotech/gapseq#94]
I have tried to install and rebuild several examples by my self and the running time is too slow for a large batch rebuild. Are there any ready-to-use gapseq-rebuilt models I can download? Thank you!

**Comment by jotech** [comment]
hi @Ezio0o 
good point we will upload a larger collection of gapseq models in the following days!

**Comment by Ezio0o** [comment]
Glad to hear that! Many thanks :)

**Comment by Waschina** [comment]
Hi!
We uploaded gapseq models for all 5414 genomes from the Human Reference Gut Microbiome (HRGM) collection.

https://zenodo.org/record/5779237

Best wishes

**Comment by Ezio0o** [comment]
> Hi! We uploaded gapseq models for all 5414 genomes from the Human Reference Gut Microbiome (HRGM) collection.
> 
> [zenodo.org/record/5779237](https://zenodo.org/record/5779237)
> 
> Best wishes

Thank you! Grateful for your kindly support!
