### ISSUE TITLE
gapseq find -t

### ISSUE THREAD

**Issue by nick-youngblut** [jotech/gapseq#97]
It appears that the possible input values for `gapseq find -t` are: `[Bacteria, Gram_neg, Gram_pos, auto]`, but this is not described in the `gapseq find` script docs (just `default: Bacteria`). 

Also, there is no explanation of the `auto` option, which triggers `predict_biomass_from16S.sh`:

```
if [ "$taxonomy" == "auto" ]; then
    pred_biom=$($dir/predict_biomass_from16S.sh "$fasta")
```

...which I'm guessing is the same as in `gapseq draft`

**Comment by Waschina** [comment]
Thank you for pointing this out. I amended the option descriptions in `gapseq find` and `gapseq draft`.
