### ISSUE TITLE
gapseq fill ec-code error

### ISSUE THREAD

**Issue by JosuaCarl** [jotech/gapseq#99]
Hello, 
when I am executing gapseq fill with my model, in the end I get:

> Top 10 produced metabolites:
> NA:NA 
> Error in .checkTypos(e, names_x) : 
>   Object 'ec' not found. Perhaps you intended seed
> Calls: addReactAttr ... tryCatchList -> tryCatchOne -> <Anonymous> -> .checkTypos
> Execution halted

And when I print out mod@react_attr in the R file addReactAttr.R, I see, that it does not have a column named ec.

> for bug reports and errors please report the output of: ./gapseq test
Here is my gapseq test:
>  gapseq: prediction and analysis of bacterial metabolic pathways and genome-scale networks
> 
> Usage:
>   gapseq (find | find-transport | draft | fill | doall | adapt) (...)
>   ... middle part omitted for shortness
>   -h              Show this screen.
>   -n              Enable noisy verbose mode.

I would be very glad to find out the cause of the error.

**Comment by jotech** [comment]
Hi @JosuaCarl 
this sounds strange indeed! I need a bit more details to see what is going wrong. Do you mind providing your draft model plus temporary files (rxnWeights.RDS, rxnXgenes.RDS) and the actual command you used for `gapseq fill`?

**Comment by JosuaCarl** [comment]
Hi @jotech 
So, I think I already got a little bit at what went wrong. I naively tried to use gapseq fill on my own model, which was drafted by CarveMe and used the naming convention from BiGG, while gapseq relies on Model SEED. I uses  the rxnWeights and rxnXgenes, from gapseq find/find-transport/draft from the gene sequence of my organism.
I suspect that the non matching sets of identifiers caused no ec-codes to be appended to the dataframe.
The difference in naming convention unfortunatrly also makes it infeasible for me to compare both models, even when I use the completed draft by gapseq, but the method (gapseq fill) now works as it should.
Thank you very much for your reply.

**Comment by jotech** [comment]
i see this makes sense and I agree the differences in namespace definitely caused the errors you encountered!
For comparing bigg and seed namespaces, you might have a look at:
- https://github.com/jotech/gapseq/blob/master/dat/SEED2VMH_translation_edited.csv
- https://www.metanetx.org/mnxdoc/mnxref.html 

which at least could at assist you in matching reactions ids.
In addition, comparing model quality by using memote (https://memote.io) or the predicted phenotype vs. literature/databases (e.g. https://bacdive.dsmz.de/) could maybe another alternative?
